// Generates src/styles/tokens.css from src/design/tokens.ts (P-07).
// Runs under `node --experimental-strip-types` so it can import the .ts source directly.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const { tokens } = await import('../src/design/tokens.ts');

const kebab = (s) => String(s).replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
const vars = (prefix, obj, indent = '  ') =>
  Object.entries(obj)
    .map(([k, v]) => `${indent}--${prefix}-${kebab(k)}: ${v};`)
    .join('\n');
const colorVars = (set, indent = '  ') => vars('color', set, indent);
const metalVars = (set, indent = '  ') => vars('metal', set, indent);

const lines = [];
lines.push('/* GENERATED by `npm run tokens` from src/design/tokens.ts. Do not edit by hand. */');
lines.push(':root {');
lines.push(colorVars(tokens.color.light));
lines.push(`  /* Metal finish: ${tokens.metalDefault} by default; override with <html data-metal="..."> (every key of tokens.metal). */`);
lines.push(metalVars(tokens.metal[tokens.metalDefault]));
lines.push(vars('brand', tokens.brand));
lines.push(vars('gradient', tokens.gradient));
for (const [k, v] of Object.entries(tokens.font)) lines.push(`  --font-${k}: ${v};`);
lines.push(vars('tracking', tokens.tracking));
lines.push(vars('weight', tokens.weight));
for (const [k, v] of Object.entries(tokens.radius)) lines.push(`  --radius-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.space)) lines.push(`  --space-${k}: ${v};`);
lines.push(vars('shadow', tokens.shadow));
lines.push(`  --hairline: ${tokens.hairline};`);
lines.push(`  --target: ${tokens.target};`);
lines.push(`  --focus-ring: ${tokens.focusRing};`);
lines.push(`  --scale: ${tokens.scale[0].scale};`);
lines.push('  color-scheme: light;');
lines.push('}');
lines.push('');
for (const [name, set] of Object.entries(tokens.metal)) {
  lines.push(`:root[data-metal="${name}"] {`);
  lines.push(metalVars(set));
  lines.push('}');
  lines.push('');
}
// Theme on :root (ThemeProvider) and on any element: a `data-theme` island (e.g. a dark tile inside a light page).
lines.push(':root[data-theme="dark"],');
lines.push('[data-theme="dark"] {');
lines.push(colorVars(tokens.color.dark));
lines.push('  color-scheme: dark;');
lines.push('}');
lines.push('');
lines.push('[data-theme="light"] {');
lines.push(colorVars(tokens.color.light));
lines.push('  color-scheme: light;');
lines.push('}');
lines.push('');
lines.push('@media (prefers-color-scheme: dark) {');
lines.push('  :root:not([data-theme="light"]) {');
lines.push(colorVars(tokens.color.dark, '    '));
lines.push('    color-scheme: dark;');
lines.push('  }');
lines.push('}');
lines.push('');
lines.push('/* Responsive matrix bands (P-01): --scale multiplies the 16 px root size. */');
for (const band of tokens.scale) {
  if (band.minWidth === 0) continue;
  lines.push(`@media (min-width: ${band.minWidth}px) {`);
  lines.push(`  :root { --scale: ${band.scale}; }`);
  lines.push('}');
}
lines.push('');

const out = fileURLToPath(new URL('../src/styles/tokens.css', import.meta.url));
writeFileSync(out, lines.join('\n'));
console.log(`tokens: wrote ${out}`);
