import type { StringTable } from '../../i18n/types';

/** W-04 Method desk (prompt 0026). Object texts come from the bilingual playbook data through `pick()`. */
export const strings: StringTable = {
  'desk.nav.desk': { en: 'Method desk', es: 'Mesa del método' },
  'desk.title': { en: 'Method desk', es: 'Mesa del método' },
  'desk.subtitle': {
    en: '{items} objects on {mats} mats, one mat per phase of the client journey. Each one shows what it really holds: zoom in to read it.',
    es: '{items} objetos en {mats} tapetes, un tapete por fase del recorrido del cliente. Cada uno muestra lo que realmente contiene: acerca para leerlo.',
  },
  'desk.toolbar': { en: 'Desk view', es: 'Vista de la mesa' },
  'desk.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'desk.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'desk.zoomLabel': { en: 'Zoom', es: 'Zoom' },
  'desk.zoomNow': { en: '{pct} %', es: '{pct} %' },
  'desk.fit': { en: 'Fit', es: 'Ajustar' },
  'desk.tiltOn': { en: 'Tilted', es: 'Inclinada' },
  'desk.tiltOff': { en: 'Flat', es: 'Plana' },
  'desk.phase': { en: 'Phase', es: 'Fase' },
  'desk.goToPhase': { en: 'Go to a phase…', es: 'Ir a una fase…' },
  'desk.phaseOption': { en: '{name} · {n}', es: '{name} · {n}' },
  'desk.reset': { en: 'Reset', es: 'Restablecer' },
  'desk.hint': {
    en: 'Scroll or pinch to zoom, drag the desk to move it. Keyboard: + and − zoom, arrows move, F fits, 0 resets, Tab walks the mats and objects. Select any object to look closer.',
    es: 'Desplaza o pellizca para hacer zoom y arrastra la mesa para moverla. Teclado: + y − acercan y alejan, las flechas mueven, F ajusta, 0 restablece, Tab recorre los tapetes y los objetos. Selecciona cualquier objeto para verlo de cerca.',
  },
  'desk.stage': { en: 'The method desk', es: 'La mesa del método' },
  'desk.roledescription': { en: 'zoomable desk', es: 'mesa con zoom' },
  'desk.objects': { en: '{n} objects', es: '{n} objetos' },
  'desk.matLabel': { en: 'Phase {name}, {n} objects. Fit this mat', es: 'Fase {name}, {n} objetos. Ajustar este tapete' },
  'desk.more': { en: '+ {n} more', es: '+ {n} más' },

  'desk.kind.sheet': { en: 'Sheet', es: 'Hoja' },
  'desk.kind.form': { en: 'Form', es: 'Formulario' },
  'desk.kind.checklist': { en: 'Checklist', es: 'Lista de verificación' },
  'desk.kind.document': { en: 'Document', es: 'Documento' },
  'desk.kind.folder': { en: 'Folder', es: 'Carpeta' },
  'desk.kind.box': { en: 'Box', es: 'Caja' },
  'desk.kind.token': { en: 'Token', es: 'Ficha' },
  'desk.kind.card': { en: 'Card', es: 'Tarjeta' },

  'desk.group.services': { en: 'Services', es: 'Servicios' },
  'desk.group.statuses': { en: 'Statuses', es: 'Estados' },
  'desk.group.forms': { en: 'Forms', es: 'Formularios' },
  'desk.group.procedures': { en: 'Templates & procedures', es: 'Plantillas y procedimientos' },
  'desk.group.deliverables': { en: 'Deliverables', es: 'Entregables' },
  'desk.group.money': { en: 'Money', es: 'Dinero' },
  'desk.group.communication': { en: 'Communication', es: 'Comunicación' },
  'desk.group.rules': { en: 'Rules', es: 'Reglas' },
  'desk.group.team': { en: 'Team', es: 'Equipo' },
  'desk.group.measures': { en: 'Measures', es: 'Indicadores' },

  'desk.source.playbook': { en: 'Service playbook', es: 'Playbook de servicios' },
  'desk.source.template': { en: 'Project template', es: 'Plantilla de proyecto' },
  'desk.source.statusSet': { en: 'Status set', es: 'Conjunto de estados' },

  'desk.drawer.kind': { en: 'Kind', es: 'Tipo' },
  'desk.drawer.phase': { en: 'Phase', es: 'Fase' },
  'desk.drawer.group': { en: 'Sub-mat', es: 'Subtapete' },
  'desk.drawer.source': { en: 'Source', es: 'Fuente' },
  'desk.drawer.code': { en: 'Code', es: 'Código' },
  'desk.drawer.id': { en: 'Id', es: 'Id' },
  'desk.drawer.contents': { en: 'Contents ({n})', es: 'Contenido ({n})' },
  'desk.drawer.open': { en: 'Open', es: 'Abrir' },
  'desk.drawer.openWhat': { en: 'opening this object on its own page: {where}', es: 'abrir este objeto en su propia página: {where}' },
};
