import type { StringTable } from '../../i18n/types';

/** W-04 Method desk (prompt 0026). Object texts come from the bilingual playbook data through `pick()`. */
export const strings: StringTable = {
  'desk.nav.desk': { en: 'Method desk', es: 'Mesa del método' },
  'desk.title': { en: 'Method desk', es: 'Mesa del método' },
  'desk.subtitle': {
    en: '{items} objects and {people} people on {mats} mats, one mat and one owner per phase of the client journey. Each object shows what it really holds: zoom in to read it.',
    es: '{items} objetos y {people} personas en {mats} tapetes, un tapete y un responsable por fase del recorrido del cliente. Cada objeto muestra lo que realmente contiene: acerca para leerlo.',
  },
  'desk.phase': { en: 'Phase', es: 'Fase' },
  'desk.goToPhase': { en: 'Go to a phase…', es: 'Ir a una fase…' },
  'desk.hint': {
    en: 'Two-finger scroll or drag to move the desk; pinch, or ctrl + scroll, to zoom (Settings: make the mouse wheel zoom); double-click an object to zoom to it. Touch: drag with one finger, pinch with two, double-tap to zoom. Keyboard: + and − zoom, arrows move, F fits, 0 resets, Tab walks the mats and objects. Select any object to look closer. Follow a project to see its records as light; with the desk focused, Space plays its trail and [ and ] step through it.',
    es: 'Desplaza con dos dedos o arrastra para mover la mesa; pellizca, o ctrl + rueda, para acercar (Ajustes: que la rueda del ratón acerque); doble clic en un objeto lo acerca. Táctil: arrastra con un dedo, pellizca con dos, doble toque acerca. Teclado: + y − acercan y alejan, las flechas mueven, F ajusta, 0 restablece, Tab recorre los tapetes y los objetos. Selecciona cualquier objeto para verlo de cerca. Sigue un proyecto para ver sus registros como luz; con la mesa enfocada, Espacio reproduce su rastro y [ y ] avanzan o retroceden.',
  },
  'desk.stage': { en: 'The method desk', es: 'La mesa del método' },
  'desk.matLabel': { en: 'Phase {name}, {n} objects. Fit this mat', es: 'Fase {name}, {n} objetos. Ajustar este tapete' },


  'desk.group.services': { en: 'Services', es: 'Servicios' },
  'desk.group.statuses': { en: 'Statuses', es: 'Estados' },
  'desk.group.forms': { en: 'Forms', es: 'Formularios' },
  'desk.group.procedures': { en: 'Templates & procedures', es: 'Plantillas y procedimientos' },
  'desk.group.deliverables': { en: 'Deliverables', es: 'Entregables' },
  'desk.group.money': { en: 'Money', es: 'Dinero' },
  'desk.group.communication': { en: 'Communication', es: 'Comunicación' },
  'desk.group.rules': { en: 'Rules', es: 'Reglas' },
  'desk.group.team': { en: 'Team', es: 'Equipo' },
  'desk.group.measures': { en: 'Measures', es: 'Indicadores' },

  'desk.source.playbook': { en: 'Service playbook', es: 'Playbook de servicios' },
  'desk.source.template': { en: 'Project template', es: 'Plantilla de proyecto' },
  'desk.source.statusSet': { en: 'Status set', es: 'Conjunto de estados' },

  'desk.drawer.phase': { en: 'Phase', es: 'Fase' },
  'desk.drawer.group': { en: 'Sub-mat', es: 'Subtapete' },
  'desk.drawer.source': { en: 'Source', es: 'Fuente' },
  'desk.drawer.contents': { en: 'Contents ({n})', es: 'Contenido ({n})' },
  'desk.person.label': { en: 'Person: {role}{name}, owner of {phase}. Open', es: 'Persona: {role}{name}, responsable de {phase}. Abrir' },
  'desk.person.kicker': { en: 'Owner of {phase}', es: 'Responsable de {phase}' },
  'desk.person.role': { en: 'Playbook role', es: 'Rol del playbook' },
  'desk.person.portalRole': { en: 'Portal role', es: 'Rol del portal' },
  'desk.person.noPortalRole': { en: 'None yet', es: 'Aún ninguno' },
  'desk.person.person': { en: 'Demo person', es: 'Persona demo' },
  'desk.person.basis': { en: 'Basis', es: 'Base' },
  'desk.person.basis.template': { en: 'Project template (phase owner)', es: 'Plantilla de proyecto (responsable de la fase)' },
  'desk.person.basis.responsibility': { en: 'Role responsibilities (p. 17)', es: 'Responsabilidades del rol (p. 17)' },
  'desk.person.basis.closest': { en: 'Inferred: closest role, to confirm with the founder', es: 'Inferido: rol más cercano, por confirmar con la fundadora' },
  'desk.person.responsibilities': { en: 'Responsibilities', es: 'Responsabilidades' },
  'desk.person.why': { en: 'Why here', es: 'Por qué aquí' },
  'desk.person.phases': { en: 'Phases this role owns on the desk ({n})', es: 'Fases de este rol en la mesa ({n})' },
  'desk.person.inferred': { en: 'inferred', es: 'inferido' },
  'desk.person.openPortal': { en: 'Open portal', es: 'Abrir portal' },
  'desk.person.openPortalWhat': { en: 'Opens this portal: {where}', es: 'Abre este portal: {where}' },

  // The light layer (prompt 0028, D-105): one project followed across the desk.
  'desk.lightToolbar': { en: 'Follow a project as light', es: 'Seguir un proyecto como luz' },
  'desk.followLabel': { en: 'Project', es: 'Proyecto' },
  'desk.follow': { en: 'Follow a project…', es: 'Seguir un proyecto…' },
  'desk.followOption': { en: '{name} · {status}', es: '{name} · {status}' },
  'desk.clear': { en: 'Clear', es: 'Quitar' },
  'desk.play': { en: 'Play', es: 'Reproducir' },
  'desk.pause': { en: 'Pause', es: 'Pausar' },
  'desk.prev': { en: 'Previous event', es: 'Evento anterior' },
  'desk.next': { en: 'Next event', es: 'Evento siguiente' },
  'desk.trail.idle': { en: '{name}: lights on the desk {lights} · events in its trail {n}. Play to follow the light from mat to mat.', es: '{name}: luces en la mesa {lights} · eventos en su rastro {n}. Reproduce para seguir la luz de tapete en tapete.' },
  'desk.trail.step': { en: 'Event {i} of {n} · {date} · {phase}: {caption}', es: 'Evento {i} de {n} · {date} · {phase}: {caption}' },
  'desk.trail.empty': { en: 'No rows or events yet for {name}.', es: 'Aún no hay registros ni eventos de {name}.' },
  'desk.objectsLights': { en: '{n} objects · {l} lights', es: '{n} objetos · {l} luces' },
  'desk.group.project': { en: 'Project', es: 'Proyecto' },
  'desk.group.projectComms': { en: '{name} · messages', es: '{name} · mensajes' },
  'desk.source.project': { en: 'Followed project (live data)', es: 'Proyecto seguido (datos en vivo)' },
  'desk.light.label': { en: '{kind} of {project}: {title} ({facts}). Open', es: '{kind} de {project}: {title} ({facts}). Abrir' },
  'desk.drawer.project': { en: 'Project', es: 'Proyecto' },
  'desk.drawer.rule': { en: 'Why this mat', es: 'Por qué este tapete' },
  'desk.strip.label': { en: 'Money and communication of {name}', es: 'Dinero y comunicación de {name}' },
  'desk.strip.following': { en: 'Following', es: 'Siguiendo' },
  'desk.strip.status': { en: '{status} · {phase}', es: '{status} · {phase}' },
  'desk.money.quoted': { en: 'Quoted', es: 'Cotizado' },
  'desk.money.approved': { en: 'Approved', es: 'Aprobado' },
  'desk.money.paid': { en: 'Paid', es: 'Pagado' },
  'desk.money.outstanding': { en: 'Outstanding', es: 'Pendiente' },
  'desk.money.quotedSub': { en: 'quotes {n} · comparisons {g}', es: 'cotizaciones {n} · comparaciones {g}' },
  'desk.money.approvedSub': { en: 'purchases {p} + change orders {c}', es: 'compras {p} + órdenes de cambio {c}' },
  'desk.money.split': { en: 'in {in} · out {out}', es: 'entra {in} · sale {out}' },
  'desk.comms.title': { en: 'Communication', es: 'Comunicación' },
  'desk.comms.messages': { en: '{n} messages', es: '{n} mensajes' },
  'desk.comms.messages.one': { en: '1 message', es: '1 mensaje' },
  'desk.comms.sub': { en: 'project channel: client {c} · team {t} · meetings {m}', es: 'canal del proyecto: cliente {c} · equipo {t} · reuniones {m}' },
  'desk.comms.lead': { en: ' · lead via {ch}', es: ' · lead por {ch}' },
};
