import type { ActionDef } from '../specs/PageSpec';
import { deskStrings } from './strings';

/**
 * Spanish names of the page actions a desk object offers as abilities (changelog 0038, QA 0008 D1). The specs' own
 * `label` is the English name and the WebMCP / voice vocabulary, so it stays as it is; this table is how the drawer
 * says it in Spanish. An action with no row here falls back to its spec label (the build keeps working when a module
 * adds an action; the QA pass lists what is missing).
 */
const ES: Record<string, string> = {
  'archive.openProject': 'Abrir un proyecto',
  'archive.toggleInSet': 'Añadir o quitar del set de portafolio',
  'archive.setProjectTags': 'Etiquetar el proyecto',
  'archive.openFile': 'Ver un archivo',
  'archive.openSource': 'Abrir un archivo en su origen',
  'archive.downloadFile': 'Descargar un archivo',
  'archive.copyFileLink': 'Copiar el enlace de un archivo',
  'archive.tagFile': 'Etiquetar un archivo',
  'archive.setStage': 'Mover un archivo a una etapa',
  'archive.setCover': 'Poner la portada del proyecto',
  'brand.openPresentation': 'Abrir la presentación',
  'brand.advancePresentation': 'Avanzar la presentación',
  'brand.requestPresentation': 'Solicitar una presentación',
  'brand.openDeck': 'Abrir el archivo de la presentación',
  'brand.supersedeAsset': 'Marcar la pieza como reemplazada',
  'brand.restoreAsset': 'Marcar la pieza como vigente',
  'brand.uploadAsset': 'Subir una nueva versión',
  'brand.openImageSet': 'Abrir el set de imágenes',
  'brand.advanceImageSet': 'Avanzar el set de imágenes',
  'brand.shareImages': 'Compartir con el cliente',
  'brand.previewImages': 'Ver las imágenes',
  'brand.newImageSet': 'Nuevo set de imágenes',
  'brand.moveRevision': 'Mover la revisión',
  'brand.openRevision': 'Abrir la revisión',
  'brand.requestRevision': 'Solicitar una revisión',
  'founder.approveProject': 'Aprobar el proyecto',
  'founder.requestChanges': 'Pedir cambios',
  'founder.commentApproval': 'Comentar una aprobación',
  'founder.openCheck': 'Abrir la revisión de coherencia',
  'founder.movePipelineStatus': 'Mover a un estado del pipeline',
  'founder.moveProject': 'Mover el proyecto a una fase',
  'founder.openProject': 'Abrir el proyecto',
  'founder.setCreativeDirection': 'Definir la dirección creativa',
  'founder.openLead': 'Abrir el lead',
  'founder.qualifyLead': 'Registrar la calificación',
  'founder.suggestService': 'Sugerir un servicio',
  'founder.setLeadService': 'Definir el servicio solicitado',
  'founder.assignLeadOwner': 'Asignar el responsable',
  'founder.advanceLead': 'Avanzar el lead',
  'founder.convertLead': 'Convertir en proyecto',
  'founder.finaliseDocument': 'Marcar el documento como final',
  'founder.sendDocument': 'Enviar el documento al cliente',
  'founder.signOffPresentation': 'Aprobar la presentación',
  'founder.shortlistQuote': 'Preseleccionar la cotización del proveedor',
  'founder.newClientQuote': 'Nueva cotización al cliente',
  'founder.approveMaterial': 'Aprobar el material',
  'founder.completeTask': 'Marcar mi tarea como hecha',
  'founder.confirmProject': 'Confirmar los datos inferidos',
  'founder.setProjectType': 'Definir el tipo de proyecto',
  'founder.setProjectStatus': 'Definir el estado del proyecto',
  'founder.setProjectClient': 'Definir el cliente',
  'founder.setProjectYear': 'Definir el año',
  'founder.markDuplicate': 'Marcar como duplicado',
  'ops.acknowledgeAlert': 'Enterado de la alerta',
  'ops.confirmDelivery': 'Confirmar la entrega',
  'ops.moveTask': 'Mover la tarea',
  'ops.completeTask': 'Marcar la tarea como hecha',
  'ops.viewTask': 'Abrir la tarea',
  'ops.resolveAlert': 'Resolver la alerta',
  'ops.reopenAlert': 'Reabrir la alerta',
  'ops.openAlertSubject': 'Abrir el elemento',
  'ops.viewSupplier': 'Abrir el proveedor',
  'ops.setSupplierStatus': 'Pausar o activar el proveedor',
  'ops.logFollowUp': 'Guardar nota de seguimiento',
  'ops.selectQuote': 'Seleccionar la cotización',
  'ops.shortlistQuote': 'Preseleccionar la cotización',
  'ops.viewQuote': 'Abrir la cotización',
  'ops.requestQuote': 'Solicitar cotización',
  'ops.receiveDelivery': 'Marcar como recibida',
  'ops.delayDelivery': 'Marcar como retrasada',
  'ops.newChangeOrder': 'Nueva orden de cambio',
  'ops.approveChangeOrder': 'Aprobar la orden de cambio',
  'ops.rejectChangeOrder': 'Rechazar la orden de cambio',
  'ops.executeChangeOrder': 'Marcar la orden de cambio como ejecutada',
  'ops.filterChangeOrdersProject': 'Filtrar por proyecto',
  'ops.newPurchase': 'Nueva compra',
  'ops.advancePurchase': 'Avanzar la compra',
  'ops.setPurchaseStatus': 'Definir el estado de la compra',
  'ops.filterPurchases': 'Filtrar compras',
  'ops.newSiteReport': 'Nuevo informe de obra',
  'ops.openSiteReport': 'Abrir el informe de obra',
  'ops.filterSiteReportsProject': 'Filtrar por proyecto',
  'ops.markPaid': 'Marcar como pagado',
  'ops.registerPayment': 'Registrar un pago parcial',
  'ops.viewPayment': 'Abrir el pago',
  'ops.setDocumentStatus': 'Avanzar el estado',
  'ops.viewDocument': 'Abrir el documento',
  'ops.openDocumentFile': 'Abrir el archivo',
  'ops.uploadDocument': 'Subir documento',
  'spaces.selectSpace': 'Abrir el espacio',
  'spaces.toggleNode': 'Expandir o contraer',
  'spaces.createSpace': 'Nuevo espacio',
  'spaces.createPost': 'Nueva publicación',
  'spaces.editDescription': 'Editar la descripción',
  'spaces.archive': 'Archivar el espacio',
  'spaces.openPost': 'Abrir la publicación',
  'spaces.openTemplate': 'Abrir la plantilla',
  'spaces.openProject': 'Abrir el trabajo del proyecto',
  'spaces.previewAsset': 'Ver el archivo',
  'spaces.openAssetSource': 'Abrir un archivo en su origen',
  'spaces.editPost': 'Editar la publicación',
  'spaces.savePost': 'Guardar la publicación',
  'spaces.pin': 'Fijar o soltar',
  'spaces.setStatus': 'Publicar / archivar la publicación',
  'spaces.fileIn': 'Archivar en un espacio',
  'spaces.unfile': 'Quitar del espacio',
  'spaces.setTags': 'Editar etiquetas',
  'spaces.relate': 'Añadir relación',
  'spaces.comment': 'Comentar',
  'spaces.openLink': 'Abrir el enlace',
  'studio.openProject': 'Abrir el proyecto',
  'studio.newProposal': 'Nueva propuesta de diseño',
  'studio.openCheck': 'Abrir la revisión de coherencia',
  'studio.askReschedule': 'Pedir a operaciones que reprogramen',
  'studio.openProjectDetail': 'Abrir el detalle del proyecto',
  'studio.sendToCheck': 'Enviar a revisión de coherencia',
  'studio.requestDirection': 'Pedir dirección creativa',
  'studio.newProposalDoc': 'Nueva propuesta',
  'studio.toggleCheckItem': 'Marcar un punto de la revisión',
  'studio.passCheck': 'Marcar como aprobada',
  'studio.reportCheckIssues': 'Reportar problemas',
  'studio.saveCheckNotes': 'Guardar notas',
  'studio.newCheck': 'Nueva revisión',
  'studio.addCheckItem': 'Añadir punto de revisión',
  'studio.reviewSchedule': 'Enviar a revisión',
  'studio.finaliseSchedule': 'Marcar como final',
  'studio.openSchedule': 'Abrir el cuadro',
  'studio.openScheduleItems': 'Abrir la lista de ítems',
  'studio.newSchedule': 'Nuevo cuadro',
  'studio.openReference': 'Abrir la referencia',
  'studio.moveReference': 'Mover a un tablero',
  'studio.uploadReferenceImage': 'Subir imagen',
  'studio.newBoard': 'Nuevo tablero de inspiración',
  'studio.sampleMaterial': 'Pedir muestra',
  'studio.approveMaterial': 'Aprobar el material',
  'studio.rejectMaterial': 'Rechazar el material',
  'studio.openMaterial': 'Abrir el material',
  'studio.newPalette': 'Nueva paleta',
  'studio.newPlanVersion': 'Nueva versión',
  'studio.finalisePlan': 'Marcar como final',
  'studio.openPlan': 'Abrir el documento',
  'studio.uploadDrawing': 'Subir plano',
  'studio.newPack': 'Nuevo paquete',
  'studio.openMeasurementSheet': 'Abrir la hoja de medidas',
  'studio.captureDimensions': 'Medidas por espacio',
  'studio.addRequirement': 'Requisitos por espacio',
  'studio.attachSitePhoto': 'Fotos de obra y anotaciones',
  'studio.selectChecklistProject': 'Elegir proyecto',
  'studio.sendToProcurement': 'Enviar a compras',
  'studio.editRevisionItem': 'Guardar comentario',
  'studio.selectRevisionProject': 'Elegir proyecto',
  'studio.sendMatrixToClient': 'Enviar al cliente',
  'work.addTask': 'Añadir tarea',
  'work.openTask': 'Abrir la tarea',
  'work.editTitle': 'Renombrar la tarea',
  'work.assign': 'Asignar la tarea',
  'work.setDates': 'Definir fechas',
  'work.setStatus': 'Definir el estado',
  'work.setPriority': 'Definir la prioridad',
  'work.complete': 'Marcar como completa',
  'work.moveTask': 'Mover la tarea',
  'work.setTags': 'Definir etiquetas',
  'work.setDescription': 'Editar la descripción',
  'work.addDependency': 'Añadir dependencia',
  'work.removeDependency': 'Quitar dependencia',
  'work.addSubtask': 'Añadir subtarea',
  'work.toggleSubtask': 'Marcar subtarea',
  'work.comment': 'Comentar',
  'work.setDeliverable': 'Definir el entregable',
  'work.toggleSubtree': 'Contraer o expandir una tarea',
  'work.openProject': 'Abrir el trabajo del proyecto',
  'work.selectClient': 'Elegir el cliente',
  // The lead dossier's abilities (D-108) are desk actions and carry their own strings.
};

/**
 * The ability's name in the page language: a `desk.ability.<actionId>` string when the desk defines one (the desk's
 * own actions, D-108), else this table's Spanish row, else the spec's label.
 */
export function abilityLabel(action: Pick<ActionDef, 'id' | 'label'>, lang: 'en' | 'es'): string {
  const own = deskStrings[`desk.ability.${action.id}`];
  if (own) return typeof own === 'string' ? own : lang === 'es' ? own.es ?? own.en : own.en;
  return lang === 'es' ? ES[action.id] ?? action.label : action.label;
}

/** Action ids that have a Spanish name (the QA pass checks every ability against it). */
export const ABILITY_ES_IDS: ReadonlySet<string> = new Set(Object.keys(ES));
