import type { StringTable } from '../i18n/types';

/**
 * The desk system's own strings (D-106): toolbar, legend, sizes, fullscreen, abilities, page desks, object kinds and
 * the values the page desks group by that the StatusPill vocabulary (`core.status.*`) does not name. Merged by the
 * registry next to `core.*`; W-04's playbook, people and light-layer strings stay in `modules/desk/strings.ts`.
 */
export const deskStrings: StringTable = {
  'desk.toolbar': { en: 'Desk view', es: 'Vista de la mesa' },
  'desk.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'desk.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'desk.zoomLabel': { en: 'Zoom', es: 'Zoom' },
  'desk.zoomNow': { en: '{pct} %', es: '{pct} %' },
  'desk.fit': { en: 'Fit', es: 'Ajustar' },
  'desk.tiltOn': { en: 'Tilted', es: 'Inclinada' },
  'desk.tiltOff': { en: 'Flat', es: 'Plana' },
  'desk.phaseOption': { en: '{name} · {n}', es: '{name} · {n}' },
  'desk.reset': { en: 'Reset', es: 'Restablecer' },
  'desk.roledescription': { en: 'zoomable desk', es: 'mesa con zoom' },
  'desk.objects': { en: '{n} objects', es: '{n} objetos' },
  'desk.more': { en: '+ {n} more', es: '+ {n} más' },
  'desk.kind.sheet': { en: 'Sheet', es: 'Hoja' },
  'desk.kind.form': { en: 'Form', es: 'Formulario' },
  'desk.kind.checklist': { en: 'Checklist', es: 'Lista de verificación' },
  'desk.kind.document': { en: 'Document', es: 'Documento' },
  'desk.kind.folder': { en: 'Folder', es: 'Carpeta' },
  'desk.kind.box': { en: 'Box', es: 'Caja' },
  'desk.kind.token': { en: 'Token', es: 'Ficha' },
  'desk.kind.card': { en: 'Card', es: 'Tarjeta' },
  'desk.kind.phone': { en: 'Phone', es: 'Teléfono' },
  'desk.kind.tablet': { en: 'Tablet', es: 'Tableta' },
  'desk.kind.screen': { en: 'Screen', es: 'Pantalla' },
  'desk.kind.page': { en: 'Web page', es: 'Página web' },
  'desk.kind.pages': { en: 'Stack of web pages', es: 'Pila de páginas web' },
  'desk.drawer.kind': { en: 'Kind', es: 'Tipo' },
  'desk.drawer.code': { en: 'Code', es: 'Código' },
  'desk.drawer.id': { en: 'Id', es: 'Id' },
  'desk.drawer.open': { en: 'Open', es: 'Abrir' },
  'desk.drawer.openWhat': { en: 'Opens the page that manages this: {where}', es: 'Abre la página que lo gestiona: {where}' },
  'desk.enterAs': { en: 'Opening {code} as {role}', es: 'Abriendo {code} como {role}' },
  'desk.kind.light': { en: 'Light', es: 'Luz' },
  'desk.drawer.entity': { en: 'Kind of record', es: 'Tipo de registro' },
  'desk.drawer.page': { en: 'Managed on', es: 'Se gestiona en' },
  'desk.drawer.fields': { en: 'Fields ({n})', es: 'Campos ({n})' },
  'desk.drawer.gone': { en: 'This record is no longer there (removed in another tab).', es: 'Este registro ya no está (se eliminó en otra pestaña).' },  'desk.kind.stack': { en: 'Stack', es: 'Pila' },

  // Toolbar, sizes, fullscreen, settings (D-106).
  'desk.goToMat': { en: 'Go to a mat…', es: 'Ir a un tapete…' },
  'desk.matSelect': { en: 'Mat', es: 'Tapete' },
  'desk.matLabel.generic': { en: '{name}, {n} objects. Fit this mat', es: '{name}, {n} objetos. Ajustar este tapete' },
  'desk.subLabel.aria': { en: '{name}: {n} objects. Fit this sub-mat', es: '{name}: {n} objetos. Ajustar este subtapete' },
  'desk.fullscreen': { en: 'Full screen', es: 'Pantalla completa' },
  'desk.fullscreenExit': { en: 'Exit full screen', es: 'Salir de pantalla completa' },
  'desk.size': { en: 'Size', es: 'Tamaño' },
  'desk.size.s': { en: 'S', es: 'P' },
  'desk.size.m': { en: 'M', es: 'M' },
  'desk.size.l': { en: 'L', es: 'G' },
  'desk.size.sLabel': { en: 'Small desk (40 % of the screen height)', es: 'Mesa pequeña (40 % de la altura de la pantalla)' },
  'desk.size.mLabel': { en: 'Medium desk (60 % of the screen height)', es: 'Mesa mediana (60 % de la altura de la pantalla)' },
  'desk.size.lLabel': { en: 'Large desk (85 % of the screen height)', es: 'Mesa grande (85 % de la altura de la pantalla)' },
  'desk.height': { en: 'Desk height', es: 'Altura de la mesa' },
  'desk.heightValue': { en: '{vh} % of the screen height', es: '{vh} % de la altura de la pantalla' },
  'desk.heightHint': { en: 'Drag, or use the up and down arrows, to change the desk’s height', es: 'Arrastra, o usa las flechas arriba y abajo, para cambiar la altura de la mesa' },
  'desk.settings': { en: 'Settings', es: 'Ajustes' },
  'desk.settingsTitle': { en: 'Desk settings', es: 'Ajustes de la mesa' },
  'desk.wheelZoom': { en: 'Scroll wheel zooms', es: 'La rueda del ratón acerca' },
  'desk.wheelZoomHint': { en: 'Off (best for trackpads): scrolling moves the desk; pinch or ctrl + scroll zooms. On (best for a mouse): the wheel zooms, shift + wheel moves.', es: 'Apagado (mejor con trackpad): desplazar mueve la mesa; pellizcar o ctrl + rueda acerca. Encendido (mejor con ratón): la rueda acerca, mayúsculas + rueda mueve.' },
  'desk.close': { en: 'Close', es: 'Cerrar' },
  'desk.minimap': { en: 'Minimap', es: 'Minimapa' },
  'desk.hint.engine': {
    en: 'Two-finger scroll or drag to move the desk; pinch, or ctrl + scroll, to zoom; double-click to zoom in. Touch: drag with one finger, pinch with two, double-tap to zoom. Keyboard: + and − zoom, arrows move, F fits, 0 resets, Tab walks the mats, sub-mats and objects, Enter opens, Esc closes.',
    es: 'Desplaza con dos dedos o arrastra para mover la mesa; pellizca, o ctrl + rueda, para acercar; doble clic acerca. Táctil: arrastra con un dedo, pellizca con dos, doble toque acerca. Teclado: + y − acercan y alejan, las flechas mueven, F ajusta, 0 restablece, Tab recorre tapetes, subtapetes y objetos, Enter abre, Esc cierra.',
  },
  'desk.hint.page': { en: 'Scroll or drag to move · pinch or ctrl + scroll to zoom · double-click to zoom in · select an object for its fields and abilities · Legend explains the objects. The page continues below.', es: 'Desplaza o arrastra para mover · pellizca o ctrl + rueda para acercar · doble clic acerca · selecciona un objeto para ver sus campos y habilidades · Leyenda explica los objetos. La página sigue abajo.' },
  'desk.legend.inputs': { en: 'Moving around', es: 'Cómo moverse' },
  'desk.tip': { en: '{kind} · {entity}', es: '{kind} · {entity}' },

  // Legend.
  'desk.legend': { en: 'Legend', es: 'Leyenda' },
  'desk.legendTitle': { en: 'What is on this desk', es: 'Qué hay en esta mesa' },
  'desk.legend.kinds': { en: 'Objects ({n} kinds)', es: 'Objetos ({n} tipos)' },
  'desk.legend.layout': { en: 'Mats and sub-mats', es: 'Tapetes y subtapetes' },
  'desk.legend.mats': { en: 'Each mat is one kind of record; select a mat or a sub-mat label to fit it. {grouping}.', es: 'Cada tapete es un tipo de registro; selecciona el rótulo de un tapete o subtapete para ajustarlo. {grouping}.' },
  'desk.legend.open': { en: 'Select an object to see its fields and what you can do with it (its abilities).', es: 'Selecciona un objeto para ver sus campos y lo que puedes hacer con él (sus habilidades).' },
  'desk.help.sheet': { en: 'A single page: a record with an amount or a few fields (a quote, a payment, a purchase, a message).', es: 'Una hoja: un registro con un monto o pocos campos (una cotización, un pago, una compra, un mensaje).' },
  'desk.help.form': { en: 'A form: field labels with blanks to fill.', es: 'Un formulario: etiquetas de campo con espacios por llenar.' },
  'desk.help.checklist': { en: 'A checklist: work to tick off (tasks, checks).', es: 'Una lista de verificación: trabajo por marcar (tareas, revisiones).' },
  'desk.help.document': { en: 'A document with pages: a file, a post, a deliverable, a deck.', es: 'Un documento con páginas: un archivo, una publicación, un entregable, una presentación.' },
  'desk.help.folder': { en: 'A folder holding other things: a project, a space, a service, a pack.', es: 'Una carpeta que guarda otras cosas: un proyecto, un espacio, un servicio, un paquete.' },
  'desk.help.box': { en: 'A box: goods on their way, a delivery kit.', es: 'Una caja: mercancía en camino, un kit de entrega.' },
  'desk.help.token': { en: 'A token: a status or a tag, its colour is its tone.', es: 'Una ficha: un estado o una etiqueta; su color es su tono.' },
  'desk.help.card': { en: 'A card: a person, a company, a rule, a meeting, a sample.', es: 'Una tarjeta: una persona, una empresa, una regla, una reunión, una muestra.' },
  'desk.help.light': { en: 'Light: a live record of the followed project.', es: 'Luz: un registro en vivo del proyecto seguido.' },
  'desk.help.phone': { en: 'A phone: one app screen (390 × 844); its face is a capture of the real screen.', es: 'Un teléfono: una pantalla de la app (390 × 844); su cara es una captura de la pantalla real.' },
  'desk.help.tablet': { en: 'A tablet: one screen at 768 × 1024.', es: 'Una tableta: una pantalla a 768 × 1024.' },
  'desk.help.screen': { en: 'A screen on a stand: one desktop page (1280 × 800), a dashboard or a tool.', es: 'Una pantalla sobre su base: una página de escritorio (1280 × 800), un panel o una herramienta.' },
  'desk.help.page': { en: 'A tall web page: one page of a website, full length, its header at the top.', es: 'Una página web alta: una página de un sitio, a lo largo, con su encabezado arriba.' },
  'desk.help.pages': { en: 'A fanned stack of web pages: a whole website at a glance; the badge counts its pages.', es: 'Una pila abierta de páginas web: todo un sitio de un vistazo; la insignia cuenta sus páginas.' },
  'desk.help.stack': { en: 'A stack: the rows this sub-mat does not show; open it to go to the page.', es: 'Una pila: las filas que este subtapete no muestra; ábrela para ir a la página.' },
  'desk.grouped.status': { en: 'Sub-mats are grouped by status', es: 'Los subtapetes están agrupados por estado' },
  'desk.grouped.field': { en: 'Sub-mats are grouped by {field}', es: 'Los subtapetes están agrupados por {field}' },
  'desk.grouped.mixed': { en: 'Sub-mats are grouped by {fields}', es: 'Los subtapetes están agrupados por {fields}' },
  'desk.grouped.none': { en: 'one sub-mat per mat', es: 'un subtapete por tapete' },
  'desk.grouped.all': { en: 'All', es: 'Todos' },

  // Page desks (the shell's desk above every portal page).
  'desk.page.title': { en: 'Desk', es: 'Mesa' },
  'desk.page.summary': { en: '{objects} objects on {mats} mats · {grouping}', es: '{objects} objetos en {mats} tapetes · {grouping}' },
  'desk.page.empty': { en: 'Nothing to lay out yet: this page’s tables have no rows.', es: 'Nada que mostrar todavía: las tablas de esta página no tienen filas.' },
  'desk.page.loading': { en: 'Laying out the desk…', es: 'Preparando la mesa…' },
  'desk.page.stage': { en: 'Desk of {page}', es: 'Mesa de {page}' },
  'desk.page.below': { en: 'The page continues below the desk.', es: 'La página sigue debajo de la mesa.' },
  'desk.show': { en: 'Show desk', es: 'Mostrar mesa' },
  'desk.hide': { en: 'Hide desk', es: 'Ocultar mesa' },
  'desk.compact': { en: 'Desk · {objects} objects on {mats} mats', es: 'Mesa · {objects} objetos en {mats} tapetes' },
  'desk.stack.title': { en: 'more {entity}', es: '{entity} más' },
  'desk.object.label': { en: '{kind}: {title} ({entity}{status}). Open', es: '{kind}: {title} ({entity}{status}). Abrir' },
  'desk.drawer.mat': { en: 'Mat', es: 'Tapete' },
  'desk.drawer.sub': { en: 'Sub-mat', es: 'Subtapete' },
  'desk.drawer.pageOpen': { en: 'Opens {where}', es: 'Abre {where}' },
  'desk.drawer.showBelow': { en: 'Show on the page', es: 'Ver en la página' },
  'desk.drawer.showBelowWhat': { en: 'Closes the drawer and scrolls to the page under the desk', es: 'Cierra el panel y baja a la página debajo de la mesa' },
  'desk.abilities': { en: 'Abilities', es: 'Habilidades' },
  'desk.abilities.intro': { en: 'What this page can do with this {entity}. Each button runs the page’s own action.', es: 'Lo que esta página puede hacer con este {entity}. Cada botón ejecuta la acción de la página.' },
  'desk.abilities.none': { en: 'This page declares no action for {entity} yet: use Open.', es: 'Esta página aún no declara acciones para {entity}: usa Abrir.' },
  'desk.abilities.denied': { en: 'Needs the permission {permission}', es: 'Requiere el permiso {permission}' },
  'desk.abilities.done': { en: '{label}: {result}', es: '{label}: {result}' },
  'desk.abilities.failed': { en: '{label} did not run: {error}', es: '{label} no se ejecutó: {error}' },
  'desk.abilities.needs': { en: 'Needs {fields}: use the page below', es: 'Requiere {fields}: usa la página de abajo' },
  'desk.abilities.ok': { en: 'done', es: 'hecho' },

  // Values the page desks group by that core.status does not name (kinds, severities, priorities).
  'desk.value.client': { en: 'Client', es: 'Cliente' },
  'desk.value.supplier': { en: 'Supplier', es: 'Proveedor' },
  'desk.value.internal': { en: 'Internal', es: 'Interna' },
  'desk.value.site-visit': { en: 'Site visit', es: 'Visita de obra' },
  'desk.value.strategic': { en: 'Strategic', es: 'Estratégica' },
  'desk.value.area': { en: 'Area', es: 'Área' },
  'desk.value.topic': { en: 'Topic', es: 'Tema' },
  'desk.value.role': { en: 'Role', es: 'Rol' },
  'desk.value.deliverable': { en: 'Deliverable', es: 'Entregable' },
  'desk.value.tool': { en: 'Tool', es: 'Herramienta' },
  'desk.value.project': { en: 'Project', es: 'Proyecto' },
  'desk.value.archive': { en: 'Archive', es: 'Archivo' },
  'desk.value.note': { en: 'Note', es: 'Nota' },
  'desk.value.link': { en: 'Link', es: 'Enlace' },
  'desk.value.file': { en: 'File', es: 'Archivo' },
  'desk.value.decision': { en: 'Decision', es: 'Decisión' },
  'desk.value.procedure': { en: 'Procedure', es: 'Procedimiento' },
  'desk.value.brief': { en: 'Brief', es: 'Brief' },
  'desk.value.announcement': { en: 'Announcement', es: 'Anuncio' },
  'desk.value.document': { en: 'Document', es: 'Documento' },
  'desk.value.page': { en: 'Page', es: 'Página' },
  'desk.value.image': { en: 'Image', es: 'Imagen' },
  'desk.value.logo': { en: 'Logo', es: 'Logo' },
  'desk.value.texture': { en: 'Texture', es: 'Textura' },
  'desk.value.contract': { en: 'Contract', es: 'Contrato' },
  'desk.value.invoice': { en: 'Invoice', es: 'Factura' },
  'desk.value.plan': { en: 'Plan', es: 'Plano' },
  'desk.value.project-pdf': { en: 'Project PDF', es: 'PDF del proyecto' },
  'desk.value.report': { en: 'Report', es: 'Informe' },
  'desk.value.spec': { en: 'Specification', es: 'Especificación' },
  'desk.value.quote': { en: 'Quote', es: 'Cotización' },
  'desk.value.sales': { en: 'Sales', es: 'Ventas' },
  'desk.value.proposal': { en: 'Proposal', es: 'Propuesta' },
  'desk.value.competition': { en: 'Competition', es: 'Concurso' },
  'desk.value.layout': { en: 'Layout', es: 'Diagramación' },
  'desk.value.pdf': { en: 'PDF', es: 'PDF' },
  'desk.value.presentation': { en: 'Presentation', es: 'Presentación' },
  'desk.value.social': { en: 'Social', es: 'Redes' },
  'desk.value.typography': { en: 'Typography', es: 'Tipografía' },
  'desk.value.palette': { en: 'Palette', es: 'Paleta' },
  'desk.value.template': { en: 'Template', es: 'Plantilla' },
  'desk.value.photo': { en: 'Photo', es: 'Foto' },
  'desk.value.icon': { en: 'Icon', es: 'Ícono' },
  'desk.value.guideline': { en: 'Guideline', es: 'Lineamiento' },
  'desk.value.info': { en: 'Info', es: 'Información' },
  'desk.value.warning': { en: 'Warning', es: 'Advertencia' },
  'desk.value.urgent': { en: 'Urgent', es: 'Urgente' },
  'desk.value.low': { en: 'Low', es: 'Baja' },
  'desk.value.normal': { en: 'Normal', es: 'Normal' },
  'desk.value.high': { en: 'High', es: 'Alta' },
  'desk.value.acknowledged': { en: 'Acknowledged', es: 'Vista' },
  'desk.value.resolved': { en: 'Resolved', es: 'Resuelta' },
  'desk.value.render-artist': { en: 'Render artist', es: 'Renderista' },
  'desk.value.residential': { en: 'Residential', es: 'Residencial' },
  'desk.value.commercial': { en: 'Commercial', es: 'Comercial' },
  'desk.value.hospitality': { en: 'Hospitality', es: 'Hotelería' },
  'desk.value.wellness': { en: 'Wellness', es: 'Bienestar' },
  'desk.value.lighting-product': { en: 'Lighting product', es: 'Producto de iluminación' },
  'desk.value.furniture': { en: 'Furniture', es: 'Mobiliario' },
  'desk.value.materials': { en: 'Materials', es: 'Materiales' },
  'desk.value.lighting': { en: 'Lighting', es: 'Iluminación' },
  'desk.value.elements': { en: 'Elements', es: 'Elementos' },
  'desk.value.none': { en: 'Not set', es: 'Sin valor' },
};
