import { defineSpec } from '../../specs/PageSpec';

export const planSpec = defineSpec({
  code: 'D-05',
  name: 'Plan viewer',
  purpose: 'The PM viewer the workspace policy asks for: every plan task as a board, a list and a dependency timeline, read from docs/plan/plan.json (D-037) so the plan in the product can never disagree with the plan in the repo.',
  surface: 'dev',
  navGroup: 'developer',
  layout: [
    'PageHeader (code, title, subtitle with the task count and the plan version)',
    'StatTiles: done / doing / next / backlog from planCounts()',
    'FilterBar: SearchField (id, title, code, model), status Select, model Select, step Select, summary, Clear',
    'Tabs: Board / List / Timeline',
    'Board: Kanban with backlog / next / doing / done; each card shows the title, its step, model badge, page codes and blocker count; a Placeholder button stands in for moving a card',
    'List: DataTable (id, task, step, status pill, model, codes, depends-on count, changelog), sortable, rows open the drawer',
    'Timeline: dependency swimlane, one lane per build-plan step, a task in the column of its dependency depth, SVG arrows between dependencies, arrow keys move between tasks',
    'Drawer: the full task, blockers and dependents as links, and the repo files that carry it',
  ],
  dataTables: [],
  roles: ['dev', 'founder'],
  logic: [
    'Reads PLAN, planOrder, planDepth, planBlockers, planDependents and planCounts from src/plan (docs/plan/plan.json through the @docs alias); nothing is written.',
    'Search matches id, title, step, model and page codes; the status, model and step Selects narrow further and the summary counts shown of total.',
    'The timeline lays tasks out by planOrder inside a lane per step and by planDepth across the columns; dependency arrows are drawn as an SVG overlay measured with a ResizeObserver and are decoration only — every dependency is also written as text, and the overlay is dropped under 768 px.',
    'Arrow keys, Home and End move focus between the timeline bars; Enter or Space opens the drawer, which also opens from a board card or a list row.',
    'Moving a card is a Placeholder: the plan is edited in docs/plan/plan.json in the repo (D-037), so tools.movePlanTask answers with where the edit belongs instead of changing anything.',
  ],
  components: ['PageHeader', 'StatTile', 'FilterBar', 'SearchField', 'Select', 'Tabs', 'Kanban', 'DataTable', 'StatusPill', 'Badge', 'Drawer', 'KeyValue', 'Button', 'Placeholder', 'EmptyState'],
  actions: [
    { id: 'tools.switchPlanView', label: 'Switch plan view', intent: 'show the plan as a {view}', permission: 'dev.tools', params: { view: 'enum:board|list|timeline' } },
    { id: 'tools.searchPlan', label: 'Search the plan', intent: 'find the plan task {query}', permission: 'dev.tools', params: { query: 'string' } },
    { id: 'tools.filterPlanStatus', label: 'Filter the plan by status', intent: 'show only {status} tasks', permission: 'dev.tools', params: { status: 'enum:all|done|doing|next|backlog' } },
    { id: 'tools.filterPlanModel', label: 'Filter the plan by model', intent: 'show only the tasks of model {model}', permission: 'dev.tools', params: { model: 'string' } },
    { id: 'tools.filterPlanStep', label: 'Filter the plan by step', intent: 'show only the tasks of step {step}', permission: 'dev.tools', params: { step: 'string' } },
    { id: 'tools.openPlanTask', label: 'Open a plan task', intent: 'open the plan task {task}', permission: 'dev.tools', params: { task: 'id' } },
    { id: 'tools.movePlanTask', label: 'Move a plan task', intent: 'move the plan task {task} to {status}', permission: 'dev.tools', params: { task: 'id', status: 'enum:done|doing|next|backlog' } },
  ],
  checkedAt: [360, 390, 768, 1280, 1920],
});

export const canvasSpec = defineSpec({
  code: 'D-07',
  name: 'Canvas',
  purpose: 'Every registered page of the hub laid out as a zoomable card grid grouped by surface, with the deploy-time thumbnail, code, status, shell and permission, so the whole system is visible at once and any page opens as a demo user of its surface.',
  surface: 'dev',
  navGroup: 'developer',
  layout: [
    'PageHeader (code, title, subtitle)',
    'StatTiles: pages, built, stubs, surfaces',
    'FilterBar: SearchField (code, name, path), surface Select, status Select, summary, Clear',
    'Zoom toolbar: minus / plus / fit Buttons and a preset Select (25 / 50 / 75 / 100 / 150 / 200 %)',
    'Scrolling canvas stage: one section per surface, each a grid of SurfaceCards (thumbnail, code, status, name, path / shell / permission)',
    'EmptyState when nothing matches',
  ],
  dataTables: [],
  roles: ['dev', 'founder'],
  logic: [
    'Reads the registered routes from RoutesContext and groups them by surface in the SURFACES order; a card is Built or Stub straight from route.status, so it can never disagree with the manifest.',
    'The thumbnail is ./thumbs/<code>.jpg?v=<build id> (the deploy-time captures, D-011); SurfaceCard falls back to its bilingual "no preview yet" tile when the file is missing.',
    'Zoom is a --canvas-zoom custom property: the grid is transform: scale()d from the top left and its CSS width is 100% / zoom, so the stage never scrolls sideways and the columns reflow instead. Buttons step through the presets, the Select jumps to one, Ctrl + wheel is an extra (never the only way, P-03).',
    'Fit measures the rendered height of the grid against the stage with a ResizeObserver and snaps down to the preset that shows everything.',
    'Activating a card navigates to the page; when the current role lacks the route permission the session switches to the demo user of that surface first (the same ?as= semantics as the hub cards), and a toast names the role.',
  ],
  components: ['PageHeader', 'StatTile', 'FilterBar', 'SearchField', 'Select', 'Button', 'SurfaceCard', 'EmptyState', 'Badge'],
  actions: [
    { id: 'tools.zoomCanvas', label: 'Zoom the canvas', intent: 'zoom the canvas to {zoom} percent', permission: 'dev.tools', params: { zoom: 'number' } },
    { id: 'tools.fitCanvas', label: 'Fit the canvas', intent: 'fit the whole canvas in view', permission: 'dev.tools' },
    { id: 'tools.filterCanvasSurface', label: 'Filter the canvas by surface', intent: 'show only the {surface} pages', permission: 'dev.tools', params: { surface: 'enum:all|hub|founder|ops|studio|brand|client|dev|docs|manual|public' } },
    { id: 'tools.filterCanvasStatus', label: 'Filter the canvas by status', intent: 'show only {status} pages', permission: 'dev.tools', params: { status: 'enum:all|built|stub' } },
    { id: 'tools.searchCanvas', label: 'Search the canvas', intent: 'find the page {query}', permission: 'dev.tools', params: { query: 'string' } },
    { id: 'tools.openCanvasPage', label: 'Open a page from the canvas', intent: 'open the page {code}', permission: 'dev.tools', params: { code: 'string' } },
  ],
  checkedAt: [360, 390, 768, 1280, 1920],
});

export const simulatorSpec = defineSpec({
  code: 'D-08',
  name: 'Demo simulator',
  purpose: 'The app running in a phone frame and a desktop frame side by side, as any demo role, in either language and theme, so a journey can be shown to Justin or a client from one screen without a second device.',
  surface: 'dev',
  navGroup: 'developer',
  layout: [
    'PageHeader (code, title, subtitle)',
    'Controls: route Select (every route with a menu entry, grouped by surface), role Select, language Select, theme Select, sync ToggleButton',
    'Presets row: client phone journey, founder dashboard, ops schedule, public services',
    'Two device frames side by side (stacked under 1024 px): phone 390 × 844 and desktop 1280 × 800, each an iframe of the app plus its size caption and an "Open in new tab" Button',
    'Note about the shared origin: the frames share this tab’s storage and session',
  ],
  dataTables: [],
  roles: ['dev', 'founder'],
  logic: [
    'Each frame is an <iframe> of ./index.html?as=<role>#<path> (the app is a HashRouter, so one iframe per frame) with a translated title and loading="lazy".',
    'The desktop frame renders at 1280 × 800 and is transform: scale()d to its column, the phone at 390 × 844 and scaled only when the column is narrower; both scales come from a ResizeObserver on the column.',
    'Language and theme go through the parent providers, which write aluzina.lang / aluzina.theme; the frames are then remounted so they load with the new value. Same origin means the parent follows too — the page says so.',
    'Sync on: the route Select drives both frames. Sync off: it drives the phone only and the desktop stays where it was browsed inside the frame.',
    'A preset sets route and role together; a preset whose route is not registered yet is a Placeholder.',
  ],
  components: ['PageHeader', 'Select', 'ToggleButton', 'Button', 'Card', 'Placeholder', 'EmptyState'],
  actions: [
    { id: 'tools.simulateRoute', label: 'Simulate a route', intent: 'show {route} in the simulator', permission: 'dev.tools', params: { route: 'string' } },
    { id: 'tools.simulateRole', label: 'Simulate a role', intent: 'view the simulator as {role}', permission: 'dev.tools', params: { role: 'enum:founder|ops|studio|brand|marketing|client|dev' } },
    { id: 'tools.simulateLang', label: 'Simulate a language', intent: 'switch the simulator to {lang}', permission: 'dev.tools', params: { lang: 'enum:en|es' } },
    { id: 'tools.simulateTheme', label: 'Simulate a theme', intent: 'switch the simulator to the {theme} theme', permission: 'dev.tools', params: { theme: 'enum:light|dark' } },
    { id: 'tools.openSimulatedTab', label: 'Open a frame in a new tab', intent: 'open the {frame} frame in a new tab', permission: 'dev.tools', params: { frame: 'enum:phone|desktop' } },
    { id: 'tools.toggleFrameSync', label: 'Toggle frame sync', intent: 'make both frames follow the same route', permission: 'dev.tools', params: { on: 'boolean' } },
    { id: 'tools.applyDemoPreset', label: 'Apply a demo preset', intent: 'set up the {preset} demo', permission: 'dev.tools', params: { preset: 'enum:clientJourney|founderDashboard|opsSchedule|publicServices' } },
  ],
  checkedAt: [360, 390, 768, 1280, 1920],
});
