import type { StringTable } from '../../i18n/types';

/** Builder tools (D-05 plan viewer, D-07 canvas, D-08 demo simulator). Namespace `tools.*` (P-13). */
export const strings: StringTable = {
  'tools.nav.plan': { en: 'Plan', es: 'Plan' },
  'tools.nav.canvas': { en: 'Canvas', es: 'Lienzo' },
  'tools.nav.simulator': { en: 'Simulator', es: 'Simulador' },
  'tools.summary': { en: '{shown} of {total}', es: '{shown} de {total}' },

  // Surfaces (the canvas groups by them; core.portal.* only covers the role portals).
  'tools.surface.hub': { en: 'Hub', es: 'Hub' },
  'tools.surface.founder': { en: 'Founder portal', es: 'Portal de la fundadora' },
  'tools.surface.ops': { en: 'Operations portal', es: 'Portal de operaciones' },
  'tools.surface.studio': { en: 'Studio portal', es: 'Portal de diseño' },
  'tools.surface.brand': { en: 'Brand portal', es: 'Portal de marca' },
  'tools.surface.client': { en: 'Client app', es: 'App del cliente' },
  'tools.surface.dev': { en: 'Dev tools', es: 'Herramientas de desarrollo' },
  'tools.surface.docs': { en: 'Documentation', es: 'Documentación' },
  'tools.surface.manual': { en: 'Operations manual', es: 'Manual de operaciones' },
  'tools.surface.public': { en: 'Public website', es: 'Sitio público' },

  // D-05 Plan viewer
  'tools.plan.title': { en: 'Development plan', es: 'Plan de desarrollo' },
  'tools.plan.subtitle': { en: 'The plan as data: {tasks} tasks bound by dependencies, not calendar days. Board, list and dependency timeline read the same docs/plan/plan.json.', es: 'El plan como datos: {tasks} tareas atadas por dependencias, no por días de calendario. Tablero, lista y línea de dependencias leen el mismo docs/plan/plan.json.' },
  'tools.plan.source': { en: 'Source', es: 'Fuente' },
  'tools.plan.updated': { en: 'plan.json {version} · updated {date}', es: 'plan.json {version} · actualizado {date}' },
  'tools.plan.views': { en: 'Plan views', es: 'Vistas del plan' },
  'tools.plan.tab.board': { en: 'Board', es: 'Tablero' },
  'tools.plan.tab.list': { en: 'List', es: 'Lista' },
  'tools.plan.tab.timeline': { en: 'Timeline', es: 'Línea de tiempo' },
  'tools.plan.search': { en: 'Search id, title, code, model…', es: 'Buscar id, título, código, modelo…' },
  'tools.plan.status': { en: 'Status', es: 'Estado' },
  'tools.plan.allStatuses': { en: 'All statuses', es: 'Todos los estados' },
  'tools.plan.model': { en: 'Model', es: 'Modelo' },
  'tools.plan.allModels': { en: 'All models', es: 'Todos los modelos' },
  'tools.plan.step': { en: 'Step', es: 'Paso' },
  'tools.plan.allSteps': { en: 'All steps', es: 'Todos los pasos' },
  'tools.plan.status.done': { en: 'Done', es: 'Hecho' },
  'tools.plan.status.doing': { en: 'Doing', es: 'En curso' },
  'tools.plan.status.next': { en: 'Next', es: 'Siguiente' },
  'tools.plan.status.backlog': { en: 'Backlog', es: 'Pendiente' },
  'tools.plan.board': { en: 'Plan board', es: 'Tablero del plan' },
  'tools.plan.move': { en: 'Move a task', es: 'Mover una tarea' },
  'tools.plan.moveWhat': { en: 'move a task between columns — edits land in docs/plan/plan.json via the repo', es: 'mover una tarea entre columnas — los cambios se hacen en docs/plan/plan.json en el repositorio' },
  'tools.plan.readOnly': { en: 'Read-only view. The plan is edited in docs/plan/plan.json in the repo, and build-plan.md and kanban.md must agree with it (D-037).', es: 'Vista de solo lectura. El plan se edita en docs/plan/plan.json en el repositorio, y build-plan.md y kanban.md deben coincidir con él (D-037).' },
  'tools.plan.col.id': { en: 'Id', es: 'Id' },
  'tools.plan.col.title': { en: 'Task', es: 'Tarea' },
  'tools.plan.col.step': { en: 'Step', es: 'Paso' },
  'tools.plan.col.status': { en: 'Status', es: 'Estado' },
  'tools.plan.col.model': { en: 'Model', es: 'Modelo' },
  'tools.plan.col.codes': { en: 'Codes', es: 'Códigos' },
  'tools.plan.col.deps': { en: 'Depends on', es: 'Depende de' },
  'tools.plan.col.changelog': { en: 'Changelog', es: 'Registro' },
  'tools.plan.list': { en: 'Plan tasks', es: 'Tareas del plan' },
  'tools.plan.timeline': { en: 'Dependency timeline', es: 'Línea de dependencias' },
  'tools.plan.timelineHint': { en: 'One lane per build-plan step; a task sits in the column of its dependency depth, so nothing can start left of what it depends on. Arrows are decoration: every dependency is also written out as text. Arrow keys move between tasks.', es: 'Un carril por paso del plan; cada tarea se ubica en la columna de su profundidad de dependencias, así nada empieza a la izquierda de aquello de lo que depende. Las flechas son decoración: cada dependencia también está escrita. Las flechas del teclado mueven entre tareas.' },
  'tools.plan.lane': { en: 'Step {step}', es: 'Paso {step}' },
  'tools.plan.depthLabel': { en: 'Dependency depth', es: 'Profundidad de dependencias' },
  'tools.plan.depth': { en: 'Depth {n}', es: 'Profundidad {n}' },
  'tools.plan.blockers': { en: '{n} blockers', es: '{n} bloqueos' },
  'tools.plan.blockersOne': { en: '1 blocker', es: '1 bloqueo' },
  'tools.plan.noBlockers': { en: 'Nothing blocking', es: 'Sin bloqueos' },
  'tools.plan.none': { en: 'No task matches', es: 'Ninguna tarea coincide' },
  'tools.plan.noneHint': { en: 'Clear the search and the filters to see the whole plan.', es: 'Limpia la búsqueda y los filtros para ver todo el plan.' },
  'tools.plan.dependsOn': { en: 'Depends on', es: 'Depende de' },
  'tools.plan.blockedBy': { en: 'Blocked by (not done yet)', es: 'Bloqueada por (aún sin terminar)' },
  'tools.plan.dependents': { en: 'Unblocks', es: 'Desbloquea' },
  'tools.plan.noDeps': { en: 'None', es: 'Ninguna' },
  'tools.plan.owner': { en: 'Owner', es: 'Responsable' },
  'tools.plan.files': { en: 'Files', es: 'Archivos' },
  'tools.plan.pageDocs': { en: 'Page docs', es: 'Documentos de página' },
  'tools.plan.openTask': { en: 'Open {title}', es: 'Abrir {title}' },
  'tools.plan.taskLabel': { en: '{title} — step {step}, {status}, depth {depth}', es: '{title} — paso {step}, {status}, profundidad {depth}' },

  // D-07 Canvas
  'tools.canvas.title': { en: 'Canvas', es: 'Lienzo' },
  'tools.canvas.subtitle': { en: 'Every registered page as a card, grouped by surface, with its deploy-time thumbnail. Zoom out to see the whole system, activate a card to open the page as a demo user of that surface.', es: 'Cada página registrada como una tarjeta, agrupada por superficie, con su miniatura de despliegue. Aleja para ver todo el sistema, activa una tarjeta para abrir la página como usuario demo de esa superficie.' },
  'tools.canvas.search': { en: 'Search code, name, path…', es: 'Buscar código, nombre, ruta…' },
  'tools.canvas.surface': { en: 'Surface', es: 'Superficie' },
  'tools.canvas.allSurfaces': { en: 'All surfaces', es: 'Todas las superficies' },
  'tools.canvas.status': { en: 'Status', es: 'Estado' },
  'tools.canvas.allStatuses': { en: 'All statuses', es: 'Todos los estados' },
  'tools.canvas.live': { en: 'Built', es: 'Construida' },
  'tools.canvas.stub': { en: 'Stub', es: 'Borrador' },
  'tools.canvas.zoom': { en: 'Zoom', es: 'Zoom' },
  'tools.canvas.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'tools.canvas.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'tools.canvas.fit': { en: 'Fit', es: 'Ajustar' },
  'tools.canvas.zoomNow': { en: 'Zoom {pct}%', es: 'Zoom {pct}%' },
  'tools.canvas.stage': { en: 'Page canvas', es: 'Lienzo de páginas' },
  'tools.canvas.hint': { en: 'Buttons, the preset list and Ctrl + wheel all zoom; the canvas scrolls inside its frame so the page never scrolls sideways.', es: 'Los botones, la lista de niveles y Ctrl + rueda hacen zoom; el lienzo se desplaza dentro de su marco, así la página nunca se desplaza en horizontal.' },
  'tools.canvas.groupOne': { en: '{surface} · 1 page', es: '{surface} · 1 página' },
  'tools.canvas.group': { en: '{surface} · {n} pages', es: '{surface} · {n} páginas' },
  'tools.canvas.desc': { en: '{path} · {shell} shell · {permission}', es: '{path} · shell {shell} · {permission}' },
  'tools.canvas.noPermission': { en: 'no permission needed', es: 'sin permiso' },
  'tools.canvas.none': { en: 'No page matches', es: 'Ninguna página coincide' },
  'tools.canvas.noneHint': { en: 'Clear the search and the filters to see every registered page.', es: 'Limpia la búsqueda y los filtros para ver todas las páginas registradas.' },
  'tools.canvas.enterAs': { en: 'Opening {code} as {role}', es: 'Abriendo {code} como {role}' },
  'tools.canvas.open': { en: 'Open', es: 'Abrir' },
  'tools.canvas.pages': { en: 'Pages', es: 'Páginas' },
  'tools.canvas.built': { en: 'Built', es: 'Construidas' },
  'tools.canvas.stubs': { en: 'Stubs', es: 'Borradores' },
  'tools.canvas.surfaces': { en: 'Surfaces', es: 'Superficies' },

  // D-08 Demo simulator
  'tools.sim.title': { en: 'Demo simulator', es: 'Simulador de demo' },
  'tools.sim.subtitle': { en: 'The same app in a phone frame and a desktop frame, side by side, as any demo role. Use it to walk a client or Justin through a journey without touching a device.', es: 'La misma app en un marco de teléfono y uno de escritorio, lado a lado, como cualquier rol demo. Sirve para recorrer un flujo con un cliente o con Justin sin tocar un dispositivo.' },
  'tools.sim.route': { en: 'Route', es: 'Ruta' },
  'tools.sim.role': { en: 'Role', es: 'Rol' },
  'tools.sim.lang': { en: 'Language', es: 'Idioma' },
  'tools.sim.lang.en': { en: 'English', es: 'Inglés' },
  'tools.sim.lang.es': { en: 'Spanish', es: 'Español' },
  'tools.sim.theme': { en: 'Theme', es: 'Tema' },
  'tools.sim.theme.light': { en: 'Light', es: 'Claro' },
  'tools.sim.theme.dark': { en: 'Dark', es: 'Oscuro' },
  'tools.sim.sync': { en: 'Sync frames', es: 'Sincronizar marcos' },
  'tools.sim.syncOn': { en: 'Frames synced', es: 'Marcos sincronizados' },
  'tools.sim.syncOff': { en: 'Frames independent', es: 'Marcos independientes' },
  'tools.sim.syncHint': { en: 'Synced: the route select drives both frames. Independent: it drives the phone only and the desktop frame stays where you browsed it.', es: 'Sincronizados: la ruta controla ambos marcos. Independientes: controla solo el teléfono y el marco de escritorio se queda donde navegaste.' },
  'tools.sim.phone': { en: 'Phone', es: 'Teléfono' },
  'tools.sim.desktop': { en: 'Desktop', es: 'Escritorio' },
  'tools.sim.frameTitle': { en: '{device} frame: {route} as {role}', es: 'Marco {device}: {route} como {role}' },
  'tools.sim.size': { en: '{w} × {h} px · shown at {pct}%', es: '{w} × {h} px · mostrado al {pct}%' },
  'tools.sim.openTab': { en: 'Open in new tab', es: 'Abrir en pestaña nueva' },
  'tools.sim.openTabLabel': { en: 'Open the {device} frame in a new tab', es: 'Abrir el marco {device} en una pestaña nueva' },
  'tools.sim.presets': { en: 'Presets', es: 'Escenarios' },
  'tools.sim.preset.clientJourney': { en: 'Client phone journey', es: 'Recorrido del cliente en teléfono' },
  'tools.sim.preset.founderDashboard': { en: 'Founder dashboard', es: 'Panel de la fundadora' },
  'tools.sim.preset.opsSchedule': { en: 'Ops schedule', es: 'Agenda de operaciones' },
  'tools.sim.preset.publicServices': { en: 'Public services', es: 'Servicios públicos' },
  'tools.sim.presetMissing': { en: 'open {name} — the route is not registered yet', es: 'abrir {name} — la ruta aún no está registrada' },
  'tools.sim.storageNote': { en: 'The frames are the same origin as this tab, so they share localStorage and this tab’s session: changing language, theme or role here changes them for this tab too, and reloading this tab lands you as the last simulated role.', es: 'Los marcos tienen el mismo origen que esta pestaña, así que comparten localStorage y la sesión de esta pestaña: cambiar idioma, tema o rol aquí también los cambia para esta pestaña, y al recargarla entrarás como el último rol simulado.' },
  'tools.sim.noRoutes': { en: 'No route with a menu entry is registered yet', es: 'Todavía no hay rutas con entrada de menú' },
  'tools.sim.frames': { en: 'Device frames', es: 'Marcos de dispositivo' },
};
