import type { StringTable } from '../../i18n/types';

/** Founder portal (A-01..A-07). Namespace `founder.`; Spanish is complete (the studio is Spanish-first, D-004). */
export const strings: StringTable = {
  // nav
  'founder.nav.home': { en: 'Dashboard', es: 'Panel' },
  'founder.nav.approvals': { en: 'Approvals', es: 'Aprobaciones' },
  'founder.nav.pipeline': { en: 'Pipeline', es: 'Pipeline' },
  'founder.nav.proposals': { en: 'Quotes and proposals', es: 'Cotizaciones y propuestas' },
  'founder.nav.products': { en: 'Products and partnerships', es: 'Producto y alianzas' },
  'founder.nav.clients': { en: 'Clients', es: 'Clientes' },
  'founder.nav.team': { en: 'Team overview', es: 'Panorama del equipo' },

  // shared
  'founder.common.project': { en: 'Project', es: 'Proyecto' },
  'founder.common.client': { en: 'Client', es: 'Cliente' },
  'founder.common.phase': { en: 'Phase', es: 'Fase' },
  'founder.common.status': { en: 'Status', es: 'Estado' },
  'founder.common.approval': { en: 'Approval', es: 'Aprobación' },
  'founder.common.creativeDirection': { en: 'Creative direction', es: 'Dirección creativa' },
  'founder.common.budget': { en: 'Budget', es: 'Presupuesto' },
  'founder.common.due': { en: 'Due', es: 'Fecha límite' },
  'founder.common.leadDesigner': { en: 'Lead designer', es: 'Diseñadora líder' },
  'founder.common.location': { en: 'Location', es: 'Ubicación' },
  'founder.common.type': { en: 'Type', es: 'Tipo' },
  'founder.common.summary': { en: 'Summary', es: 'Resumen' },
  'founder.common.owner': { en: 'Owner', es: 'Responsable' },
  'founder.common.title': { en: 'Title', es: 'Título' },
  'founder.common.date': { en: 'Date', es: 'Fecha' },
  'founder.common.amount': { en: 'Amount', es: 'Monto' },
  'founder.common.version': { en: 'Version', es: 'Versión' },
  'founder.common.all': { en: 'All', es: 'Todos' },
  'founder.common.none': { en: 'None', es: 'Ninguno' },
  'founder.common.saved': { en: 'Saved', es: 'Guardado' },
  'founder.common.close': { en: 'Close', es: 'Cerrar' },
  'founder.common.noProject': { en: 'Studio (no project)', es: 'Estudio (sin proyecto)' },

  'founder.phase.lead': { en: 'Lead', es: 'Prospecto' },
  'founder.phase.concept': { en: 'Concept', es: 'Concepto' },
  'founder.phase.development': { en: 'Development', es: 'Desarrollo' },
  'founder.phase.documentation': { en: 'Documentation', es: 'Documentación' },
  'founder.phase.procurement': { en: 'Procurement', es: 'Compras' },
  'founder.phase.execution': { en: 'Execution', es: 'Obra' },
  'founder.phase.delivered': { en: 'Delivered', es: 'Entregado' },

  'founder.type.residential': { en: 'Residential', es: 'Residencial' },
  'founder.type.commercial': { en: 'Commercial', es: 'Comercial' },
  'founder.type.hospitality': { en: 'Hospitality', es: 'Hostelería' },
  'founder.type.wellness': { en: 'Wellness', es: 'Bienestar' },
  'founder.type.lighting-product': { en: 'Lighting product', es: 'Producto de iluminación' },

  'founder.cd.pending': { en: 'Pending', es: 'Pendiente' },
  'founder.cd.set': { en: 'Set', es: 'Definida' },
  'founder.cd.revised': { en: 'Being revised', es: 'En revisión' },

  'founder.role.founder': { en: 'Alejandra (founder)', es: 'Alejandra (fundadora)' },
  'founder.role.ops': { en: 'Miguel (operations)', es: 'Miguel (operaciones)' },
  'founder.role.studio': { en: 'Sarai (interior design)', es: 'Sarai (diseño interior)' },
  'founder.role.brand': { en: 'Angélica (graphic design)', es: 'Angélica (diseño gráfico)' },

  // A-01 dashboard
  'founder.home.title': { en: 'Founder dashboard', es: 'Panel de la fundadora' },
  'founder.home.desc': {
    en: 'What waits for your approval, the pipeline, this week and the money, in one screen.',
    es: 'Lo que espera tu aprobación, el pipeline, la semana y el dinero, en una sola pantalla.',
  },
  'founder.home.stat.waiting': { en: 'Waiting for you', es: 'Esperan tu decisión' },
  'founder.home.stat.waitingHint': { en: 'projects to approve', es: 'proyectos por aprobar' },
  'founder.home.stat.projects': { en: 'Live projects', es: 'Proyectos activos' },
  'founder.home.stat.projectsHint': { en: 'not delivered yet', es: 'aún sin entregar' },
  'founder.home.stat.alerts': { en: 'Open alerts', es: 'Alertas abiertas' },
  'founder.home.stat.alertsHint': { en: '{n} urgent', es: '{n} urgentes' },
  'founder.home.stat.owed': { en: 'Owed to the studio', es: 'Nos deben' },
  'founder.home.stat.owedHint': { en: '{n} overdue', es: '{n} vencidos' },
  'founder.home.waiting': { en: 'Waiting for you', es: 'Esperan tu decisión' },
  'founder.home.waitingAll': { en: 'See all approvals', es: 'Ver todas las aprobaciones' },
  'founder.home.pipeline': { en: 'Pipeline by phase', es: 'Pipeline por fase' },
  'founder.home.pipelineOpen': { en: 'Open the pipeline', es: 'Abrir el pipeline' },
  'founder.home.week': { en: 'This week', es: 'Esta semana' },
  'founder.home.weekEmpty': { en: 'No meetings in the next seven days', es: 'Sin reuniones en los próximos siete días' },
  'founder.home.alerts': { en: 'Alerts from operations', es: 'Alertas de operaciones' },
  'founder.home.alertsEmpty': { en: 'No open alerts', es: 'Sin alertas abiertas' },
  'founder.home.alertsNote': { en: 'Miguel owns these: read only here.', es: 'Miguel es el responsable: aquí solo se leen.' },
  'founder.home.money': { en: 'Money', es: 'Dinero' },
  'founder.home.moneyNote': { en: 'Read only: payments live in the operations portal.', es: 'Solo lectura: los pagos viven en el portal de operaciones.' },
  'founder.home.money.in': { en: 'Owed to the studio', es: 'Nos deben' },
  'founder.home.money.out': { en: 'Owed to suppliers', es: 'Debemos a proveedores' },
  'founder.home.money.overdue': { en: 'Overdue payments', es: 'Pagos vencidos' },
  'founder.home.money.budget': { en: 'Budget in live projects', es: 'Presupuesto en proyectos activos' },

  // approvals (A-02, shared with A-01)
  'founder.approvals.title': { en: 'Approvals', es: 'Aprobaciones' },
  'founder.approvals.desc': {
    en: 'Final project approval: the studio checks, then you decide.',
    es: 'Aprobación final de proyecto: el estudio revisa y tú decides.',
  },
  'founder.approvals.queue': { en: 'Waiting for you', es: 'Esperan tu decisión' },
  'founder.approvals.queueLabel': { en: 'Projects waiting for the founder', es: 'Proyectos que esperan a la fundadora' },
  'founder.approvals.empty': { en: 'Nothing waiting for your decision', es: 'Nada espera tu decisión' },
  'founder.approvals.checkPassed': { en: 'Consistency check passed', es: 'Chequeo de consistencia aprobado' },
  'founder.approvals.checkIssues': { en: 'Consistency check with {n} open items', es: 'Chequeo de consistencia con {n} puntos abiertos' },
  'founder.approvals.checkPending': { en: 'Consistency check still pending', es: 'Chequeo de consistencia pendiente' },
  'founder.approvals.checkNone': { en: 'No consistency check yet', es: 'Aún sin chequeo de consistencia' },
  'founder.approvals.meta': { en: '{client} · {phase} · due {due}', es: '{client} · {phase} · vence {due}' },
  'founder.approvals.approved': { en: '{project} approved', es: '{project} aprobado' },
  'founder.approvals.rejected': { en: 'Changes requested on {project}', es: 'Cambios solicitados en {project}' },
  'founder.approvals.commented': { en: 'Note sent to the design team', es: 'Nota enviada al equipo de diseño' },
  'founder.approvals.changeTask': { en: 'Founder requested changes: {project}', es: 'La fundadora pidió cambios: {project}' },
  'founder.approvals.noteTask': { en: 'Founder note: {note}', es: 'Nota de la fundadora: {note}' },
  'founder.approvals.checks': { en: 'Consistency checks', es: 'Chequeos de consistencia' },
  'founder.approvals.checksCaption': { en: 'Consistency checks by project', es: 'Chequeos de consistencia por proyecto' },
  'founder.approvals.col.check': { en: 'Check', es: 'Chequeo' },
  'founder.approvals.col.items': { en: 'Items OK', es: 'Puntos OK' },
  'founder.approvals.col.checkedBy': { en: 'Checked by', es: 'Revisado por' },
  'founder.approvals.open': { en: 'Open', es: 'Abrir' },
  'founder.approvals.decided': { en: 'Already decided', es: 'Ya decididos' },
  'founder.approvals.decidedCaption': { en: 'Projects already decided', es: 'Proyectos ya decididos' },
  'founder.approvals.decidedEmpty': { en: 'No decisions yet', es: 'Aún sin decisiones' },
  'founder.approvals.notes': { en: 'Notes from the studio', es: 'Notas del estudio' },
  'founder.approvals.itemsLabel': { en: 'Checked items', es: 'Puntos revisados' },
  'founder.approvals.itemOk': { en: 'OK', es: 'OK' },
  'founder.approvals.itemNotOk': { en: 'Open', es: 'Abierto' },
  'founder.approvals.readOnly': { en: 'Sarai owns the check: read only here.', es: 'El chequeo es de Sarai: aquí solo se lee.' },

  // A-03 pipeline
  'founder.pipeline.title': { en: 'Pipeline', es: 'Pipeline' },
  'founder.pipeline.desc': {
    en: 'Every project in its phase, from the first lead to delivery.',
    es: 'Cada proyecto en su fase, del primer prospecto a la entrega.',
  },
  'founder.pipeline.board': { en: 'Projects by phase', es: 'Proyectos por fase' },
  'founder.pipeline.filterType': { en: 'Type', es: 'Tipo' },
  'founder.pipeline.filterApproval': { en: 'Approval', es: 'Aprobación' },
  'founder.pipeline.summary': { en: '{n} of {total} projects', es: '{n} de {total} proyectos' },
  'founder.pipeline.moved': { en: '{project} moved to {phase}', es: '{project} pasó a {phase}' },
  'founder.pipeline.newLead': { en: 'New lead', es: 'Nuevo prospecto' },
  'founder.pipeline.newLeadWhat': { en: 'creating a lead from the pipeline', es: 'crear un prospecto desde el pipeline' },
  'founder.pipeline.setDirection': { en: 'Mark creative direction as set', es: 'Marcar dirección creativa como definida' },
  'founder.pipeline.directionSet': { en: 'Creative direction set for {project}', es: 'Dirección creativa definida para {project}' },

  // A-04 quotes and proposals
  'founder.proposals.title': { en: 'Quotes and proposals', es: 'Cotizaciones y propuestas' },
  'founder.proposals.desc': {
    en: 'Client quotes, graphic proposals and project PDFs you write, and the supplier quotes you review before negotiating.',
    es: 'Cotizaciones de cliente, propuestas gráficas y PDFs de proyecto que escribes, y las cotizaciones de proveedor que revisas antes de negociar.',
  },
  'founder.proposals.tabs': { en: 'Quotes and proposals', es: 'Cotizaciones y propuestas' },
  'founder.proposals.tab.documents': { en: 'Client documents', es: 'Documentos de cliente' },
  'founder.proposals.tab.presentations': { en: 'Graphic proposals', es: 'Propuestas gráficas' },
  'founder.proposals.tab.quotes': { en: 'Supplier quotes', es: 'Cotizaciones de proveedor' },
  'founder.proposals.docsCaption': { en: 'Client quotes, PDFs and briefs', es: 'Cotizaciones, PDFs y briefs de cliente' },
  'founder.proposals.col.kind': { en: 'Kind', es: 'Tipo' },
  'founder.proposals.kind.quote': { en: 'Client quote', es: 'Cotización de cliente' },
  'founder.proposals.kind.project-pdf': { en: 'Project PDF', es: 'PDF de proyecto' },
  'founder.proposals.kind.brief': { en: 'Brief', es: 'Brief' },
  'founder.proposals.finalise': { en: 'Mark final', es: 'Marcar final' },
  'founder.proposals.send': { en: 'Send to client', es: 'Enviar al cliente' },
  'founder.proposals.finalised': { en: '{title} is final', es: '{title} quedó final' },
  'founder.proposals.sent': { en: '{title} sent to the client', es: '{title} enviado al cliente' },
  'founder.proposals.presCaption': { en: 'Graphic proposals and sales decks', es: 'Propuestas gráficas y presentaciones de venta' },
  'founder.proposals.col.slides': { en: 'Slides', es: 'Láminas' },
  'founder.proposals.signOff': { en: 'Sign off', es: 'Dar visto bueno' },
  'founder.proposals.signedOff': { en: '{title} signed off', es: '{title} con visto bueno' },
  'founder.proposals.quotesCaption': { en: 'Supplier quotes collected by operations', es: 'Cotizaciones de proveedor reunidas por operaciones' },
  'founder.proposals.col.group': { en: 'Comparison', es: 'Comparativo' },
  'founder.proposals.col.item': { en: 'Item', es: 'Ítem' },
  'founder.proposals.col.lead': { en: 'Lead time (days)', es: 'Entrega (días)' },
  'founder.proposals.col.valid': { en: 'Valid until', es: 'Vigente hasta' },
  'founder.proposals.shortlist': { en: 'Shortlist', es: 'Preseleccionar' },
  'founder.proposals.shortlisted': { en: 'Quote shortlisted', es: 'Cotización preseleccionada' },
  'founder.proposals.quotesNote': {
    en: 'Miguel selects the winning quote in the operations portal; here you shortlist what you want on the table.',
    es: 'Miguel selecciona la cotización ganadora en el portal de operaciones; aquí preseleccionas lo que quieres sobre la mesa.',
  },
  'founder.proposals.new': { en: 'New client quote', es: 'Nueva cotización de cliente' },
  'founder.proposals.newWhat': { en: 'writing a client quote from a template', es: 'escribir una cotización de cliente desde una plantilla' },
  'founder.proposals.emptyDocs': { en: 'No client documents yet', es: 'Aún no hay documentos de cliente' },
  'founder.proposals.emptyPres': { en: 'No graphic proposals yet', es: 'Aún no hay propuestas gráficas' },
  'founder.proposals.emptyQuotes': { en: 'No supplier quotes to review', es: 'Sin cotizaciones de proveedor por revisar' },

  // A-05 products and partnerships
  'founder.products.title': { en: 'Products and partnerships', es: 'Producto y alianzas' },
  'founder.products.desc': {
    en: 'Lighting fixture development and the partnerships that produce it.',
    es: 'Desarrollo de luminarias y las alianzas que las producen.',
  },
  'founder.products.materials': { en: 'Materials', es: 'Materiales' },
  'founder.products.materialsCaption': { en: 'Materials of {project}', es: 'Materiales de {project}' },
  'founder.products.col.material': { en: 'Material', es: 'Material' },
  'founder.products.col.finish': { en: 'Finish', es: 'Acabado' },
  'founder.products.col.unit': { en: 'Unit price', es: 'Precio unitario' },
  'founder.products.approve': { en: 'Approve', es: 'Aprobar' },
  'founder.products.approved': { en: '{name} approved for the collection', es: '{name} aprobado para la colección' },
  'founder.products.packs': { en: 'Render and supplier packs', es: 'Paquetes de render y proveedor' },
  'founder.products.packsCaption': { en: 'Render and supplier packs of {project}', es: 'Paquetes de render y proveedor de {project}' },
  'founder.products.col.audience': { en: 'For', es: 'Para' },
  'founder.products.audience.render-artist': { en: 'Render artist', es: 'Renderista' },
  'founder.products.audience.supplier': { en: 'Supplier', es: 'Proveedor' },
  'founder.products.col.views': { en: 'Views', es: 'Vistas' },
  'founder.products.tasks': { en: 'Open tasks', es: 'Tareas abiertas' },
  'founder.products.tasksCaption': { en: 'Open tasks of {project}', es: 'Tareas abiertas de {project}' },
  'founder.products.tasksEmpty': { en: 'No open tasks', es: 'Sin tareas abiertas' },
  'founder.products.meetings': { en: 'Strategic meetings and negotiations', es: 'Reuniones estratégicas y negociaciones' },
  'founder.products.meetingsEmpty': { en: 'No strategic meetings scheduled', es: 'Sin reuniones estratégicas programadas' },
  'founder.products.new': { en: 'New partnership', es: 'Nueva alianza' },
  'founder.products.newWhat': { en: 'recording a partnership (there is no partnerships entity yet)', es: 'registrar una alianza (aún no existe la entidad de alianzas)' },
  'founder.products.roadmap': { en: 'Collection roadmap', es: 'Ruta de la colección' },
  'founder.products.roadmapWhat': { en: 'a product roadmap (needs a products entity)', es: 'una ruta de producto (necesita una entidad de producto)' },
  'founder.products.roadmapBody': {
    en: 'Prototype, tooling and launch dates per fixture will live here once product is an entity of its own.',
    es: 'Prototipo, herramentaje y fechas de lanzamiento por luminaria vivirán aquí cuando producto sea una entidad propia.',
  },
  'founder.products.empty': { en: 'No product projects yet', es: 'Aún no hay proyectos de producto' },
  'founder.products.emptyDesc': { en: 'A project of type "lighting product" appears here.', es: 'Un proyecto de tipo "producto de iluminación" aparece aquí.' },

  // A-06 clients
  'founder.clients.title': { en: 'Clients and negotiations', es: 'Clientes y negociaciones' },
  'founder.clients.desc': {
    en: 'Every client with their projects, the budget in play, what they owe and the next conversation.',
    es: 'Cada cliente con sus proyectos, el presupuesto en juego, lo que debe y la próxima conversación.',
  },
  'founder.clients.stat.clients': { en: 'Clients', es: 'Clientes' },
  'founder.clients.stat.budget': { en: 'Budget in play', es: 'Presupuesto en juego' },
  'founder.clients.stat.outstanding': { en: 'Owed to the studio', es: 'Nos deben' },
  'founder.clients.caption': { en: 'Clients and their projects', es: 'Clientes y sus proyectos' },
  'founder.clients.col.projects': { en: 'Projects', es: 'Proyectos' },
  'founder.clients.col.outstanding': { en: 'Outstanding', es: 'Por cobrar' },
  'founder.clients.col.next': { en: 'Next meeting', es: 'Próxima reunión' },
  'founder.clients.drawerProjects': { en: 'Projects', es: 'Proyectos' },
  'founder.clients.drawerPayments': { en: 'Payments', es: 'Pagos' },
  'founder.clients.drawerMeetings': { en: 'Meetings', es: 'Reuniones' },
  'founder.clients.drawerDocs': { en: 'Documents', es: 'Documentos' },
  'founder.clients.note': { en: 'Log a note', es: 'Registrar una nota' },
  'founder.clients.noteWhat': { en: 'client notes (needs a clients entity)', es: 'notas de cliente (necesita una entidad de clientes)' },
  'founder.clients.empty': { en: 'No client matches the search', es: 'Ningún cliente coincide con la búsqueda' },
  'founder.clients.noneScheduled': { en: 'Nothing scheduled', es: 'Nada programado' },

  // A-07 team overview
  'founder.team.title': { en: 'Team overview', es: 'Panorama del equipo' },
  'founder.team.desc': {
    en: 'What each role is carrying right now: their tasks, their alerts and the meetings you share.',
    es: 'Lo que lleva cada rol ahora mismo: sus tareas, sus alertas y las reuniones que comparten.',
  },
  'founder.team.tabs': { en: 'Tasks by role', es: 'Tareas por rol' },
  'founder.team.caption': { en: 'Tasks of {role}', es: 'Tareas de {role}' },
  'founder.team.openTasks': { en: 'open tasks', es: 'tareas abiertas' },
  'founder.team.showDone': { en: 'Show tasks already done', es: 'Mostrar tareas ya hechas' },
  'founder.team.complete': { en: 'Mark done', es: 'Marcar hecha' },
  'founder.team.completed': { en: 'Task marked done', es: 'Tarea marcada como hecha' },
  'founder.team.col.priority': { en: 'Priority', es: 'Prioridad' },
  'founder.team.priority.low': { en: 'Low', es: 'Baja' },
  'founder.team.priority.normal': { en: 'Normal', es: 'Normal' },
  'founder.team.priority.high': { en: 'High', es: 'Alta' },
  'founder.team.priority.urgent': { en: 'Urgent', es: 'Urgente' },
  'founder.team.alerts': { en: 'Alerts', es: 'Alertas' },
  'founder.team.alertsCaption': { en: 'Open alerts by role', es: 'Alertas abiertas por rol' },
  'founder.team.col.severity': { en: 'Severity', es: 'Gravedad' },
  'founder.team.col.for': { en: 'For', es: 'Para' },
  'founder.team.meetings': { en: 'Shared meetings', es: 'Reuniones compartidas' },
  'founder.team.meetingsEmpty': { en: 'No shared meetings scheduled', es: 'Sin reuniones compartidas programadas' },
  'founder.team.vision': { en: 'Vision and growth', es: 'Visión y crecimiento' },
  'founder.team.visionWhat': { en: 'goals and growth targets (needs a goals entity)', es: 'metas y objetivos de crecimiento (necesita una entidad de metas)' },
  'founder.team.visionBody': {
    en: 'Yearly goals, revenue targets and the growth of the studio will be tracked here.',
    es: 'Las metas anuales, los objetivos de ingresos y el crecimiento del estudio se seguirán aquí.',
  },
  'founder.team.tasksEmpty': { en: 'No open tasks for this role', es: 'Sin tareas abiertas para este rol' },

  // meetings shared
  'founder.meeting.kind.client': { en: 'Client', es: 'Cliente' },
  'founder.meeting.kind.supplier': { en: 'Supplier', es: 'Proveedor' },
  'founder.meeting.kind.internal': { en: 'Internal', es: 'Interna' },
  'founder.meeting.kind.site-visit': { en: 'Site visit', es: 'Visita de obra' },
  'founder.meeting.kind.strategic': { en: 'Strategic', es: 'Estratégica' },
  'founder.meeting.today': { en: 'Today', es: 'Hoy' },
  'founder.meeting.tomorrow': { en: 'Tomorrow', es: 'Mañana' },
  'founder.meeting.inDays': { en: 'in {n} days', es: 'en {n} días' },
};
