import type { StringTable } from '../../i18n/types';

/**
 * Operations manual strings (M-01..M-08). English primary, Spanish complete (P-13).
 * The manual's *content* is not here: it comes from `src/domain/playbook.ts` through `pick(text, lang)`,
 * so the founder's wording is never duplicated in a string table.
 */
export const strings: StringTable = {
  // The DesktopShell names the surface with `core.portal.<surface>`; `manual` has no core entry yet
  // (request in `docs/changelog/_pending/manual.md`: move this key into `src/i18n/core.ts`).
  'core.portal.manual': { en: 'Manual', es: 'Manual' },

  'manual.nav.overview': { en: 'Manual', es: 'Manual' },
  'manual.nav.commercial': { en: 'Commercial process', es: 'Proceso comercial' },
  'manual.nav.governance': { en: 'Governance', es: 'Gobernanza' },
  'manual.nav.service.01': { en: '01 Digital consultation', es: '01 Consultoría digital' },
  'manual.nav.service.02': { en: '02 In-person consultation', es: '02 Consultoría presencial' },
  'manual.nav.service.03': { en: '03 Comprehensive design', es: '03 Diseño integral' },
  'manual.nav.service.E': { en: 'E Execution / construction', es: 'E Ejecución / obra' },
  'manual.nav.service.04': { en: '04 Interior styling', es: '04 Styling de interiores' },

  'manual.title': { en: 'Operations manual', es: 'Manual de operaciones' },
  'manual.subtitle': {
    en: 'The ALUZINA Operating System – Service Delivery Playbook v1.0, rendered from the one source the product uses.',
    es: 'El ALUZINA Operating System – Service Delivery Playbook v1.0, renderizado desde la única fuente que usa el producto.',
  },
  'manual.motto': { en: 'One studio. One method. Different depths of service.', es: 'Un estudio. Un método. Distintas profundidades de servicio.' },
  'manual.purpose.title': { en: 'What this manual is for', es: 'Para qué sirve este manual' },
  'manual.purpose.body': {
    en: 'This is how ALUZINA sells, designs, builds, delivers and closes. Every page here is rendered from `src/domain/playbook.ts`, the same data the leads, engagements, checklists and status pipelines of the Hub run on: the manual and the product can never drift apart.',
    es: 'Así vende, diseña, construye, entrega y cierra ALUZINA. Cada página se renderiza desde `src/domain/playbook.ts`, los mismos datos con los que funcionan los leads, los encargos, las listas de chequeo y los estados del Hub: el manual y el producto no pueden separarse.',
  },
  'manual.source': { en: 'Source: docs/knowledge/service-playbook.md (transcription of the founder’s PDF).', es: 'Fuente: docs/knowledge/service-playbook.md (transcripción del PDF de la fundadora).' },

  'manual.print': { en: 'Print / PDF', es: 'Imprimir / PDF' },

  'manual.journey.title': { en: 'Core client journey', es: 'Recorrido central del cliente' },
  'manual.journey.hint': { en: 'Ten steps, the same for every service; each service deepens them.', es: 'Diez pasos, iguales para cada servicio; cada servicio los profundiza.' },
  'manual.journey.step': { en: 'Step {n}', es: 'Paso {n}' },

  'manual.ladder.title': { en: 'The ALUZINA service ladder', es: 'La escalera de servicios ALUZINA' },
  'manual.ladder.open': { en: 'Open {name}', es: 'Abrir {name}' },

  'manual.services.title': { en: 'Services', es: 'Servicios' },
  'manual.service': { en: 'Service {code}', es: 'Servicio {code}' },
  'manual.service.outcome': { en: 'Primary outcome', es: 'Resultado principal' },
  'manual.service.ladderWord': { en: 'Ladder word', es: 'Palabra de la escalera' },
  'manual.service.centralQuestion': { en: 'Central question', es: 'Pregunta central' },
  'manual.service.promise': { en: 'Service promise', es: 'Promesa del servicio' },
  'manual.service.idealFor': { en: 'Ideal for', es: 'Ideal para' },
  'manual.service.phases': { en: 'Phases', es: 'Fases' },
  'manual.service.stages': { en: 'Stages', es: 'Etapas' },
  'manual.service.phase': { en: 'Phase {n}', es: 'Fase {n}' },
  'manual.service.stage': { en: 'Stage {n}', es: 'Etapa {n}' },
  'manual.service.index': { en: 'On this page', es: 'En esta página' },
  'manual.service.indexLabel': { en: 'Phase index', es: 'Índice de fases' },
  'manual.service.delivery': { en: 'What the client receives', es: 'Lo que recibe el cliente' },
  'manual.service.notIncluded': { en: 'Not included (scope protection)', es: 'No incluye (protección del alcance)' },
  'manual.service.nextStep': { en: 'Natural next step', es: 'Siguiente paso natural' },
  'manual.service.prev': { en: 'Previous service', es: 'Servicio anterior' },
  'manual.service.next': { en: 'Next service', es: 'Servicio siguiente' },
  'manual.service.notFound': { en: 'That service is not in the playbook.', es: 'Ese servicio no está en el playbook.' },
  'manual.service.checklist': { en: 'Checklist of {title}', es: 'Lista de chequeo de {title}' },
  'manual.service.readOnly': { en: 'Read-only: the working checklist lives on the studio engagement page.', es: 'Solo lectura: la lista de chequeo operativa vive en la página de encargos del estudio.' },

  'manual.governance.title': { en: 'Governance', es: 'Gobernanza' },
  'manual.governance.subtitle': { en: 'The rules that hold the method together, the status architecture, the roles, the operational assets and the KPIs.', es: 'Las reglas que sostienen el método, la arquitectura de estados, los roles, los activos operativos y los KPI.' },
  'manual.governance.rules': { en: 'Mandatory rules', es: 'Reglas obligatorias' },
  'manual.governance.count': { en: '{n} rules', es: '{n} reglas' },
  'manual.governance.enforcedBy': { en: 'Enforced by', es: 'Se hace cumplir en' },
  'manual.governance.playbookPage': { en: 'Playbook p. {n}', es: 'Playbook p. {n}' },
  'manual.governance.openPage': { en: 'Open {code}', es: 'Abrir {code}' },
  'manual.governance.noPageShort': { en: 'No page enforces this yet', es: 'Ninguna página lo hace cumplir todavía' },
  'manual.governance.noPage': { en: 'Open the page that will enforce {rule}', es: 'Abrir la página que hará cumplir {rule}' },
  'manual.governance.summary': { en: 'Governance', es: 'Gobernanza' },
  'manual.governance.summaryBody': { en: '{n} rules govern the method: {mandatory} mandatory, plus the commercial, method, gate, principle and change-control rules stated inside the services.', es: '{n} reglas rigen el método: {mandatory} obligatorias, más las reglas comercial, de método, de puerta, de principio y de control de cambios enunciadas dentro de los servicios.' },

  'manual.kind.mandatory': { en: 'Mandatory', es: 'Obligatoria' },
  'manual.kind.commercial': { en: 'Commercial', es: 'Comercial' },
  'manual.kind.method': { en: 'Method', es: 'Método' },
  'manual.kind.gate': { en: 'Gate', es: 'Puerta' },
  'manual.kind.principle': { en: 'Principle', es: 'Principio' },
  'manual.kind.changeControl': { en: 'Change control', es: 'Control de cambios' },

  'manual.statuses.title': { en: 'Status architecture', es: 'Arquitectura de estados' },
  'manual.statuses.hint': { en: 'Fifteen statuses, in order; a lead carries the first four, a project carries the rest.', es: 'Quince estados, en orden; un lead lleva los primeros cuatro, un proyecto lleva el resto.' },
  'manual.statuses.group.lead': { en: 'Lead', es: 'Lead' },
  'manual.statuses.group.sale': { en: 'Sale', es: 'Venta' },
  'manual.statuses.group.design': { en: 'Design', es: 'Diseño' },
  'manual.statuses.group.build': { en: 'Build', es: 'Obra' },
  'manual.statuses.group.close': { en: 'Close', es: 'Cierre' },
  'manual.validation.title': { en: 'Validation statuses (revision matrix)', es: 'Estados de validación (matriz de revisión)' },
  'manual.purchase.title': { en: 'Purchase statuses', es: 'Estados de compra' },

  'manual.roles.title': { en: 'Roles and responsibilities', es: 'Roles y responsabilidades' },
  'manual.roles.noPortal': { en: 'No portal role yet', es: 'Aún sin rol de portal' },
  'manual.assets.title': { en: 'Operational assets', es: 'Activos operativos' },
  'manual.assets.none': { en: 'Not in the product yet', es: 'Aún no está en el producto' },
  'manual.assets.template': { en: 'Template', es: 'Plantilla' },
  'manual.kpis.title': { en: 'KPI layer', es: 'Capa de KPI' },
  'manual.kpis.open': { en: 'Open KPI dashboard', es: 'Abrir tablero de KPI' },
  'manual.kpis.openWhat': { en: 'Open the KPI dashboard with these ten indicators', es: 'Abrir el tablero de KPI con estos diez indicadores' },
  'manual.principle.title': { en: 'Final principle', es: 'Principio final' },

  'manual.commercial.title': { en: 'General commercial process', es: 'Proceso comercial general' },
  'manual.commercial.subtitle': { en: 'From the first message to the right service: how a lead enters, what we record, what we ask and how we route it.', es: 'Del primer mensaje al servicio correcto: cómo entra un lead, qué registramos, qué preguntamos y cómo lo enrutamos.' },
  'manual.commercial.channels': { en: 'Lead entry channels', es: 'Canales de entrada de leads' },
  'manual.commercial.channelsHint': { en: 'Wherever the client writes from, the lead is registered the same way.', es: 'Desde donde sea que escriba el cliente, el lead se registra igual.' },
  'manual.commercial.record': { en: 'Immediate registration: lead record', es: 'Registro inmediato: ficha del lead' },
  'manual.commercial.commercialData': { en: 'Immediate registration: commercial data', es: 'Registro inmediato: datos comerciales' },
  'manual.commercial.firstStatus': { en: 'The lead is created with the first status of the pipeline.', es: 'El lead se crea con el primer estado del pipeline.' },
  'manual.commercial.questions': { en: 'Initial qualification', es: 'Calificación inicial' },
  'manual.commercial.questionsHint': { en: 'Ten questions; the answers live in `leads.qualification` and feed the routing.', es: 'Diez preguntas; las respuestas viven en `leads.qualification` y alimentan el enrutamiento.' },
  'manual.commercial.routing': { en: 'Service routing', es: 'Enrutamiento de servicios' },
  'manual.commercial.rule': { en: 'Commercial rule', es: 'Regla comercial' },
  'manual.commercial.widget': { en: 'Route a client', es: 'Enrutar un cliente' },
  'manual.commercial.widgetHint': { en: 'Answer the closed questions to see what the routing would suggest. Nothing is saved: this is the manual, not the CRM.', es: 'Responde las preguntas cerradas para ver qué sugeriría el enrutamiento. No se guarda nada: esto es el manual, no el CRM.' },
  'manual.commercial.visit': { en: 'Does the client want an on-site diagnosis?', es: '¿El cliente quiere un diagnóstico en sitio?' },
  'manual.commercial.unanswered': { en: 'No answer', es: 'Sin responder' },
  'manual.commercial.suggestion': { en: 'Suggested service', es: 'Servicio sugerido' },
  'manual.commercial.then': { en: 'then', es: 'luego' },
  'manual.commercial.reason': { en: 'Why', es: 'Por qué' },
  'manual.commercial.reset': { en: 'Clear answers', es: 'Limpiar respuestas' },
  'manual.commercial.createLead': { en: 'Create lead', es: 'Crear lead' },
  'manual.commercial.createLeadWhat': { en: 'Create a lead from these answers on the leads page (A-08)', es: 'Crear un lead con estas respuestas en la página de leads (A-08)' },
  'manual.commercial.yes': { en: 'Yes', es: 'Sí' },
  'manual.commercial.no': { en: 'No', es: 'No' },
  'manual.commercial.openService': { en: 'Open service {code} in the manual', es: 'Abrir el servicio {code} en el manual' },

  'manual.quickLinks': { en: 'Quick links', es: 'Accesos rápidos' },
  'manual.link.statuses': { en: 'Status architecture (15)', es: 'Arquitectura de estados (15)' },
  'manual.link.kpis': { en: 'KPI layer (10)', es: 'Capa de KPI (10)' },
  'manual.link.commercial': { en: 'Commercial process', es: 'Proceso comercial' },
  'manual.link.governance': { en: 'Governance rules', es: 'Reglas de gobernanza' },
};
