import type { StringTable } from '../../i18n/types';

/** Spaces module strings (K-01..K-06). English primary, Spanish complete (P-13). */
export const strings: StringTable = {
  'spaces.nav.spaces': { en: 'Spaces', es: 'Espacios' },
  'spaces.nav.graph': { en: 'Graph', es: 'Grafo' },
  'spaces.nav.catalog': { en: 'Catalog', es: 'Catálogo' },
  'spaces.nav.import': { en: 'Import from Slack', es: 'Importar desde Slack' },

  'spaces.title': { en: 'Spaces', es: 'Espacios' },
  'spaces.subtitle': { en: 'One place for what belongs in many places: spaces nest without limit, a post is filed wherever it applies, and anything relates to anything.', es: 'Un lugar para lo que pertenece a varios lugares: los espacios se anidan sin límite, una publicación se archiva donde aplique y todo se relaciona con todo.' },
  'spaces.post': { en: 'Post', es: 'Publicación' },
  'spaces.posts': { en: '{n} posts', es: '{n} publicaciones' },
  'spaces.postsOne': { en: '1 post', es: '1 publicación' },
  'spaces.allSpaces': { en: 'All spaces', es: 'Todos los espacios' },
  'spaces.notFound': { en: 'This space does not exist (or was removed).', es: 'Este espacio no existe (o fue eliminado).' },
  'spaces.postNotFound': { en: 'This post does not exist (or was removed).', es: 'Esta publicación no existe (o fue eliminada).' },
  'spaces.postHidden': { en: 'This post is a draft or archived; only its author and editors can see it.', es: 'Esta publicación es un borrador o está archivada; solo su autor y los editores pueden verla.' },
  'spaces.browse': { en: 'Browse spaces', es: 'Explorar espacios' },
  'spaces.treeLabel': { en: 'Spaces tree', es: 'Árbol de espacios' },
  'spaces.search': { en: 'Search spaces and posts', es: 'Buscar espacios y publicaciones' },
  'spaces.searchPlaceholder': { en: 'Search spaces and posts…', es: 'Buscar espacios y publicaciones…' },
  'spaces.searchSpaces': { en: 'Search spaces…', es: 'Buscar espacios…' },
  'spaces.searchResults': { en: 'results for "{query}" across all spaces', es: 'resultados para "{query}" en todos los espacios' },
  'spaces.noTreeMatch': { en: 'No space matches.', es: 'Ningún espacio coincide.' },
  'spaces.noResults': { en: 'No post matches your search.', es: 'Ninguna publicación coincide con la búsqueda.' },
  'spaces.showArchived': { en: 'Show archived', es: 'Mostrar archivados' },
  'spaces.newSpace': { en: 'New space', es: 'Nuevo espacio' },
  'spaces.newPost': { en: 'New post', es: 'Nueva publicación' },
  'spaces.newPostIn': { en: 'New post in {space}', es: 'Nueva publicación en {space}' },
  'spaces.create': { en: 'Create', es: 'Crear' },
  'spaces.publish': { en: 'Publish', es: 'Publicar' },
  'spaces.save': { en: 'Save', es: 'Guardar' },
  'spaces.cancel': { en: 'Cancel', es: 'Cancelar' },
  'spaces.edit': { en: 'Edit', es: 'Editar' },
  'spaces.saved': { en: 'Saved', es: 'Guardado' },
  'spaces.spaceCreated': { en: 'Space created', es: 'Espacio creado' },
  'spaces.postCreated': { en: 'Post published in {space}', es: 'Publicación creada en {space}' },
  'spaces.archive': { en: 'Archive space', es: 'Archivar espacio' },
  'spaces.unarchive': { en: 'Restore space', es: 'Restaurar espacio' },
  'spaces.archived': { en: 'Space archived; it stays findable with "Show archived"', es: 'Espacio archivado; sigue visible con "Mostrar archivados"' },
  'spaces.unarchived': { en: 'Space restored', es: 'Espacio restaurado' },
  'spaces.description': { en: 'Description', es: 'Descripción' },
  'spaces.editDescription': { en: 'Edit description', es: 'Editar descripción' },
  'spaces.noDescription': { en: 'No description yet.', es: 'Sin descripción todavía.' },
  'spaces.children': { en: '{n} spaces inside', es: '{n} espacios dentro' },
  'spaces.hasChildren': { en: 'has spaces inside', es: 'contiene espacios' },
  'spaces.noPosts': { en: 'Nothing filed here yet.', es: 'Nada archivado aquí todavía.' },
  'spaces.noPostsHint': { en: 'Write a post here, or file an existing one from its page.', es: 'Escribe una publicación aquí o archiva una existente desde su página.' },
  'spaces.role.title': { en: 'For your role: {space}', es: 'Para tu rol: {space}' },
  'spaces.role.count': { en: '{n} posts are filed to this role from across the Hub.', es: '{n} publicaciones están archivadas para este rol desde todo el Hub.' },
  'spaces.role.countOne': { en: '1 post is filed to this role from across the Hub.', es: '1 publicación está archivada para este rol desde todo el Hub.' },
  'spaces.role.go': { en: 'Go to my role space', es: 'Ir al espacio de mi rol' },

  'spaces.filter.kind': { en: 'Kind', es: 'Tipo' },
  'spaces.filter.allKinds': { en: 'All kinds', es: 'Todos los tipos' },
  'spaces.filter.tag': { en: 'Tag', es: 'Etiqueta' },
  'spaces.filter.allTags': { en: 'All tags', es: 'Todas las etiquetas' },
  'spaces.filter.author': { en: 'Author', es: 'Autor' },
  'spaces.filter.allAuthors': { en: 'All authors', es: 'Todos los autores' },
  'spaces.sort': { en: 'Sort', es: 'Ordenar' },
  'spaces.sort.updated': { en: 'Last updated', es: 'Última actualización' },
  'spaces.sort.title': { en: 'Title', es: 'Título' },
  'spaces.sort.kind': { en: 'Kind', es: 'Tipo' },
  'spaces.sort.author': { en: 'Author', es: 'Autor' },

  'spaces.form.name': { en: 'Name', es: 'Nombre' },
  'spaces.form.kind': { en: 'Kind', es: 'Tipo' },
  'spaces.form.parent': { en: 'Inside', es: 'Dentro de' },
  'spaces.form.noParent': { en: 'Top level', es: 'Nivel superior' },
  'spaces.form.title': { en: 'Title', es: 'Título' },
  'spaces.form.url': { en: 'Link (URL)', es: 'Enlace (URL)' },
  'spaces.form.body': { en: 'Body', es: 'Contenido' },
  'spaces.form.bodyHint': { en: 'Markdown: # headings, **bold**, - lists, - [ ] tasks, > quotes, | tables |, [links](https://…)', es: 'Markdown: # títulos, **negrita**, - listas, - [ ] tareas, > citas, | tablas |, [enlaces](https://…)' },
  'spaces.form.tags': { en: 'Tags', es: 'Etiquetas' },
  'spaces.form.tagsHint': { en: 'Comma separated, e.g. brand, procesos', es: 'Separadas por comas, p. ej. brand, procesos' },

  'spaces.kind.area': { en: 'Area', es: 'Área' },
  'spaces.kind.topic': { en: 'Topic', es: 'Tema' },
  'spaces.kind.role': { en: 'Role', es: 'Rol' },
  'spaces.kind.client': { en: 'Client', es: 'Cliente' },
  'spaces.kind.deliverable': { en: 'Deliverable', es: 'Entregable' },
  'spaces.kind.tool': { en: 'Tool', es: 'Herramienta' },
  'spaces.kind.project': { en: 'Project', es: 'Proyecto' },
  'spaces.kind.archive': { en: 'Archive', es: 'Archivo' },
  'spaces.kind.other': { en: 'Other entities', es: 'Otras entidades' },

  // K-03
  'spaces.openLink': { en: 'Open link', es: 'Abrir enlace' },
  'spaces.pin': { en: 'Pin', es: 'Fijar' },
  'spaces.unpin': { en: 'Unpin', es: 'Desfijar' },
  'spaces.pinned': { en: 'Pinned to the top of every space it is filed in', es: 'Fijada arriba en todos los espacios donde está archivada' },
  'spaces.unpinned': { en: 'Unpinned', es: 'Ya no está fijada' },
  'spaces.status': { en: 'Status', es: 'Estado' },
  'spaces.statusSet': { en: 'Post is now {status}', es: 'La publicación ahora está: {status}' },
  'spaces.updatedAt': { en: 'Updated {date}', es: 'Actualizado {date}' },
  'spaces.tags': { en: 'Tags', es: 'Etiquetas' },
  'spaces.noBody': { en: 'This post has no body yet.', es: 'Esta publicación no tiene contenido todavía.' },
  'spaces.filedIn': { en: 'Filed in', es: 'Archivado en' },
  'spaces.fileIn': { en: 'File in…', es: 'Archivar en…' },
  'spaces.fileInTitle': { en: 'File "{post}" in spaces', es: 'Archivar "{post}" en espacios' },
  'spaces.filed': { en: 'Filed in {space}', es: 'Archivado en {space}' },
  'spaces.unfiled': { en: 'Removed from that space; the post stays in the others', es: 'Quitado de ese espacio; la publicación sigue en los demás' },
  'spaces.unfileFrom': { en: 'Remove from {space}', es: 'Quitar de {space}' },
  'spaces.lastFiling': { en: 'A post must stay in at least one space; file it elsewhere first.', es: 'Una publicación debe estar en al menos un espacio; archívala en otro primero.' },
  'spaces.filedHint': { en: 'One post, many spaces: editing it here updates it everywhere.', es: 'Una publicación, muchos espacios: editarla aquí la actualiza en todos.' },
  'spaces.relations': { en: 'Relations', es: 'Relaciones' },
  'spaces.noRelations': { en: 'No relations yet.', es: 'Sin relaciones todavía.' },
  'spaces.addRelation': { en: 'Add relation', es: 'Añadir relación' },
  'spaces.removeRelation': { en: 'Remove relation', es: 'Quitar relación' },
  'spaces.related': { en: 'Relation added', es: 'Relación añadida' },
  'spaces.unrelated': { en: 'Relation removed', es: 'Relación quitada' },
  'spaces.rel.type': { en: 'Relate to a…', es: 'Relacionar con…' },
  'spaces.rel.target': { en: 'Find the target', es: 'Buscar el destino' },
  'spaces.rel.targetPlaceholder': { en: 'Type to search…', es: 'Escribe para buscar…' },
  'spaces.rel.results': { en: 'Matches', es: 'Coincidencias' },
  'spaces.rel.noResults': { en: 'No match', es: 'Sin coincidencias' },
  'spaces.rel.kind': { en: 'Relation kind', es: 'Tipo de relación' },
  'spaces.rel.note': { en: 'Note (optional)', es: 'Nota (opcional)' },
  'spaces.referencedBy': { en: 'Referenced by', es: 'Referenciado por' },
  'spaces.noBacklinks': { en: 'Nothing references this post yet.', es: 'Nada referencia esta publicación todavía.' },
  'spaces.comments': { en: 'Comments', es: 'Comentarios' },
  'spaces.noComments': { en: 'No comments yet.', es: 'Sin comentarios todavía.' },
  'spaces.commentLabel': { en: 'Write a comment', es: 'Escribe un comentario' },
  'spaces.comment': { en: 'Comment', es: 'Comentar' },
  'spaces.activity': { en: 'Activity', es: 'Actividad' },
  'spaces.noActivity': { en: 'No changes recorded yet.', es: 'Sin cambios registrados todavía.' },
  'spaces.changed': { en: 'changed {field}:', es: 'cambió {field}:' },
  'spaces.noRoute': { en: 'This entity has no page yet.', es: 'Esta entidad aún no tiene página.' },

  'spaces.relation.references': { en: 'references', es: 'referencia a' },
  'spaces.relation.applies-to': { en: 'applies to', es: 'aplica a' },
  'spaces.relation.part-of': { en: 'part of', es: 'parte de' },
  'spaces.relation.replaces': { en: 'replaces', es: 'reemplaza a' },
  'spaces.relation.depends-on': { en: 'depends on', es: 'depende de' },
  'spaces.relation.belongs-to': { en: 'belongs to', es: 'pertenece a' },
  'spaces.relation.produced-by': { en: 'produced by', es: 'producido por' },
  'spaces.relation.for-client': { en: 'for client', es: 'para el cliente' },
  'spaces.relation.owned-by': { en: 'owned by', es: 'a cargo de' },

  'spaces.type.spaces': { en: 'Space', es: 'Espacio' },
  'spaces.type.posts': { en: 'Post', es: 'Publicación' },
  'spaces.type.projects': { en: 'Project', es: 'Proyecto' },
  'spaces.type.tasks': { en: 'Task', es: 'Tarea' },
  'spaces.type.documents': { en: 'Document', es: 'Documento' },
  'spaces.type.clients': { en: 'Client', es: 'Cliente' },
  'spaces.type.deliverables': { en: 'Deliverable', es: 'Entregable' },
  'spaces.type.tools': { en: 'Tool', es: 'Herramienta' },
  'spaces.type.roles': { en: 'Role', es: 'Rol' },
  'spaces.type.users': { en: 'Person', es: 'Persona' },
  'spaces.type.competitions': { en: 'Competition', es: 'Concurso' },
  'spaces.type.brandAssets': { en: 'Brand asset', es: 'Activo de marca' },
  'spaces.type.presentations': { en: 'Presentation', es: 'Presentación' },

  // K-04
  'spaces.graph': { en: 'Graph', es: 'Grafo' },
  'spaces.graphSubtitle': { en: 'Spaces, posts and relations as one picture: pick a focus, choose how far to look, open anything.', es: 'Espacios, publicaciones y relaciones en una sola imagen: elige un foco, decide hasta dónde mirar, abre cualquier cosa.' },
  'spaces.graphControls': { en: 'Graph controls', es: 'Controles del grafo' },
  'spaces.graphLabel': { en: 'Graph around {focus}', es: 'Grafo alrededor de {focus}' },
  'spaces.focus': { en: 'Focus on', es: 'Foco en' },
  'spaces.depth': { en: 'Depth', es: 'Profundidad' },
  'spaces.depthN': { en: '{n} hops', es: '{n} saltos' },
  'spaces.depthAll': { en: 'Everything', es: 'Todo' },
  'spaces.zoom': { en: 'Zoom', es: 'Zoom' },
  'spaces.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'spaces.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'spaces.zoomFit': { en: 'Fit', es: 'Ajustar' },
  'spaces.filterKinds': { en: 'Node kinds', es: 'Tipos de nodo' },
  'spaces.toggleKind': { en: 'Show or hide {kind}', es: 'Mostrar u ocultar {kind}' },
  'spaces.graphEmpty': { en: 'Nothing to draw with these filters.', es: 'Nada que dibujar con estos filtros.' },
  'spaces.graphEmptyHint': { en: 'Turn a kind back on or choose another focus.', es: 'Vuelve a activar un tipo o elige otro foco.' },
  'spaces.legend': { en: 'Legend', es: 'Leyenda' },
  'spaces.nodes': { en: '{n} nodes', es: '{n} nodos' },
  'spaces.edges': { en: '{n} links', es: '{n} enlaces' },
  'spaces.edge.child': { en: 'inside (tree)', es: 'dentro de (árbol)' },
  'spaces.edge.filed': { en: 'filed in', es: 'archivado en' },
  'spaces.edge.relation': { en: 'relation (arrow)', es: 'relación (flecha)' },
  'spaces.graphKeys': { en: 'Keyboard: Tab to a node, Enter opens, Space centres, arrows walk neighbours, Home returns to the focus.', es: 'Teclado: Tab hasta un nodo, Enter abre, Espacio centra, flechas recorren vecinos, Inicio vuelve al foco.' },

  // K-05
  'spaces.catalog': { en: 'Catalog', es: 'Catálogo' },
  'spaces.catalogSubtitle': { en: 'The catalogs behind the spaces, as data: deliverable types, clients, tools and roles.', es: 'Los catálogos detrás de los espacios, como datos: tipos de entregable, clientes, herramientas y roles.' },
  'spaces.deliverables': { en: 'Deliverables', es: 'Entregables' },
  'spaces.deliverablesHint': { en: 'Deliverable types per phase with their owner and how ready the template is. "Open page" links to the hub page that produces it today; the rest are placeholders until a template exists.', es: 'Tipos de entregable por fase con su responsable y qué tan lista está la plantilla. "Abrir página" lleva a la página del Hub que lo produce hoy; el resto son pendientes hasta que exista una plantilla.' },
  'spaces.clients': { en: 'Clients', es: 'Clientes' },
  'spaces.clientsHint': { en: 'Past, current and prospective clients with their projects. Unknown facts are marked unknown, never guessed.', es: 'Clientes anteriores, actuales y prospectos con sus proyectos. Lo desconocido se marca como desconocido, nunca se inventa.' },
  'spaces.tools': { en: 'Tools', es: 'Herramientas' },
  'spaces.toolsHint': { en: 'Software the studio pays for or plans to, and which hub module replaces it.', es: 'Software que el estudio paga o planea, y qué módulo del Hub lo reemplaza.' },
  'spaces.dependencyMap': { en: 'Dependency map', es: 'Mapa de dependencias' },
  'spaces.roles': { en: 'Roles', es: 'Roles' },
  'spaces.rolesHint': { en: 'The seven roles of the system with their portal, permissions, demo user and role space.', es: 'Los siete roles del sistema con su portal, permisos, usuario demo y espacio de rol.' },
  'spaces.unknown': { en: 'unknown', es: 'desconocido' },
  'spaces.cat.name': { en: 'Name', es: 'Nombre' },
  'spaces.cat.phase': { en: 'Phase', es: 'Fase' },
  'spaces.cat.owner': { en: 'Owner', es: 'Responsable' },
  'spaces.cat.typicalDays': { en: 'Typical days', es: 'Días típicos' },
  'spaces.cat.status': { en: 'Status', es: 'Estado' },
  'spaces.cat.template': { en: 'Template', es: 'Plantilla' },
  'spaces.cat.openPage': { en: 'Open {code}', es: 'Abrir {code}' },
  'spaces.cat.openTemplate': { en: 'Open template', es: 'Abrir plantilla' },
  'spaces.cat.templateWhat': { en: 'open the document template for {name}', es: 'abrir la plantilla del documento {name}' },
  'spaces.cat.kind': { en: 'Kind', es: 'Tipo' },
  'spaces.cat.sector': { en: 'Sector', es: 'Sector' },
  'spaces.cat.city': { en: 'City', es: 'Ciudad' },
  'spaces.cat.contact': { en: 'Contact', es: 'Contacto' },
  'spaces.cat.projects': { en: 'Projects', es: 'Proyectos' },
  'spaces.cat.space': { en: 'Space', es: 'Espacio' },
  'spaces.cat.vendor': { en: 'Vendor', es: 'Proveedor' },
  'spaces.cat.category': { en: 'Category', es: 'Categoría' },
  'spaces.cat.usedFor': { en: 'Used for', es: 'Se usa para' },
  'spaces.cat.replacedBy': { en: 'Replaced by', es: 'Reemplazado por' },
  'spaces.cat.noReplacement': { en: 'no replacement planned', es: 'sin reemplazo planeado' },
  'spaces.cat.notes': { en: 'Notes', es: 'Notas' },
  'spaces.cat.role': { en: 'Role', es: 'Rol' },
  'spaces.cat.portal': { en: 'Portal', es: 'Portal' },
  'spaces.cat.dashboard': { en: 'Dashboard', es: 'Panel' },
  'spaces.cat.permissions': { en: 'Permissions', es: 'Permisos' },
  'spaces.cat.allPermissions': { en: 'all', es: 'todos' },
  'spaces.cat.demoUser': { en: 'Demo user', es: 'Usuario demo' },

  'spaces.phase.lead': { en: 'Lead', es: 'Prospecto' },
  'spaces.phase.concept': { en: 'Concept', es: 'Concepto' },
  'spaces.phase.development': { en: 'Development', es: 'Desarrollo' },
  'spaces.phase.documentation': { en: 'Documentation', es: 'Documentación' },
  'spaces.phase.procurement': { en: 'Procurement', es: 'Compras' },
  'spaces.phase.execution': { en: 'Execution', es: 'Obra' },
  'spaces.phase.delivered': { en: 'Delivered', es: 'Entrega' },

  'spaces.toolCategory.ai-image': { en: 'AI image', es: 'IA imagen' },
  'spaces.toolCategory.ai-text': { en: 'AI text', es: 'IA texto' },
  'spaces.toolCategory.pm': { en: 'Project management', es: 'Gestión de proyectos' },
  'spaces.toolCategory.chat': { en: 'Chat', es: 'Chat' },
  'spaces.toolCategory.website-builder': { en: 'Website builder', es: 'Constructor web' },
  'spaces.toolCategory.design': { en: 'Design', es: 'Diseño' },
  'spaces.toolCategory.render': { en: 'Render', es: 'Render' },
  'spaces.toolCategory.finance': { en: 'Finance', es: 'Finanzas' },
  'spaces.toolCategory.comms': { en: 'Communications', es: 'Comunicaciones' },
  'spaces.toolCategory.infra': { en: 'Infrastructure', es: 'Infraestructura' },

  // K-06
  'spaces.import': { en: 'Import from Slack', es: 'Importar desde Slack' },
  'spaces.importSubtitle': { en: 'Where the Slack export will land. The sidebar Justin built is already the space tree; the messages come with the export.', es: 'Donde aterrizará la exportación de Slack. La barra lateral que armó Justin ya es el árbol de espacios; los mensajes llegan con la exportación.' },
  'spaces.import.uploadTitle': { en: 'Slack export', es: 'Exportación de Slack' },
  'spaces.import.uploadSubtitle': { en: 'Workspace settings → Import / export data → Export (.zip)', es: 'Ajustes del espacio de trabajo → Importar / exportar datos → Exportar (.zip)' },
  'spaces.import.upload': { en: 'Upload Slack export', es: 'Subir exportación de Slack' },
  'spaces.import.uploadWhat': { en: 'read the Slack export and create posts, comments and relations from it', es: 'leer la exportación de Slack y crear publicaciones, comentarios y relaciones a partir de ella' },
  'spaces.import.readOnly': { en: 'This page is read-only today: it shows the mapping and the contract. Nothing here re-seeds or deletes.', es: 'Esta página es solo lectura hoy: muestra el mapeo y el contrato. Nada aquí re-siembra ni borra.' },
  'spaces.import.checklistTitle': { en: 'What a real import does', es: 'Qué hace una importación real' },
  'spaces.import.checklistSubtitle': { en: 'The contract for the import script (D-027)', es: 'El contrato del script de importación (D-027)' },
  'spaces.import.check.channels.from': { en: 'Channels', es: 'Canales' },
  'spaces.import.check.channels.to': { en: 'spaces (existing ones by slug, new ones under their section area)', es: 'espacios (los existentes por slug, los nuevos bajo el área de su sección)' },
  'spaces.import.check.messages.from': { en: 'Messages', es: 'Mensajes' },
  'spaces.import.check.messages.to': { en: 'posts filed in the channel\'s space (kind note, or link / file when they carry one)', es: 'publicaciones archivadas en el espacio del canal (tipo nota, o enlace / archivo cuando lo traen)' },
  'spaces.import.check.threads.from': { en: 'Thread replies', es: 'Respuestas en hilo' },
  'spaces.import.check.threads.to': { en: 'comments on the post', es: 'comentarios en la publicación' },
  'spaces.import.check.pins.from': { en: 'Pinned messages', es: 'Mensajes fijados' },
  'spaces.import.check.pins.to': { en: 'pinned posts', es: 'publicaciones fijadas' },
  'spaces.import.check.mentions.from': { en: 'Mentions of people, channels and links', es: 'Menciones de personas, canales y enlaces' },
  'spaces.import.check.mentions.to': { en: 'relations (references, applies-to a role) and extra filings', es: 'relaciones (referencia, aplica a un rol) y archivados adicionales' },
  'spaces.import.check.files.from': { en: 'Files', es: 'Archivos' },
  'spaces.import.check.files.to': { en: 'file posts (storage arrives with Supabase)', es: 'publicaciones de archivo (el almacenamiento llega con Supabase)' },
  'spaces.import.check.users.from': { en: 'Users', es: 'Usuarios' },
  'spaces.import.check.users.to': { en: 'demo users by role today, real accounts later', es: 'usuarios demo por rol hoy, cuentas reales después' },
  'spaces.import.check.sections.from': { en: 'Sidebar sections', es: 'Secciones de la barra lateral' },
  'spaces.import.check.sections.to': { en: 'top-level areas (already seeded)', es: 'áreas de nivel superior (ya sembradas)' },
  'spaces.import.mappingTitle': { en: 'Slack sidebar → spaces', es: 'Barra lateral de Slack → espacios' },
  'spaces.import.mappingHint': { en: 'Transcribed from the two sidebar screenshots (2026-09-21). Every section became an area and every channel a space inside it.', es: 'Transcrito de las dos capturas de la barra lateral (2026-09-21). Cada sección se volvió un área y cada canal un espacio dentro de ella.' },
  'spaces.import.section': { en: 'Slack section', es: 'Sección de Slack' },
  'spaces.import.channel': { en: 'Channel', es: 'Canal' },
  'spaces.import.sectionRow': { en: '(section)', es: '(sección)' },
  'spaces.import.space': { en: 'Space', es: 'Espacio' },
  'spaces.import.unmapped': { en: 'Unmapped', es: 'Sin mapear' },
  'spaces.import.postsToday': { en: 'Posts today', es: 'Publicaciones hoy' },
};
