import type { StringTable } from '../../i18n/types';

/**
 * Operations portal (O-01..O-10, Miguel). Keys are namespaced `ops.<page>.<key>`;
 * Spanish is complete because the studio works in Spanish (D-004, P-13).
 */
export const strings: StringTable = {
  // nav
  'ops.nav.home': { en: 'Dashboard', es: 'Panel' },
  'ops.nav.tasks': { en: 'Tasks', es: 'Tareas' },
  'ops.nav.schedule': { en: 'Schedule', es: 'Cronograma' },
  'ops.nav.alerts': { en: 'Alerts', es: 'Alertas' },
  'ops.nav.suppliers': { en: 'Suppliers', es: 'Proveedores' },
  'ops.nav.quotes': { en: 'Quotes', es: 'Cotizaciones' },
  'ops.nav.deliveries': { en: 'Deliveries', es: 'Entregas' },
  'ops.nav.payments': { en: 'Payments', es: 'Pagos' },
  'ops.nav.documents': { en: 'Documents', es: 'Documentos' },
  'ops.nav.reports': { en: 'Reports', es: 'Informes' },

  // shared
  'ops.common.project': { en: 'Project', es: 'Proyecto' },
  'ops.common.allProjects': { en: 'All projects', es: 'Todos los proyectos' },
  'ops.common.internal': { en: 'Studio (no project)', es: 'Estudio (sin proyecto)' },
  'ops.common.supplier': { en: 'Supplier', es: 'Proveedor' },
  'ops.common.allSuppliers': { en: 'All suppliers', es: 'Todos los proveedores' },
  'ops.common.status': { en: 'Status', es: 'Estado' },
  'ops.common.allStatuses': { en: 'All statuses', es: 'Todos los estados' },
  'ops.common.item': { en: 'Item', es: 'Ítem' },
  'ops.common.amount': { en: 'Amount', es: 'Monto' },
  'ops.common.due': { en: 'Due', es: 'Vence' },
  'ops.common.owner': { en: 'Owner', es: 'Responsable' },
  'ops.common.notes': { en: 'Notes', es: 'Notas' },
  'ops.common.open': { en: 'Open', es: 'Abrir' },
  'ops.common.close': { en: 'Close', es: 'Cerrar' },
  'ops.common.seeAll': { en: 'See all', es: 'Ver todo' },
  'ops.common.count': { en: '{n} of {total}', es: '{n} de {total}' },
  'ops.common.noDate': { en: 'No date', es: 'Sin fecha' },
  'ops.common.dueToday': { en: 'Due today', es: 'Vence hoy' },
  'ops.common.inDays': { en: 'in {n} days', es: 'en {n} días' },
  'ops.common.overdueBy': { en: '{n} days overdue', es: 'vencido hace {n} días' },
  'ops.common.saved': { en: 'Saved', es: 'Guardado' },
  'ops.common.detail': { en: 'Detail', es: 'Detalle' },
  'ops.common.empty': { en: 'Nothing here yet', es: 'Aún no hay nada aquí' },
  'ops.common.role': { en: 'Team role', es: 'Rol del equipo' },
  'ops.common.mine': { en: 'Only mine (Miguel)', es: 'Solo lo mío (Miguel)' },
  'ops.common.openInWork': { en: 'Open in Work', es: 'Abrir en Trabajo' },

  // O-01 dashboard
  'ops.home.title': { en: 'Operations dashboard', es: 'Panel de operaciones' },
  'ops.home.desc': { en: 'Schedule, pending tasks, meetings, suppliers, quotes and comparisons, deliveries, payments and alerts before they become urgent.', es: 'Cronograma, tareas pendientes, reuniones, proveedores, cotizaciones y comparativos, entregas, pagos y alertas antes de que sean urgentes.' },
  'ops.home.section.schedule': { en: 'Overall project schedule', es: 'Cronograma general de proyectos' },
  'ops.home.section.tasks': { en: 'Pending tasks', es: 'Tareas pendientes' },
  'ops.home.section.meetings': { en: 'Meetings and commitments', es: 'Reuniones y compromisos' },
  'ops.home.section.suppliers': { en: 'Suppliers and follow-ups', es: 'Proveedores y seguimiento' },
  'ops.home.section.quotes': { en: 'Price quotes and comparisons', es: 'Cotizaciones y comparativos' },
  'ops.home.section.deliveries': { en: 'Deliveries and dates', es: 'Entregas y fechas' },
  'ops.home.section.payments': { en: 'Payments, accounts and who owes what', es: 'Pagos, cuentas y quién debe qué' },
  'ops.home.section.alerts': { en: 'Alerts before urgent', es: 'Alertas antes de lo urgente' },
  'ops.home.tile.tasks': { en: 'Pending tasks', es: 'Tareas pendientes' },
  'ops.home.tile.tasksHint': { en: '{n} high or urgent', es: '{n} altas o urgentes' },
  'ops.home.tile.alerts': { en: 'Open alerts', es: 'Alertas abiertas' },
  'ops.home.tile.alertsHint': { en: '{n} urgent', es: '{n} urgentes' },
  'ops.home.tile.deliveries': { en: 'Deliveries in 14 days', es: 'Entregas en 14 días' },
  'ops.home.tile.deliveriesHint': { en: '{n} still unconfirmed', es: '{n} sin confirmar' },
  'ops.home.tile.in': { en: 'Clients owe us', es: 'Los clientes nos deben' },
  'ops.home.tile.inHint': { en: '{n} overdue', es: '{n} vencidos' },
  'ops.home.tile.out': { en: 'We owe suppliers', es: 'Debemos a proveedores' },
  'ops.home.tile.outHint': { en: 'next due {date}', es: 'próximo vence {date}' },
  'ops.home.agenda': { en: 'Next meetings and commitments', es: 'Próximas reuniones y compromisos' },
  'ops.home.agenda.when': { en: 'When', es: 'Cuándo' },
  'ops.home.agenda.what': { en: 'Meeting', es: 'Reunión' },
  'ops.home.agenda.where': { en: 'Where', es: 'Dónde' },
  'ops.home.agenda.empty': { en: 'No meetings ahead', es: 'No hay reuniones próximas' },
  'ops.home.tasks': { en: 'Pending tasks', es: 'Tareas pendientes' },
  'ops.home.tasks.empty': { en: 'Nothing pending', es: 'Nada pendiente' },
  'ops.home.alerts': { en: 'Before it becomes urgent', es: 'Antes de que sea urgente' },
  'ops.home.alerts.empty': { en: 'No open alerts', es: 'Sin alertas abiertas' },
  'ops.home.deliveries': { en: 'Deliveries this fortnight', es: 'Entregas de la quincena' },
  'ops.home.deliveries.empty': { en: 'No deliveries expected', es: 'No se esperan entregas' },
  'ops.home.money': { en: 'Money due in and out', es: 'Dinero por cobrar y por pagar' },
  'ops.home.money.empty': { en: 'Nothing outstanding', es: 'Nada pendiente de pago' },
  'ops.home.newTask': { en: 'New task', es: 'Nueva tarea' },
  'ops.home.newTaskWhat': { en: 'create a task from the dashboard', es: 'crear una tarea desde el panel' },

  // O-02 schedule
  'ops.schedule.title': { en: 'Project schedule', es: 'Cronograma de proyectos' },
  'ops.schedule.subtitle': { en: 'Every task on one timeline with its dependencies, and a calendar of meetings, deliveries and payment dates.', es: 'Todas las tareas en una línea de tiempo con sus dependencias, y un calendario de reuniones, entregas y fechas de pago.' },
  'ops.schedule.tab.timeline': { en: 'Timeline', es: 'Línea de tiempo' },
  'ops.schedule.tab.calendar': { en: 'Calendar', es: 'Calendario' },
  'ops.schedule.timelineLabel': { en: 'Task timeline', es: 'Línea de tiempo de tareas' },
  'ops.schedule.calendarLabel': { en: 'Commitments calendar', es: 'Calendario de compromisos' },
  'ops.schedule.timelineNote': { en: 'Each bar runs from when the task opened (or when the task it depends on is due) to its own due date.', es: 'Cada barra va desde que se abrió la tarea (o desde el vencimiento de la tarea de la que depende) hasta su propia fecha de entrega.' },
  'ops.schedule.legend': { en: 'Calendar shows meetings, expected deliveries and payment due dates.', es: 'El calendario muestra reuniones, entregas previstas y fechas de pago.' },
  'ops.schedule.kind.meeting': { en: 'Meeting', es: 'Reunión' },
  'ops.schedule.kind.delivery': { en: 'Delivery', es: 'Entrega' },
  'ops.schedule.kind.payment': { en: 'Payment', es: 'Pago' },
  'ops.schedule.newMeeting': { en: 'Schedule a meeting', es: 'Agendar reunión' },
  'ops.schedule.newMeetingWhat': { en: 'create a meeting and invite the team', es: 'crear una reunión e invitar al equipo' },
  'ops.schedule.noTasks': { en: 'No tasks with dates', es: 'No hay tareas con fechas' },

  // O-03 tasks
  'ops.tasks.title': { en: 'Pending tasks', es: 'Tareas pendientes' },
  'ops.tasks.subtitle': { en: 'Everything the studio owes, by state. Moving a card writes the task status.', es: 'Todo lo que el estudio tiene pendiente, por estado. Mover una tarjeta guarda el estado de la tarea.' },
  'ops.tasks.board': { en: 'Task board', es: 'Tablero de tareas' },
  'ops.tasks.col.todo': { en: 'To do', es: 'Por hacer' },
  'ops.tasks.col.doing': { en: 'Doing', es: 'En curso' },
  'ops.tasks.col.blocked': { en: 'Blocked', es: 'Bloqueado' },
  'ops.tasks.col.done': { en: 'Done', es: 'Hecho' },
  'ops.tasks.col.title': { en: 'Task', es: 'Tarea' },
  'ops.tasks.priority': { en: 'Priority', es: 'Prioridad' },
  'ops.tasks.dependsOn': { en: 'Waits for', es: 'Espera a' },
  'ops.tasks.assignee': { en: 'Assignee', es: 'Asignada a' },
  'ops.tasks.complete': { en: 'Mark done', es: 'Marcar como hecha' },
  'ops.tasks.moved': { en: 'Task moved', es: 'Tarea movida' },
  'ops.tasks.new': { en: 'New task', es: 'Nueva tarea' },
  'ops.tasks.newWhat': { en: 'create a task with owner, project and due date', es: 'crear una tarea con responsable, proyecto y fecha' },
  'ops.tasks.searchPlaceholder': { en: 'Search tasks…', es: 'Buscar tareas…' },

  // O-04 suppliers
  'ops.suppliers.title': { en: 'Suppliers and follow-ups', es: 'Proveedores y seguimiento' },
  'ops.suppliers.subtitle': { en: 'Who we buy from, how long they take, and what is open with each of them right now.', es: 'A quién le compramos, cuánto se demora y qué está abierto con cada uno ahora mismo.' },
  'ops.suppliers.table': { en: 'Suppliers', es: 'Proveedores' },
  'ops.suppliers.col.name': { en: 'Supplier', es: 'Proveedor' },
  'ops.suppliers.col.category': { en: 'Category', es: 'Categoría' },
  'ops.suppliers.col.contact': { en: 'Contact', es: 'Contacto' },
  'ops.suppliers.col.city': { en: 'City', es: 'Ciudad' },
  'ops.suppliers.col.lead': { en: 'Lead time (days)', es: 'Tiempo de entrega (días)' },
  'ops.suppliers.col.rating': { en: 'Rating', es: 'Calificación' },
  'ops.suppliers.openQuotes': { en: 'Open quotes', es: 'Cotizaciones abiertas' },
  'ops.suppliers.openDeliveries': { en: 'Pending deliveries', es: 'Entregas pendientes' },
  'ops.suppliers.owed': { en: 'We owe them', es: 'Les debemos' },
  'ops.suppliers.pause': { en: 'Pause supplier', es: 'Pausar proveedor' },
  'ops.suppliers.activate': { en: 'Activate supplier', es: 'Activar proveedor' },
  'ops.suppliers.followUp': { en: 'Follow-up note', es: 'Nota de seguimiento' },
  'ops.suppliers.followUpHint': { en: 'What you asked for, what they promised and when to chase again.', es: 'Qué pediste, qué prometieron y cuándo volver a insistir.' },
  'ops.suppliers.saveNote': { en: 'Save follow-up note', es: 'Guardar nota de seguimiento' },
  'ops.suppliers.saveNoteWhat': { en: 'save a dated follow-up note on the supplier', es: 'guardar una nota de seguimiento con fecha en el proveedor' },
  'ops.suppliers.add': { en: 'Add supplier', es: 'Agregar proveedor' },
  'ops.suppliers.addWhat': { en: 'add a supplier with contact and category', es: 'agregar un proveedor con contacto y categoría' },
  'ops.suppliers.category': { en: 'Category', es: 'Categoría' },
  'ops.suppliers.allCategories': { en: 'All categories', es: 'Todas las categorías' },
  'ops.suppliers.searchPlaceholder': { en: 'Search suppliers…', es: 'Buscar proveedores…' },
  'ops.suppliers.statusSaved': { en: 'Supplier status updated', es: 'Estado del proveedor actualizado' },

  // O-05 quotes
  'ops.quotes.title': { en: 'Quotes and comparisons', es: 'Cotizaciones y comparativos' },
  'ops.quotes.subtitle': { en: 'Requested prices side by side per comparison group: best price and shortest lead time are marked.', es: 'Precios solicitados lado a lado por comparativo: se marcan el mejor precio y el menor tiempo de entrega.' },
  'ops.quotes.group': { en: 'Comparison', es: 'Comparativo' },
  'ops.quotes.col.supplier': { en: 'Supplier', es: 'Proveedor' },
  'ops.quotes.col.item': { en: 'Item', es: 'Ítem' },
  'ops.quotes.col.amount': { en: 'Price', es: 'Precio' },
  'ops.quotes.col.lead': { en: 'Lead time (days)', es: 'Tiempo de entrega (días)' },
  'ops.quotes.col.valid': { en: 'Valid until', es: 'Válida hasta' },
  'ops.quotes.best': { en: 'Best price', es: 'Mejor precio' },
  'ops.quotes.fastest': { en: 'Fastest', es: 'Más rápida' },
  'ops.quotes.select': { en: 'Select', es: 'Seleccionar' },
  'ops.quotes.shortlist': { en: 'Shortlist', es: 'Preseleccionar' },
  'ops.quotes.selected': { en: 'Quote selected; the rest of the comparison was rejected', es: 'Cotización seleccionada; el resto del comparativo quedó rechazado' },
  'ops.quotes.request': { en: 'Request quote', es: 'Solicitar cotización' },
  'ops.quotes.requestWhat': { en: 'request a quote from a supplier for an item', es: 'solicitar una cotización a un proveedor por un ítem' },
  'ops.quotes.spread': { en: 'Spread {amount} between {n} quotes', es: 'Diferencia de {amount} entre {n} cotizaciones' },
  'ops.quotes.empty': { en: 'No quotes yet', es: 'Aún no hay cotizaciones' },

  // O-06 deliveries
  'ops.deliveries.title': { en: 'Deliveries and dates', es: 'Entregas y fechas' },
  'ops.deliveries.subtitle': { en: 'Confirm what each supplier is sending and when it actually arrives.', es: 'Confirma qué envía cada proveedor y cuándo llega realmente.' },
  'ops.deliveries.table': { en: 'Deliveries', es: 'Entregas' },
  'ops.deliveries.col.expected': { en: 'Expected', es: 'Prevista' },
  'ops.deliveries.col.confirmed': { en: 'Confirmed', es: 'Confirmada' },
  'ops.deliveries.confirm': { en: 'Confirm date', es: 'Confirmar fecha' },
  'ops.deliveries.confirmTitle': { en: 'Confirm delivery date', es: 'Confirmar fecha de entrega' },
  'ops.deliveries.confirmedDate': { en: 'Date the supplier confirmed', es: 'Fecha confirmada por el proveedor' },
  'ops.deliveries.confirmSave': { en: 'Save confirmation', es: 'Guardar confirmación' },
  'ops.deliveries.confirmed': { en: 'Delivery confirmed', es: 'Entrega confirmada' },
  'ops.deliveries.received': { en: 'Mark received', es: 'Marcar recibida' },
  'ops.deliveries.delay': { en: 'Flag as delayed', es: 'Marcar como retrasada' },
  'ops.deliveries.empty': { en: 'No deliveries', es: 'Sin entregas' },

  // O-07 payments
  'ops.payments.title': { en: 'Payments and accounts', es: 'Pagos y cuentas' },
  'ops.payments.subtitle': { en: 'Who owes what, by when, and what is already overdue.', es: 'Quién debe qué, para cuándo, y qué ya está vencido.' },
  'ops.payments.tile.in': { en: 'Clients owe us', es: 'Los clientes nos deben' },
  'ops.payments.tile.out': { en: 'We owe suppliers', es: 'Debemos a proveedores' },
  'ops.payments.tile.overdue': { en: 'Overdue', es: 'Vencido' },
  'ops.payments.tile.balance': { en: 'Net balance', es: 'Balance neto' },
  'ops.payments.overdueList': { en: 'Overdue right now', es: 'Vencidos ahora mismo' },
  'ops.payments.table': { en: 'Payments', es: 'Pagos' },
  'ops.payments.col.counterparty': { en: 'Who', es: 'Quién' },
  'ops.payments.col.concept': { en: 'Concept', es: 'Concepto' },
  'ops.payments.col.direction': { en: 'Direction', es: 'Sentido' },
  'ops.payments.col.outstanding': { en: 'Outstanding', es: 'Saldo' },
  'ops.payments.direction.in': { en: 'They owe us', es: 'Nos deben' },
  'ops.payments.direction.out': { en: 'We owe', es: 'Debemos' },
  'ops.payments.allDirections': { en: 'In and out', es: 'Por cobrar y por pagar' },
  'ops.payments.markPaid': { en: 'Mark paid', es: 'Marcar pagado' },
  'ops.payments.paid': { en: 'Payment settled', es: 'Pago saldado' },
  'ops.payments.registerPart': { en: 'Register part payment', es: 'Registrar abono' },
  'ops.payments.registerTitle': { en: 'Register a part payment', es: 'Registrar un abono' },
  'ops.payments.partAmount': { en: 'Amount received or paid', es: 'Monto recibido o pagado' },
  'ops.payments.registerSave': { en: 'Register', es: 'Registrar' },
  'ops.payments.registered': { en: 'Part payment registered', es: 'Abono registrado' },
  'ops.payments.empty': { en: 'No payments', es: 'Sin pagos' },
  'ops.payments.noneOverdue': { en: 'Nothing overdue', es: 'Nada vencido' },

  // O-08 documents
  'ops.documents.title': { en: 'Administrative documents', es: 'Documentos administrativos' },
  'ops.documents.subtitle': { en: 'Contracts, invoices, quotes and reports with their version and state.', es: 'Contratos, facturas, cotizaciones e informes con su versión y estado.' },
  'ops.documents.table': { en: 'Documents', es: 'Documentos' },
  'ops.documents.col.title': { en: 'Document', es: 'Documento' },
  'ops.documents.col.kind': { en: 'Kind', es: 'Tipo' },
  'ops.documents.col.version': { en: 'Version', es: 'Versión' },
  'ops.documents.kind': { en: 'Kind', es: 'Tipo' },
  'ops.documents.allKinds': { en: 'All kinds', es: 'Todos los tipos' },
  'ops.documents.advance': { en: 'Advance status', es: 'Avanzar estado' },
  'ops.documents.advanced': { en: 'Document status updated', es: 'Estado del documento actualizado' },
  'ops.documents.openFile': { en: 'Open file', es: 'Abrir archivo' },
  'ops.documents.openFileWhat': { en: 'open the stored file of this document', es: 'abrir el archivo guardado de este documento' },
  'ops.documents.upload': { en: 'Upload document', es: 'Subir documento' },
  'ops.documents.uploadWhat': { en: 'upload a file and file it under a project', es: 'subir un archivo y archivarlo en un proyecto' },
  'ops.documents.searchPlaceholder': { en: 'Search documents…', es: 'Buscar documentos…' },
  'ops.documents.kind.contract': { en: 'Contract', es: 'Contrato' },
  'ops.documents.kind.invoice': { en: 'Invoice', es: 'Factura' },
  'ops.documents.kind.plan': { en: 'Plan', es: 'Plano' },
  'ops.documents.kind.project-pdf': { en: 'Project PDF', es: 'PDF de proyecto' },
  'ops.documents.kind.report': { en: 'Report', es: 'Informe' },
  'ops.documents.kind.spec': { en: 'Spec', es: 'Especificación' },
  'ops.documents.kind.brief': { en: 'Brief', es: 'Brief' },
  'ops.documents.kind.quote': { en: 'Quote', es: 'Cotización' },

  // O-09 alerts
  'ops.alerts.title': { en: 'Alerts before urgent', es: 'Alertas antes de lo urgente' },
  'ops.alerts.subtitle': { en: 'Dated items with a lead time, so the founder hears about them before they burn.', es: 'Asuntos con fecha y días de anticipación, para avisar a la fundadora antes de que se quemen.' },
  'ops.alerts.tab.open': { en: 'Open', es: 'Abiertas' },
  'ops.alerts.tab.acknowledged': { en: 'Acknowledged', es: 'Vistas' },
  'ops.alerts.tab.resolved': { en: 'Resolved', es: 'Resueltas' },
  'ops.alerts.col.title': { en: 'Alert', es: 'Alerta' },
  'ops.alerts.severity': { en: 'Severity', es: 'Gravedad' },
  'ops.alerts.lead': { en: 'Warn {n} days ahead', es: 'Avisar {n} días antes' },
  'ops.alerts.about': { en: 'About', es: 'Sobre' },
  'ops.alerts.forRole': { en: 'For', es: 'Para' },
  'ops.alerts.acknowledge': { en: 'Acknowledge', es: 'Marcar vista' },
  'ops.alerts.acknowledged': { en: 'Alert acknowledged', es: 'Alerta marcada como vista' },
  'ops.alerts.resolve': { en: 'Resolve', es: 'Resolver' },
  'ops.alerts.resolved': { en: 'Alert resolved', es: 'Alerta resuelta' },
  'ops.alerts.reopen': { en: 'Reopen', es: 'Reabrir' },
  'ops.alerts.new': { en: 'New alert', es: 'Nueva alerta' },
  'ops.alerts.newWhat': { en: 'create an alert with a date and a lead time', es: 'crear una alerta con fecha y días de anticipación' },
  'ops.alerts.empty': { en: 'No alerts in this state', es: 'Sin alertas en este estado' },
  'ops.alerts.openItem': { en: 'Open the item', es: 'Abrir el asunto' },

  // O-10 reports
  'ops.reports.title': { en: 'Reports', es: 'Informes' },
  'ops.reports.subtitle': { en: 'The monthly numbers Miguel lays out for the founder: money, deliveries and tasks closed.', es: 'Los números del mes que Miguel arma para la fundadora: dinero, entregas y tareas cerradas.' },
  'ops.reports.period': { en: 'Period', es: 'Periodo' },
  'ops.reports.figures': { en: 'Figures for {period}', es: 'Cifras de {period}' },
  'ops.reports.fig.in': { en: 'Collected', es: 'Cobrado' },
  'ops.reports.fig.out': { en: 'Paid out', es: 'Pagado' },
  'ops.reports.fig.pending': { en: 'Still outstanding', es: 'Pendiente' },
  'ops.reports.fig.deliveries': { en: 'Deliveries due', es: 'Entregas previstas' },
  'ops.reports.fig.tasksDone': { en: 'Tasks done', es: 'Tareas hechas' },
  'ops.reports.existing': { en: 'Report documents', es: 'Documentos de informe' },
  'ops.reports.build': { en: 'Format and lay out report', es: 'Formatear y diagramar informe' },
  'ops.reports.buildWhat': { en: 'lay the figures out in the Aluzina report template', es: 'diagramar las cifras en la plantilla de informes de Aluzina' },
  'ops.reports.export': { en: 'Export PDF', es: 'Exportar PDF' },
  'ops.reports.exportWhat': { en: 'export the report as a PDF', es: 'exportar el informe como PDF' },
  'ops.reports.send': { en: 'Send to founder', es: 'Enviar a la fundadora' },
  'ops.reports.sendWhat': { en: 'send the report to the founder for review', es: 'enviar el informe a la fundadora para revisión' },
  'ops.reports.note': { en: 'The figures are live. Layout, export and sending are not wired yet.', es: 'Las cifras son reales. La diagramación, la exportación y el envío aún no están conectados.' },

  // supplier categories
  'ops.suppliers.cat.lighting': { en: 'Lighting', es: 'Iluminación' },
  'ops.suppliers.cat.furniture': { en: 'Furniture', es: 'Mobiliario' },
  'ops.suppliers.cat.stone': { en: 'Stone', es: 'Piedra' },
  'ops.suppliers.cat.wood': { en: 'Wood and joinery', es: 'Madera y ebanistería' },
  'ops.suppliers.cat.textiles': { en: 'Textiles', es: 'Textiles' },
  'ops.suppliers.cat.paint': { en: 'Paint and finishes', es: 'Pintura y acabados' },
  'ops.suppliers.cat.metalwork': { en: 'Metalwork', es: 'Metalmecánica' },
  'ops.suppliers.cat.installation': { en: 'Installation', es: 'Instalación' },
  'ops.suppliers.cat.printing': { en: 'Printing', es: 'Impresión' },

  // task priorities
  'ops.priority.low': { en: 'Low', es: 'Baja' },
  'ops.priority.normal': { en: 'Normal', es: 'Normal' },
  'ops.priority.high': { en: 'High', es: 'Alta' },
  'ops.priority.urgent': { en: 'Urgent', es: 'Urgente' },
};
