import type { StringTable } from '../../i18n/types';

/**
 * Studio portal strings (S-01..S-09). Namespace `studio.`; Spanish is complete because the studio
 * works in Spanish (D-004) and the seeded content is already Spanish.
 */
export const strings: StringTable = {
  // Navigation
  'studio.nav.home': { en: 'Dashboard', es: 'Panel' },
  'studio.nav.projects': { en: 'Projects and proposals', es: 'Proyectos y propuestas' },
  'studio.nav.checks': { en: 'Consistency check', es: 'Chequeo de consistencia' },
  'studio.nav.schedules': { en: 'Schedules', es: 'Cuadros' },
  'studio.nav.references': { en: 'References and mood boards', es: 'Referencias y moodboards' },
  'studio.nav.materials': { en: 'Material palettes', es: 'Paletas de materiales' },
  'studio.nav.plans': { en: 'Plans and documentation', es: 'Planos y documentación' },
  'studio.nav.packs': { en: 'Render and supplier packs', es: 'Paquetes de render y proveedor' },
  'studio.nav.measurements': { en: 'Measurements and requirements', es: 'Medidas y requerimientos' },

  // Shared labels
  'studio.col.project': { en: 'Project', es: 'Proyecto' },
  'studio.col.title': { en: 'Title', es: 'Título' },
  'studio.col.status': { en: 'Status', es: 'Estado' },
  'studio.col.due': { en: 'Due', es: 'Entrega' },
  'studio.col.phase': { en: 'Phase', es: 'Fase' },
  'studio.col.direction': { en: 'Creative direction', es: 'Dirección creativa' },
  'studio.col.approval': { en: 'Approval', es: 'Aprobación' },
  'studio.col.kind': { en: 'Kind', es: 'Tipo' },
  'studio.col.items': { en: 'Items', es: 'Ítems' },
  'studio.col.version': { en: 'Version', es: 'Versión' },
  'studio.col.owner': { en: 'Owner', es: 'Responsable' },
  'studio.col.tags': { en: 'Tags', es: 'Etiquetas' },
  'studio.col.board': { en: 'Board', es: 'Tablero' },
  'studio.col.palette': { en: 'Palette', es: 'Paleta' },
  'studio.col.source': { en: 'Source', es: 'Fuente' },
  'studio.col.category': { en: 'Category', es: 'Categoría' },
  'studio.col.finish': { en: 'Finish', es: 'Acabado' },
  'studio.col.colour': { en: 'Colour', es: 'Color' },
  'studio.col.unit': { en: 'Unit price', es: 'Precio unitario' },
  'studio.col.supplier': { en: 'Supplier', es: 'Proveedor' },
  'studio.col.audience': { en: 'Audience', es: 'Destinatario' },
  'studio.col.views': { en: 'Views', es: 'Vistas' },
  'studio.col.location': { en: 'Location', es: 'Ubicación' },
  'studio.col.client': { en: 'Client', es: 'Cliente' },
  'studio.col.budget': { en: 'Budget', es: 'Presupuesto' },
  'studio.col.assignee': { en: 'Assignee', es: 'Responsable' },
  'studio.col.priority': { en: 'Priority', es: 'Prioridad' },
  'studio.col.note': { en: 'Note', es: 'Nota' },
  'studio.col.updated': { en: 'Last change', es: 'Último cambio' },
  'studio.filter.allProjects': { en: 'All projects', es: 'Todos los proyectos' },
  'studio.filter.allStatuses': { en: 'All statuses', es: 'Todos los estados' },
  'studio.filter.allTags': { en: 'All tags', es: 'Todas las etiquetas' },
  'studio.filter.allPhases': { en: 'All phases', es: 'Todas las fases' },
  'studio.filter.summary': { en: '{shown} of {total}', es: '{shown} de {total}' },
  'studio.saved': { en: 'Saved', es: 'Guardado' },
  'studio.noProject': { en: 'No project', es: 'Sin proyecto' },
  'studio.empty.title': { en: 'Nothing here yet', es: 'Aún no hay nada aquí' },
  'studio.empty.desc': { en: 'Nothing matches the current filters.', es: 'Nada coincide con los filtros actuales.' },

  // Vocabulary the core status table does not cover
  'studio.phase.lead': { en: 'Lead', es: 'Prospecto' },
  'studio.phase.concept': { en: 'Concept', es: 'Concepto' },
  'studio.phase.development': { en: 'Development', es: 'Desarrollo' },
  'studio.phase.documentation': { en: 'Documentation', es: 'Documentación' },
  'studio.phase.procurement': { en: 'Procurement', es: 'Compras' },
  'studio.phase.execution': { en: 'Execution', es: 'Obra' },
  'studio.phase.delivered': { en: 'Delivered', es: 'Entregado' },
  'studio.direction.pending': { en: 'Direction pending', es: 'Dirección pendiente' },
  'studio.direction.set': { en: 'Direction set', es: 'Dirección definida' },
  'studio.direction.revised': { en: 'Direction revised', es: 'Dirección revisada' },
  'studio.priority.low': { en: 'Low', es: 'Baja' },
  'studio.priority.normal': { en: 'Normal', es: 'Normal' },
  'studio.priority.high': { en: 'High', es: 'Alta' },
  'studio.priority.urgent': { en: 'Urgent', es: 'Urgente' },
  'studio.docKind.plan': { en: 'Plan', es: 'Plano' },
  'studio.docKind.spec': { en: 'Specification', es: 'Especificación' },

  // S-01 dashboard
  'studio.home.title': { en: 'Studio dashboard', es: 'Panel del estudio' },
  'studio.home.desc': { en: 'Design proposals per project, references, palettes, plans, schedules, render packs and the consistency check before the founder.', es: 'Propuestas de diseño por proyecto, referencias, paletas, planos, cuadros, paquetes de render y el chequeo de consistencia antes de la fundadora.' },
  'studio.home.subtitle': { en: 'What is in development, what needs a check before it reaches Alejandra, and what the studio owes this week.', es: 'Qué está en desarrollo, qué necesita chequeo antes de llegar a Alejandra y qué debe el estudio esta semana.' },
  'studio.home.stat.development': { en: 'Projects in development', es: 'Proyectos en desarrollo' },
  'studio.home.stat.developmentHint': { en: 'development and documentation phases', es: 'fases de desarrollo y documentación' },
  'studio.home.stat.checks': { en: 'Checks to close', es: 'Chequeos por cerrar' },
  'studio.home.stat.checksHint': { en: 'before work reaches the founder', es: 'antes de que el trabajo llegue a la fundadora' },
  'studio.home.stat.tasks': { en: 'Open studio tasks', es: 'Pendientes del estudio' },
  'studio.home.stat.tasksHint': { en: 'to do, doing or blocked', es: 'por hacer, en curso o bloqueados' },
  'studio.home.stat.packs': { en: 'Packs in flight', es: 'Paquetes en curso' },
  'studio.home.stat.packsHint': { en: 'briefing, sent or rendering', es: 'en brief, enviados o renderizando' },
  'studio.home.projects': { en: 'Projects in development', es: 'Proyectos en desarrollo' },
  'studio.home.projectsSub': { en: 'Phase, creative direction from Alejandra, and where the approval stands.', es: 'Fase, dirección creativa de Alejandra y estado de la aprobación.' },
  'studio.home.checks': { en: 'Consistency checks before the founder', es: 'Chequeos de consistencia antes de la fundadora' },
  'studio.home.checksSub': { en: 'The initial check Sarai runs before work reaches Alejandra.', es: 'El chequeo inicial que hace Sarai antes de que el trabajo llegue a Alejandra.' },
  'studio.home.tasks': { en: 'Studio tasks', es: 'Pendientes del estudio' },
  'studio.home.tasksSub': { en: 'Owned by operations; the studio reads them here.', es: 'Los administra operaciones; el estudio los consulta aquí.' },
  'studio.home.packs': { en: 'Render and supplier packs in flight', es: 'Paquetes de render y proveedor en curso' },
  'studio.home.newProposal': { en: 'New design proposal', es: 'Nueva propuesta de diseño' },
  'studio.home.newProposalWhat': { en: 'start a design proposal from the creative direction', es: 'iniciar una propuesta de diseño desde la dirección creativa' },
  'studio.home.rescheduleWhat': { en: 'ask operations to reschedule a studio task', es: 'pedir a operaciones que reprograme un pendiente del estudio' },
  'studio.home.reschedule': { en: 'Ask operations to reschedule', es: 'Pedir reprogramación a operaciones' },
  'studio.home.open': { en: 'Open', es: 'Abrir' },

  // S-02 projects and proposals
  'studio.projects.title': { en: 'Projects and proposals', es: 'Proyectos y propuestas' },
  'studio.projects.subtitle': { en: 'One card per project: phase, the creative direction Alejandra set, the approval state and the documents attached.', es: 'Una tarjeta por proyecto: fase, la dirección creativa que definió Alejandra, el estado de aprobación y los documentos adjuntos.' },
  'studio.projects.search': { en: 'Search project or client…', es: 'Buscar proyecto o cliente…' },
  'studio.projects.detail': { en: 'Project detail', es: 'Detalle del proyecto' },
  'studio.projects.documents': { en: 'Documents', es: 'Documentos' },
  'studio.projects.sendToCheck': { en: 'Send to consistency check', es: 'Enviar a chequeo de consistencia' },
  'studio.projects.sent': { en: 'Sent to consistency check', es: 'Enviado a chequeo de consistencia' },
  'studio.projects.sendHint': { en: 'Only a draft or a project with requested changes can go back into check.', es: 'Solo un borrador o un proyecto con cambios solicitados puede volver a chequeo.' },
  'studio.projects.requestDirection': { en: 'Request creative direction', es: 'Pedir dirección creativa' },
  'studio.projects.requestDirectionWhat': { en: 'ask Alejandra for the creative direction of this project', es: 'pedir a Alejandra la dirección creativa de este proyecto' },
  'studio.projects.newProposalWhat': { en: 'create a proposal document for this project', es: 'crear un documento de propuesta para este proyecto' },
  'studio.projects.newProposal': { en: 'New proposal', es: 'Nueva propuesta' },
  'studio.projects.summary': { en: 'Summary', es: 'Resumen' },
  'studio.projects.lead': { en: 'Lead designer', es: 'Diseñadora líder' },
  'studio.projects.open': { en: 'Open project', es: 'Abrir proyecto' },

  // S-03 references and mood boards
  'studio.references.title': { en: 'References and mood boards', es: 'Referencias y moodboards' },
  'studio.references.subtitle': { en: 'Design research grouped by board: one board per project chapter, tagged so a reference can be found again.', es: 'Investigación de diseño agrupada por tablero: un tablero por capítulo del proyecto, con etiquetas para volver a encontrar la referencia.' },
  'studio.references.search': { en: 'Search reference, source or note…', es: 'Buscar referencia, fuente o nota…' },
  'studio.references.add': { en: 'Add reference', es: 'Agregar referencia' },
  'studio.references.addWhat': { en: 'add a reference with an image and tags to a board', es: 'agregar una referencia con imagen y etiquetas a un tablero' },
  'studio.references.newBoard': { en: 'New mood board', es: 'Nuevo moodboard' },
  'studio.references.newBoardWhat': { en: 'create a mood board for a project chapter', es: 'crear un moodboard para un capítulo del proyecto' },
  'studio.references.noImage': { en: 'No image yet', es: 'Aún sin imagen' },
  'studio.references.uploadWhat': { en: 'upload the reference image', es: 'subir la imagen de la referencia' },
  'studio.references.upload': { en: 'Upload image', es: 'Subir imagen' },
  'studio.references.moveTo': { en: 'Move to board', es: 'Mover a tablero' },
  'studio.references.moved': { en: 'Reference moved', es: 'Referencia movida' },
  'studio.references.count': { en: '{n} on this board', es: '{n} en este tablero' },
  'studio.references.detail': { en: 'Reference', es: 'Referencia' },

  // S-04 material palettes
  'studio.materials.title': { en: 'Material palettes', es: 'Paletas de materiales' },
  'studio.materials.subtitle': { en: 'One palette per project: each material moves from proposed to sampled to approved before it can go into a schedule.', es: 'Una paleta por proyecto: cada material pasa de propuesto a con muestra y a aprobado antes de entrar en un cuadro.' },
  'studio.materials.search': { en: 'Search material, finish or colour…', es: 'Buscar material, acabado o color…' },
  'studio.materials.newPalette': { en: 'New palette', es: 'Nueva paleta' },
  'studio.materials.newPaletteWhat': { en: 'create a material palette for a project', es: 'crear una paleta de materiales para un proyecto' },
  'studio.materials.requestSample': { en: 'Request sample', es: 'Pedir muestra' },
  'studio.materials.approve': { en: 'Approve', es: 'Aprobar' },
  'studio.materials.reject': { en: 'Reject', es: 'Rechazar' },
  'studio.materials.count': { en: '{n} materials · {approved} approved', es: '{n} materiales · {approved} aprobados' },
  'studio.materials.noSupplier': { en: 'No supplier yet', es: 'Aún sin proveedor' },
  'studio.materials.noPrice': { en: 'Unknown', es: 'Sin dato' },

  // S-05 plans and documentation
  'studio.plans.title': { en: 'Plans and design documentation', es: 'Planos y documentación de diseño' },
  'studio.plans.subtitle': { en: 'Drawings and specifications the studio owns, with their version and whether they are still a draft.', es: 'Planos y especificaciones a cargo del estudio, con su versión y si siguen en borrador.' },
  'studio.plans.search': { en: 'Search plan or specification…', es: 'Buscar plano o especificación…' },
  'studio.plans.upload': { en: 'Upload drawing', es: 'Subir plano' },
  'studio.plans.uploadWhat': { en: 'upload a drawing file and attach it to the document', es: 'subir el archivo del plano y adjuntarlo al documento' },
  'studio.plans.newVersion': { en: 'New version', es: 'Nueva versión' },
  'studio.plans.markFinal': { en: 'Mark final', es: 'Marcar final' },
  'studio.plans.versioned': { en: 'Version {n} created as a draft', es: 'Versión {n} creada como borrador' },
  'studio.plans.stat.total': { en: 'Plans and specs', es: 'Planos y especificaciones' },
  'studio.plans.stat.draft': { en: 'Still draft', es: 'Aún en borrador' },
  'studio.plans.stat.final': { en: 'Final', es: 'Finales' },
  'studio.plans.detail': { en: 'Document', es: 'Documento' },
  'studio.plans.openFile': { en: 'Open file', es: 'Abrir archivo' },
  'studio.plans.openFileWhat': { en: 'open the stored drawing file', es: 'abrir el archivo del plano almacenado' },
  'studio.plans.noFile': { en: 'No file attached', es: 'Sin archivo adjunto' },

  // S-06 schedules
  'studio.schedules.title': { en: 'Furniture, material and element schedules', es: 'Cuadros de mobiliario, materiales y elementos' },
  'studio.schedules.subtitle': { en: 'The specification lists per project. A schedule goes draft, in review, final; final schedules feed the supplier packs.', es: 'Las listas de especificación por proyecto. Un cuadro pasa de borrador a en revisión y a final; los cuadros finales alimentan los paquetes de proveedor.' },
  'studio.schedules.all': { en: 'All', es: 'Todos' },
  'studio.schedules.kind.furniture': { en: 'Furniture', es: 'Mobiliario' },
  'studio.schedules.kind.materials': { en: 'Materials', es: 'Materiales' },
  'studio.schedules.kind.lighting': { en: 'Lighting', es: 'Iluminación' },
  'studio.schedules.kind.elements': { en: 'Elements', es: 'Elementos' },
  'studio.schedules.stat.items': { en: 'Items specified', es: 'Ítems especificados' },
  'studio.schedules.stat.final': { en: 'Final schedules', es: 'Cuadros finales' },
  'studio.schedules.stat.open': { en: 'Draft or in review', es: 'En borrador o revisión' },
  'studio.schedules.sendToReview': { en: 'Send to review', es: 'Enviar a revisión' },
  'studio.schedules.markFinal': { en: 'Mark final', es: 'Marcar final' },
  'studio.schedules.new': { en: 'New schedule', es: 'Nuevo cuadro' },
  'studio.schedules.newWhat': { en: 'create a schedule for a project', es: 'crear un cuadro para un proyecto' },
  'studio.schedules.openItems': { en: 'Open item list', es: 'Abrir lista de ítems' },
  'studio.schedules.openItemsWhat': { en: 'open the line items of this schedule (no line-item entity yet)', es: 'abrir los ítems de este cuadro (aún no existe la entidad de ítems)' },
  'studio.schedules.detail': { en: 'Schedule', es: 'Cuadro' },

  // S-07 render and supplier packs
  'studio.packs.title': { en: 'Render and supplier packs', es: 'Paquetes de render y proveedor' },
  'studio.packs.subtitle': { en: 'Information prepared for the render artist and for suppliers, from briefing to delivered.', es: 'Información preparada para el renderista y para los proveedores, del brief a la entrega.' },
  'studio.packs.board': { en: 'Packs by stage', es: 'Paquetes por etapa' },
  'studio.packs.stat.flight': { en: 'In flight', es: 'En curso' },
  'studio.packs.stat.delivered': { en: 'Delivered', es: 'Entregados' },
  'studio.packs.stat.views': { en: 'Views briefed', es: 'Vistas en brief' },
  'studio.packs.new': { en: 'New pack', es: 'Nuevo paquete' },
  'studio.packs.newWhat': { en: 'brief a new render or supplier pack', es: 'preparar el brief de un nuevo paquete de render o proveedor' },
  'studio.packs.audience.render-artist': { en: 'Render artist', es: 'Renderista' },
  'studio.packs.audience.supplier': { en: 'Supplier', es: 'Proveedor' },
  'studio.packs.moved': { en: 'Pack moved to {status}', es: 'Paquete movido a {status}' },
  'studio.packs.detail': { en: 'Pack', es: 'Paquete' },
  'studio.packs.attach': { en: 'Attach pack contents', es: 'Adjuntar contenido del paquete' },
  'studio.packs.attachWhat': { en: 'attach the drawings, materials and views that make up the pack', es: 'adjuntar los planos, materiales y vistas que componen el paquete' },
  'studio.packs.meta': { en: '{views} views · {project}', es: '{views} vistas · {project}' },

  // S-08 consistency check
  'studio.checks.title': { en: 'Consistency check', es: 'Chequeo de consistencia' },
  'studio.checks.subtitle': { en: 'Sarai’s initial check before work reaches Alejandra. Passing it puts the project in the founder’s approval queue.', es: 'El chequeo inicial de Sarai antes de que el trabajo llegue a Alejandra. Aprobarlo pone el proyecto en la cola de aprobación de la fundadora.' },
  'studio.checks.stat.pending': { en: 'Pending', es: 'Pendientes' },
  'studio.checks.stat.issues': { en: 'With issues', es: 'Con observaciones' },
  'studio.checks.stat.passed': { en: 'Passed', es: 'Aprobados' },
  'studio.checks.pass': { en: 'Mark passed', es: 'Marcar aprobado' },
  'studio.checks.issues': { en: 'Report issues', es: 'Reportar observaciones' },
  'studio.checks.passHint': { en: 'Every item must be ticked before the check can pass.', es: 'Todos los ítems deben estar marcados para poder aprobar el chequeo.' },
  'studio.checks.passed': { en: 'Check passed — project now awaits the founder', es: 'Chequeo aprobado — el proyecto espera a la fundadora' },
  'studio.checks.reported': { en: 'Issues reported — project stays in check', es: 'Observaciones reportadas — el proyecto sigue en revisión' },
  'studio.checks.notes': { en: 'Notes for Alejandra', es: 'Notas para Alejandra' },
  'studio.checks.notesHint': { en: 'What she should look at first.', es: 'Qué debería mirar primero.' },
  'studio.checks.saveNotes': { en: 'Save notes', es: 'Guardar notas' },
  'studio.checks.checkedBy': { en: 'Checked by', es: 'Revisado por' },
  'studio.checks.progress': { en: '{ok} of {total} items ticked', es: '{ok} de {total} ítems marcados' },
  'studio.checks.new': { en: 'New check', es: 'Nuevo chequeo' },
  'studio.checks.newWhat': { en: 'start a consistency check from a project template', es: 'iniciar un chequeo de consistencia desde una plantilla de proyecto' },
  'studio.checks.addItem': { en: 'Add check item', es: 'Agregar ítem al chequeo' },
  'studio.checks.addItemWhat': { en: 'add a new item to this consistency check', es: 'agregar un ítem nuevo a este chequeo de consistencia' },
  'studio.checks.empty': { en: 'No consistency checks yet', es: 'Aún no hay chequeos de consistencia' },
  'studio.checks.emptyDesc': { en: 'A check is created when a project is ready to leave the studio.', es: 'Un chequeo se crea cuando un proyecto está listo para salir del estudio.' },

  // S-09 measurements and requirements
  'studio.measurements.title': { en: 'Measurements and requirements', es: 'Medidas y requerimientos' },
  'studio.measurements.subtitle': { en: 'Verifying measurements on site and holding each space’s requirements. The capture tools are not wired yet.', es: 'Verificación de medidas en sitio y requerimientos de cada espacio. Las herramientas de captura aún no están conectadas.' },
  'studio.measurements.stat.projects': { en: 'Projects to verify', es: 'Proyectos por verificar' },
  'studio.measurements.stat.tasks': { en: 'Open site tasks', es: 'Pendientes en sitio' },
  'studio.measurements.stat.schedules': { en: 'Schedules waiting', es: 'Cuadros en espera' },
  'studio.measurements.projects': { en: 'Projects and sites', es: 'Proyectos y sitios' },
  'studio.measurements.projectsSub': { en: 'Where the measurements have to be verified before documentation.', es: 'Dónde hay que verificar las medidas antes de la documentación.' },
  'studio.measurements.tasks': { en: 'Site visits and measurement tasks', es: 'Visitas de obra y pendientes de medidas' },
  'studio.measurements.tasksSub': { en: 'Read-only: task status is owned by operations.', es: 'Solo lectura: el estado de los pendientes lo administra operaciones.' },
  'studio.measurements.sheet': { en: 'Room-by-room dimensions', es: 'Dimensiones espacio por espacio' },
  'studio.measurements.sheetWhat': { en: 'capture room-by-room dimensions for a project', es: 'capturar dimensiones espacio por espacio de un proyecto' },
  'studio.measurements.sheetDesc': { en: 'A dimension sheet per space: walls, ceiling heights, openings, electrical points.', es: 'Una hoja de dimensiones por espacio: muros, alturas, vanos, puntos eléctricos.' },
  'studio.measurements.requirements': { en: 'Requirements per space', es: 'Requerimientos por espacio' },
  'studio.measurements.requirementsWhat': { en: 'record the client and technical requirements of a space', es: 'registrar los requerimientos del cliente y técnicos de un espacio' },
  'studio.measurements.requirementsDesc': { en: 'What the client asked for and what the space needs technically, checked off against the design.', es: 'Lo que pidió el cliente y lo que el espacio necesita técnicamente, contrastado con el diseño.' },
  'studio.measurements.photos': { en: 'Site photos and annotations', es: 'Fotos de obra y anotaciones' },
  'studio.measurements.photosWhat': { en: 'attach site photos and annotate them', es: 'adjuntar fotos de obra y anotarlas' },
  'studio.measurements.photosDesc': { en: 'Photos from the site visit, annotated where a measurement disagrees with the drawing.', es: 'Fotos de la visita, anotadas donde una medida no coincide con el plano.' },
  'studio.measurements.openSheet': { en: 'Open measurement sheet', es: 'Abrir hoja de medidas' },
  'studio.measurements.openSheetWhat': { en: 'open the measurement sheet of a project', es: 'abrir la hoja de medidas de un proyecto' },
};
