import type { StringTable } from '../../i18n/types';

/**
 * Public site strings, namespaced `public.*` (P-13). Aluzina's clients are Spanish-speaking people in
 * Medellín, so every key here carries `es` as well as `en`: this is the one surface where a missing
 * Spanish string would be read by a customer. Service names, outcomes, phases and checklist items are
 * not here - they come from `src/domain/playbook.ts` through `pick(text, lang)` (D-033).
 */
export const strings: StringTable = {
  // ---------------------------------------------------------------- layout (P-01..P-04)
  'public.brand': { en: 'Aluzina', es: 'Aluzina' },
  'public.tagline': { en: 'Spaces + Light + Experiences that transform', es: 'Espacios + Luz + Experiencias que transforman' },
  'public.home': { en: 'Aluzina, start of the site', es: 'Aluzina, inicio del sitio' },
  'public.skip': { en: 'Skip to content', es: 'Ir al contenido' },
  'public.nav.label': { en: 'Site sections', es: 'Secciones del sitio' },
  'public.nav.services': { en: 'Services', es: 'Servicios' },
  'public.nav.start': { en: 'Start your project', es: 'Empieza tu proyecto' },
  'public.nav.method': { en: 'Our method', es: 'Nuestro método' },
  'public.nav.portfolio': { en: 'Portfolio', es: 'Portafolio' },
  'public.staffHub': { en: 'Staff: open the Hub', es: 'Equipo: abrir el Hub' },
  'public.footer.label': { en: 'Studio and contact', es: 'Estudio y contacto' },
  'public.footer.studio': { en: 'Aluzina — Interior Design & Emotional Lighting, Medellín, Colombia.', es: 'Aluzina — Diseño interior e iluminación emocional, Medellín, Colombia.' },
  'public.footer.website': { en: 'aluzinaa.com', es: 'aluzinaa.com' },
  'public.footer.websiteAria': { en: 'Open aluzinaa.com, the studio portfolio', es: 'Abrir aluzinaa.com, el portafolio del estudio' },
  'public.footer.instagram': { en: 'Instagram', es: 'Instagram' },
  'public.footer.instagramWhat': { en: 'open the studio Instagram account (the handle is not published yet)', es: 'abrir la cuenta de Instagram del estudio (aún no se publica el usuario)' },
  'public.footer.whatsapp': { en: 'WhatsApp', es: 'WhatsApp' },
  'public.footer.whatsappWhat': { en: 'write to the studio on WhatsApp (the number is not published yet)', es: 'escribir al estudio por WhatsApp (aún no se publica el número)' },
  'public.footer.contactHint': { en: 'Until the studio publishes its channels here, the intake form is the way to reach us.', es: 'Mientras el estudio publica sus canales aquí, el formulario es la forma de contactarnos.' },
  'public.cta.start': { en: 'Start your project', es: 'Empieza tu proyecto' },

  // ---------------------------------------------------------------- P-01 /services
  'public.services.title': { en: 'Interior design and emotional lighting in Medellín', es: 'Diseño interior e iluminación emocional en Medellín' },
  'public.services.lead': {
    en: 'Aluzina is an interior design studio working with space, light and experience. We read how you live a place before we change it, and we take it as far as you need: from a first creative direction to the finished, built space.',
    es: 'Aluzina es un estudio de diseño interior que trabaja con el espacio, la luz y la experiencia. Leemos cómo vives un lugar antes de cambiarlo y lo llevamos tan lejos como lo necesites: desde una primera dirección creativa hasta el espacio construido y terminado.',
  },
  'public.services.founder': { en: 'Alejandra Guerra — Founder & Creative Director', es: 'Alejandra Guerra — Fundadora y directora creativa' },
  'public.services.ladder.title': { en: 'Five ways to work with us', es: 'Cinco formas de trabajar con nosotros' },
  'public.services.ladder.desc': {
    en: 'Each service answers a different question and goes a different depth. You can start anywhere.',
    es: 'Cada servicio responde a una pregunta distinta y llega a una profundidad distinta. Puedes empezar por donde quieras.',
  },
  'public.services.ladder.listLabel': { en: 'Aluzina services', es: 'Servicios de Aluzina' },
  'public.services.card.idealFor': { en: 'Ideal for', es: 'Ideal para' },
  'public.services.card.question': { en: 'The question it answers', es: 'La pregunta que responde' },
  'public.services.card.promise': { en: 'Our promise', es: 'Nuestra promesa' },
  'public.services.card.open': { en: 'See this service', es: 'Ver este servicio' },
  'public.services.journey.title': { en: 'How we work', es: 'Cómo trabajamos' },
  'public.services.journey.desc': {
    en: 'Every project, large or small, walks the same ten steps. You always know which one you are in.',
    es: 'Todo proyecto, grande o pequeño, recorre los mismos diez pasos. Siempre sabes en cuál estás.',
  },
  'public.services.journey.listLabel': { en: 'The ten steps of a project', es: 'Los diez pasos de un proyecto' },
  'public.services.logic.title': { en: 'One studio. One method. Different depths of service.', es: 'Un estudio. Un método. Distintas profundidades de servicio.' },
  'public.services.cta.title': { en: 'Tell us about your space', es: 'Cuéntanos sobre tu espacio' },
  'public.services.cta.body': {
    en: 'Answer a few questions and the studio will come back to you with the right starting point. It takes about five minutes.',
    es: 'Responde unas preguntas y el estudio volverá a ti con el punto de partida adecuado. Toma unos cinco minutos.',
  },
  'public.services.cta.method': { en: 'Read our method', es: 'Leer nuestro método' },

  // ---------------------------------------------------------------- P-02 /services/:slug
  'public.detail.crumbServices': { en: 'Services', es: 'Servicios' },
  'public.detail.idealFor': { en: 'Ideal for', es: 'Ideal para' },
  'public.detail.question': { en: 'The question it answers', es: 'La pregunta que responde' },
  'public.detail.promise': { en: 'Our promise', es: 'Nuestra promesa' },
  'public.detail.get.title': { en: 'What you receive', es: 'Qué recibes' },
  'public.detail.get.desc': { en: 'The delivery of this service includes:', es: 'La entrega de este servicio incluye:' },
  'public.detail.how.title': { en: 'How it unfolds', es: 'Cómo se desarrolla' },
  'public.detail.how.desc': {
    en: 'The studio works through these steps in order. Open a step to see what it covers.',
    es: 'El estudio recorre estos pasos en orden. Abre un paso para ver qué cubre.',
  },
  'public.detail.step': { en: 'Step {n}', es: 'Paso {n}' },
  'public.detail.stepShow': { en: 'Show what "{title}" covers', es: 'Ver qué cubre «{title}»' },
  'public.detail.stepHide': { en: 'Hide what "{title}" covers', es: 'Ocultar qué cubre «{title}»' },
  'public.detail.stepOpen': { en: 'What it covers', es: 'Qué cubre' },
  'public.detail.stepClose': { en: 'Close', es: 'Cerrar' },
  'public.detail.notIncluded.title': { en: 'What is not included', es: 'Qué no está incluido' },
  'public.detail.notIncluded.desc': {
    en: 'So there are no surprises, this service does not cover:',
    es: 'Para que no haya sorpresas, este servicio no cubre:',
  },
  'public.detail.next.title': { en: 'The natural next step', es: 'El siguiente paso natural' },
  'public.detail.cta': { en: 'Start with this service', es: 'Empezar con este servicio' },
  'public.detail.prev': { en: 'Previous service', es: 'Servicio anterior' },
  'public.detail.next': { en: 'Next service', es: 'Servicio siguiente' },
  'public.detail.moreLabel': { en: 'More services', es: 'Más servicios' },
  'public.detail.notFound.title': { en: 'We could not find that service', es: 'No encontramos ese servicio' },
  'public.detail.notFound.desc': {
    en: 'The link may be old. These are the five services the studio offers today.',
    es: 'Puede que el enlace esté desactualizado. Estos son los cinco servicios que ofrece el estudio hoy.',
  },
  'public.detail.notFound.cta': { en: 'See all services', es: 'Ver todos los servicios' },

  // ---------------------------------------------------------------- P-03 /start
  'public.start.title': { en: 'Start your project', es: 'Empieza tu proyecto' },
  'public.start.subtitle': {
    en: 'Four short steps. Nothing is charged here: the studio reads your answers and comes back to you with the right starting point.',
    es: 'Cuatro pasos cortos. Aquí no se cobra nada: el estudio lee tus respuestas y vuelve a ti con el punto de partida adecuado.',
  },
  'public.start.progress': { en: 'Step {n} of {total}', es: 'Paso {n} de {total}' },
  'public.start.stepsLabel': { en: 'Steps of the form', es: 'Pasos del formulario' },
  'public.start.goToStep': { en: 'Go back to step {n}: {title}', es: 'Volver al paso {n}: {title}' },
  'public.start.step1': { en: 'About you', es: 'Sobre ti' },
  'public.start.step2': { en: 'Your space', es: 'Tu espacio' },
  'public.start.step3': { en: 'What you need', es: 'Qué necesitas' },
  'public.start.step4': { en: 'Review and send', es: 'Revisar y enviar' },
  'public.start.back': { en: 'Back', es: 'Atrás' },
  'public.start.next': { en: 'Next', es: 'Siguiente' },
  'public.start.submit': { en: 'Send my request', es: 'Enviar mi solicitud' },
  'public.start.sending': { en: 'Sending…', es: 'Enviando…' },
  'public.start.errorSummary': { en: 'Please check the highlighted answers before continuing.', es: 'Revisa las respuestas señaladas antes de continuar.' },
  'public.start.err.required': { en: 'This answer is needed to continue.', es: 'Necesitamos esta respuesta para continuar.' },
  'public.start.err.email': { en: 'Please write an email address we can reply to.', es: 'Escribe un correo al que podamos responderte.' },
  'public.start.err.number': { en: 'Please write a number, for example 85.', es: 'Escribe un número, por ejemplo 85.' },
  'public.start.err.consent': { en: 'We need your permission to contact you about this request.', es: 'Necesitamos tu permiso para contactarte sobre esta solicitud.' },
  'public.start.err.submit': { en: 'We could not send the request. Please try again.', es: 'No pudimos enviar la solicitud. Inténtalo de nuevo.' },
  'public.start.optional': { en: 'Optional', es: 'Opcional' },

  'public.start.field.name': { en: 'Your name', es: 'Tu nombre' },
  'public.start.field.phone': { en: 'Phone or WhatsApp', es: 'Teléfono o WhatsApp' },
  'public.start.field.email': { en: 'Email', es: 'Correo electrónico' },
  'public.start.field.city': { en: 'City', es: 'Ciudad' },
  'public.start.field.cityHint': { en: 'Medellín, Envigado, Rionegro, or wherever the space is.', es: 'Medellín, Envigado, Rionegro o donde esté el espacio.' },
  'public.start.field.projectType': { en: 'Type of project', es: 'Tipo de proyecto' },
  'public.start.field.areaM2': { en: 'Approximate area in m²', es: 'Área aproximada en m²' },
  'public.start.field.areaHint': { en: 'An estimate is enough.', es: 'Basta con un estimado.' },
  'public.start.field.projectStatus': { en: 'Current state of the space', es: 'Estado actual del espacio' },
  'public.start.field.floorPlan': { en: 'Is there a floor plan?', es: '¿Existe un plano?' },
  'public.start.field.channel': { en: 'How did you find Aluzina?', es: '¿Cómo conociste a Aluzina?' },
  'public.start.field.requestedService': { en: 'Is there a service you already have in mind?', es: '¿Hay un servicio que ya tengas en mente?' },
  'public.start.field.requestedServiceHint': { en: 'You can leave this open: the studio suggests a path at the end.', es: 'Puedes dejarlo abierto: el estudio sugiere una ruta al final.' },
  'public.start.choose': { en: 'Choose an option', es: 'Elige una opción' },
  'public.start.undecided': { en: 'Not sure yet', es: 'Aún no lo sé' },

  'public.start.q.transform': { en: 'What do you want to transform?', es: '¿Qué quieres transformar?' },
  'public.start.q.transformHint': { en: 'The space, what happens in it, what does not work today.', es: 'El espacio, lo que sucede en él, lo que hoy no funciona.' },
  'public.start.q.why': { en: 'Why do you want to do it now?', es: '¿Por qué quieres hacerlo ahora?' },
  'public.start.q.depth': { en: 'How far do you want to take it?', es: '¿Hasta dónde quieres llevarlo?' },
  'public.start.q.execute': { en: 'Would you like Aluzina to carry out the work?', es: '¿Te gustaría que Aluzina ejecute la obra?' },
  'public.start.q.investment': { en: 'What investment range do you have in mind?', es: '¿Qué rango de inversión tienes en mente?' },
  'public.start.q.investmentHint': { en: 'A range is enough. It helps us propose a scope that fits.', es: 'Basta con un rango. Nos ayuda a proponer un alcance que se ajuste.' },
  'public.start.q.start': { en: 'When would you like to start?', es: '¿Cuándo te gustaría empezar?' },

  'public.start.review.title': { en: 'Everything you told us', es: 'Todo lo que nos contaste' },
  'public.start.review.suggestion': { en: 'The path we suggest', es: 'La ruta que sugerimos' },
  'public.start.review.then': { en: 'And afterwards, when the design is approved: {service}.', es: 'Y después, cuando el diseño esté aprobado: {service}.' },
  'public.start.review.confirm': {
    en: 'This is a first read of your answers. Our team confirms the right path with you before anything starts.',
    es: 'Esta es una primera lectura de tus respuestas. Nuestro equipo confirma contigo la ruta adecuada antes de empezar.',
  },
  'public.start.review.consent': { en: 'Aluzina may contact me about this request by email, phone or WhatsApp.', es: 'Aluzina puede contactarme sobre esta solicitud por correo, teléfono o WhatsApp.' },
  'public.start.review.empty': { en: 'Not answered', es: 'Sin responder' },

  'public.start.done.title': { en: 'Your request is with the studio', es: 'Tu solicitud está con el estudio' },
  'public.start.done.reference': { en: 'Your reference', es: 'Tu referencia' },
  'public.start.done.referenceHint': { en: 'Keep it: it identifies your request when we talk.', es: 'Guárdala: identifica tu solicitud cuando hablemos.' },
  'public.start.done.next.title': { en: 'What happens now', es: 'Qué sigue ahora' },
  'public.start.done.next1': { en: 'The studio reads your answers and confirms the right starting point for your space.', es: 'El estudio lee tus respuestas y confirma el punto de partida adecuado para tu espacio.' },
  'public.start.done.next2': { en: 'The studio will contact you to schedule the diagnosis.', es: 'El estudio te contactará para agendar el diagnóstico.' },
  'public.start.done.next3': { en: 'Once the diagnosis is agreed, the service is activated and the work begins.', es: 'Una vez acordado el diagnóstico, se activa el servicio y comienza el trabajo.' },
  'public.start.done.reserve.title': { en: 'Reserving your place', es: 'Reservar tu lugar' },
  'public.start.done.reserve.body': { en: 'This service can be reserved with a deposit once the studio confirms it with you.', es: 'Este servicio se puede reservar con un anticipo una vez que el estudio lo confirme contigo.' },
  'public.start.done.reserve.cta': { en: 'Reserve with a deposit', es: 'Reservar con un anticipo' },
  'public.start.done.reserve.what': { en: 'take the deposit online and reserve the service', es: 'tomar el anticipo en línea y reservar el servicio' },
  'public.start.done.proposal.title': { en: 'What follows for this path', es: 'Qué sigue para esta ruta' },
  'public.start.done.proposal.body': {
    en: 'For this depth of work there is no deposit at this point: a proposal follows the consultation, with scope, stages and investment written out.',
    es: 'Para esta profundidad de trabajo no hay anticipo en este punto: una propuesta sigue a la consultoría, con alcance, etapas e inversión por escrito.',
  },
  'public.start.done.services': { en: 'Read about the services', es: 'Leer sobre los servicios' },

  // ---------------------------------------------------------------- P-04 /method
  'public.method.title': { en: 'One studio. One method. Different depths of service.', es: 'Un estudio. Un método. Distintas profundidades de servicio.' },
  'public.method.subtitle': {
    en: 'How Aluzina works, written down. The same method carries a two-hour consultation and a building site.',
    es: 'Cómo trabaja Aluzina, puesto por escrito. El mismo método sostiene una consultoría de dos horas y una obra.',
  },
  'public.method.journey.title': { en: 'The journey of a project', es: 'El recorrido de un proyecto' },
  'public.method.journey.desc': {
    en: 'Ten steps, always in this order. At every step you know what was decided and what comes next.',
    es: 'Diez pasos, siempre en este orden. En cada paso sabes qué se decidió y qué viene después.',
  },
  'public.method.principle.title': { en: 'We observe, then we process, then we design', es: 'Observamos, luego procesamos, luego diseñamos' },
  'public.method.promise.title': { en: 'What comprehensive design means here', es: 'Qué significa aquí el diseño integral' },
  'public.method.gate.title': { en: 'Design and construction are separate stages', es: 'Diseño y construcción son etapas separadas' },
  'public.method.team.title': { en: 'Who works on your project', es: 'Quién trabaja en tu proyecto' },
  'public.method.team.desc': {
    en: 'A small studio with clear roles. Every project has one person inside Aluzina who answers for it.',
    es: 'Un estudio pequeño con roles claros. Cada proyecto tiene una persona dentro de Aluzina que responde por él.',
  },
  'public.method.team.founder': { en: 'Alejandra Guerra — creative direction, key decisions, client relationship and final approval.', es: 'Alejandra Guerra — dirección creativa, decisiones clave, relación con el cliente y aprobación final.' },
  'public.method.final.title': { en: 'Why we work like this', es: 'Por qué trabajamos así' },
  'public.method.portfolio.title': { en: 'See the work', es: 'Ver el trabajo' },
  'public.method.portfolio.body': { en: 'Finished spaces, photography and the studio story live on aluzinaa.com.', es: 'Los espacios terminados, la fotografía y la historia del estudio están en aluzinaa.com.' },
  'public.method.portfolio.cta': { en: 'Open aluzinaa.com', es: 'Abrir aluzinaa.com' },

  // ---------------------------------------------------------------- P-05 /portfolio
  'public.portfolio.title': { en: 'Portfolio and brochure', es: 'Portafolio y brochure' },
  'public.portfolio.subtitle': {
    en: 'Read the studio portfolio and the brochure here, or take the PDF with you.',
    es: 'Lee aquí el portafolio del estudio y el brochure, o llévate el PDF.',
  },
  'public.portfolio.intro': {
    en: 'Two documents say most of what a first conversation needs: the portfolio, with the projects and the way we work with space and light, and the brochure, a short presentation of the studio and its services. Both open in this page and both can be downloaded.',
    es: 'Dos documentos cuentan casi todo lo que necesita una primera conversación: el portafolio, con los proyectos y la manera en que trabajamos el espacio y la luz, y el brochure, una presentación corta del estudio y sus servicios. Los dos se abren en esta página y los dos se pueden descargar.',
  },
  'public.portfolio.doc.portfolio.title': { en: 'Portfolio', es: 'Portafolio' },
  'public.portfolio.doc.portfolio.desc': {
    en: 'Projects, spaces and the way Aluzina works with light.',
    es: 'Proyectos, espacios y la forma en que Aluzina trabaja la luz.',
  },
  'public.portfolio.doc.brochure.title': { en: 'Brochure', es: 'Brochure' },
  'public.portfolio.doc.brochure.desc': {
    en: 'A short presentation of the studio and its services.',
    es: 'Una presentación corta del estudio y sus servicios.',
  },
  'public.portfolio.fileMeta': { en: 'PDF · {pages} pages · {size} MB', es: 'PDF · {pages} páginas · {size} MB' },
  'public.portfolio.view': { en: 'Read it here', es: 'Leerlo aquí' },
  'public.portfolio.download': { en: 'Download the PDF', es: 'Descargar el PDF' },
  'public.portfolio.downloadAria': { en: 'Download {title} as a PDF', es: 'Descargar {title} en PDF' },
  'public.portfolio.newTab': { en: 'Open in a new tab', es: 'Abrir en pestaña nueva' },
  'public.portfolio.newTabAria': { en: 'Open {title} in a new tab', es: 'Abrir {title} en una pestaña nueva' },
  'public.portfolio.viewer': { en: 'Read it here', es: 'Léelo aquí' },
  'public.portfolio.tabsLabel': { en: 'Document to read', es: 'Documento por leer' },
  'public.portfolio.frameTitle': { en: '{title}, PDF viewer', es: '{title}, visor de PDF' },
  'public.portfolio.noPdf': {
    en: 'Your browser cannot show PDFs here; download it instead.',
    es: 'Tu navegador no puede mostrar PDF aquí; descárgalo.',
  },
  'public.portfolio.palette': { en: 'Colours of the document: {colors}', es: 'Colores del documento: {colors}' },
  'public.portfolio.fonts': { en: 'Typefaces: {fonts}', es: 'Tipografías: {fonts}' },
  'public.portfolio.website.title': { en: 'See the built work', es: 'Ve el trabajo construido' },
  'public.portfolio.website.body': {
    en: 'The studio site keeps the full body of work, with photography of the finished spaces.',
    es: 'El sitio del estudio conserva todo el trabajo, con fotografía de los espacios terminados.',
  },
  'public.portfolio.website.cta': { en: 'Visit aluzinaa.com', es: 'Visitar aluzinaa.com' },
};
