import type { StringTable } from '../../i18n/types';

/**
 * Client app (C-01..C-06). Namespace `client.`; Spanish is complete and is the language the studio's
 * clients in Medellín actually read (P-13, D-004), so every key carries `es`.
 */
export const strings: StringTable = {
  // nav (order sets the PhoneShell bottom nav)
  'client.nav.home': { en: 'Home', es: 'Inicio' },
  'client.nav.approvals': { en: 'Approvals', es: 'Aprobaciones' },
  'client.nav.messages': { en: 'Messages', es: 'Mensajes' },
  'client.nav.payments': { en: 'Payments', es: 'Pagos' },
  'client.nav.brief': { en: 'Brief', es: 'Brief' },

  // shared
  'client.common.project': { en: 'Project', es: 'Proyecto' },
  'client.common.service': { en: 'Service', es: 'Servicio' },
  'client.common.phase': { en: 'Current phase', es: 'Fase actual' },
  'client.common.status': { en: 'Status', es: 'Estado' },
  'client.common.progress': { en: 'Progress', es: 'Avance' },
  'client.common.selectProject': { en: 'Project', es: 'Proyecto' },
  'client.common.loading': { en: 'Loading your projects…', es: 'Cargando tus proyectos…' },
  'client.common.empty': { en: 'No project yet', es: 'Aún no hay proyecto' },
  'client.common.emptyDesc': {
    en: 'This account is not linked to a project yet. Write to the studio and we will connect it.',
    es: 'Esta cuenta todavía no está vinculada a un proyecto. Escríbenos al estudio y lo conectamos.',
  },
  'client.common.notMine': { en: 'Not your project?', es: '¿No es tu proyecto?' },
  'client.common.notMineDesc': {
    en: 'You only ever see the projects linked to your account. If something is missing, tell us in Messages.',
    es: 'Solo ves los proyectos vinculados a tu cuenta. Si falta alguno, cuéntanos en Mensajes.',
  },

  // C-01 home
  'client.home.title': { en: 'Your project', es: 'Tu proyecto' },
  'client.home.desc': { en: 'Where your project stands today and what needs you.', es: 'Cómo va tu proyecto hoy y qué necesita de ti.' },
  'client.home.greeting': { en: 'Hello, {name}', es: 'Hola, {name}' },
  'client.home.openItems': { en: 'Waiting for you', es: 'Pendiente de ti' },
  'client.home.stat.revisions': { en: 'Comments to decide', es: 'Comentarios por decidir' },
  'client.home.stat.revisionsHint': { en: 'In the revision matrix', es: 'En la matriz de revisión' },
  'client.home.stat.unread': { en: 'Unread messages', es: 'Mensajes sin leer' },
  'client.home.stat.unreadHint': { en: 'From the studio', es: 'Del estudio' },
  'client.home.stat.payments': { en: 'Pending payments', es: 'Pagos pendientes' },
  'client.home.stat.paymentsHint': { en: '{amount} outstanding', es: '{amount} por pagar' },
  'client.home.progress': { en: '{done} of {total} steps done ({percent}%)', es: '{done} de {total} pasos hechos ({percent}%)' },
  'client.home.progressLabel': { en: 'Project progress', es: 'Avance del proyecto' },
  'client.home.nextStep': { en: 'Next step', es: 'Siguiente paso' },
  'client.home.nextPhase': { en: 'Starting: {phase}', es: 'Comienza: {phase}' },
  'client.home.allDone': { en: 'Everything in this service is done.', es: 'Todo este servicio está completo.' },
  'client.home.noService': { en: 'The studio is still setting up this project.', es: 'El estudio todavía está preparando este proyecto.' },
  'client.home.openProject': { en: 'Open project', es: 'Abrir proyecto' },
  'client.home.projectAria': { en: 'Open the project {name}', es: 'Abrir el proyecto {name}' },
  'client.home.journey': { en: 'Your journey', es: 'Tu recorrido' },
  'client.home.journeyDesc': { en: 'The ten steps every ALUZINA project goes through.', es: 'Los diez pasos por los que pasa todo proyecto ALUZINA.' },
  'client.home.journeyLabel': { en: 'Client journey', es: 'Recorrido del cliente' },
  'client.home.step.done': { en: 'Done', es: 'Hecho' },
  'client.home.step.current': { en: 'You are here', es: 'Estás aquí' },
  'client.home.step.todo': { en: 'Still to come', es: 'Por venir' },

  // C-02 project
  'client.project.title': { en: 'Your project', es: 'Tu proyecto' },
  'client.project.outcome': { en: 'What this service gives you', es: 'Qué te entrega este servicio' },
  'client.project.phases': { en: 'What we do, step by step', es: 'Lo que hacemos, paso a paso' },
  'client.project.phasesDesc': {
    en: 'The studio ticks these off as it works. They are read only for you.',
    es: 'El estudio las va marcando a medida que avanza. Para ti son solo de lectura.',
  },
  'client.project.phaseLabel': { en: 'Phase {number}: {title}', es: 'Fase {number}: {title}' },
  'client.project.stageLabel': { en: 'Stage {number}: {title}', es: 'Etapa {number}: {title}' },
  'client.project.phaseCount': { en: '{done}/{total}', es: '{done}/{total}' },
  'client.project.itemDone': { en: 'Done', es: 'Hecho' },
  'client.project.itemPending': { en: 'Pending', es: 'Pendiente' },
  'client.project.deliverables': { en: 'Documents for you', es: 'Documentos para ti' },
  'client.project.deliverablesEmpty': { en: 'Nothing published yet', es: 'Todavía no hay nada publicado' },
  'client.project.deliverablesEmptyDesc': {
    en: 'Your documents appear here as the studio finalises them.',
    es: 'Tus documentos aparecen aquí a medida que el estudio los finaliza.',
  },
  'client.project.dates': { en: 'Dates', es: 'Fechas' },
  'client.project.start': { en: 'Start', es: 'Inicio' },
  'client.project.due': { en: 'Estimated delivery', es: 'Entrega estimada' },
  'client.project.serviceStart': { en: 'Service started', es: 'Servicio iniciado' },
  'client.project.team': { en: 'Your studio team', es: 'Tu equipo del estudio' },
  'client.project.leadDesigner': { en: 'Lead designer', es: 'Diseñadora líder' },
  'client.project.message': { en: 'Message the studio', es: 'Escribir al estudio' },
  'client.project.reviewTitle': { en: 'Your review is needed', es: 'Necesitamos tu revisión' },
  'client.project.reviewDesc': {
    en: 'The scheme is with you. Leave every comment in the revision matrix so nothing gets lost.',
    es: 'El esquema está en tus manos. Deja cada comentario en la matriz de revisión para que nada se pierda.',
  },
  'client.project.reviewOpen': { en: 'Go to approvals', es: 'Ir a aprobaciones' },
  'client.project.notFound': { en: 'Project not available', es: 'Proyecto no disponible' },
  'client.project.notFoundDesc': {
    en: 'This project is not linked to your account.',
    es: 'Este proyecto no está vinculado a tu cuenta.',
  },
  'client.project.back': { en: 'Back to home', es: 'Volver al inicio' },

  // C-03 approvals
  'client.approvals.title': { en: 'Approvals', es: 'Aprobaciones' },
  'client.approvals.desc': { en: 'Every comment on the design, in one place.', es: 'Todos los comentarios del diseño, en un solo lugar.' },
  'client.approvals.rule': { en: 'All comments are collected here, not in WhatsApp.', es: 'Todos los comentarios se recogen aquí, no en WhatsApp.' },
  'client.approvals.ruleWhy': {
    en: 'One revision matrix per project keeps changes traceable (playbook rule G-05).',
    es: 'Una sola matriz de revisión por proyecto mantiene los cambios trazables (regla G-05 del playbook).',
  },
  'client.approvals.awaiting': { en: '{n} waiting for your decision', es: '{n} esperan tu decisión' },
  'client.approvals.awaitingNone': { en: 'Nothing waiting for your decision', es: 'Nada espera tu decisión' },
  'client.approvals.source': { en: 'From {who}', es: 'De {who}' },
  'client.approvals.source.client': { en: 'you', es: 'ti' },
  'client.approvals.source.studio': { en: 'the studio', es: 'el estudio' },
  'client.approvals.source.founder': { en: 'Alejandra', es: 'Alejandra' },
  'client.approvals.decidedAt': { en: 'Decided {date}', es: 'Decidido el {date}' },
  'client.approvals.decide': { en: 'Your decision', es: 'Tu decisión' },
  'client.approvals.decideConfirm': { en: 'Confirm', es: 'Confirmar' },
  'client.approvals.decided': { en: 'Decision saved.', es: 'Decisión guardada.' },
  'client.approvals.addTitle': { en: 'Add a comment', es: 'Agregar un comentario' },
  'client.approvals.addDesc': {
    en: 'It becomes a line of the revision matrix and the studio answers it there.',
    es: 'Se convierte en una línea de la matriz de revisión y el estudio te responde ahí.',
  },
  'client.approvals.addStage': { en: 'Which stage', es: 'Qué etapa' },
  'client.approvals.addItem': { en: 'What it is about', es: 'Sobre qué' },
  'client.approvals.addItemHint': { en: 'For example: pendant lights over the dining table', es: 'Por ejemplo: colgantes sobre el comedor' },
  'client.approvals.addComment': { en: 'Your comment', es: 'Tu comentario' },
  'client.approvals.addSubmit': { en: 'Add to the matrix', es: 'Agregar a la matriz' },
  'client.approvals.added': { en: 'Comment added to the revision matrix.', es: 'Comentario agregado a la matriz de revisión.' },
  'client.approvals.addMissing': { en: 'Write what it is about and your comment.', es: 'Escribe sobre qué es y tu comentario.' },
  'client.approvals.gateTitle': { en: 'Approve the proposal for execution', es: 'Aprobar la propuesta para ejecución' },
  'client.approvals.gateDesc': {
    en: 'Construction may begin only after you approve the final design. This gate protects quality, schedule, scope and cost.',
    es: 'La obra solo puede empezar después de que apruebes el diseño final. Esta compuerta protege calidad, plazo, alcance y costo.',
  },
  'client.approvals.gateButton': { en: 'Approve for execution', es: 'Aprobar para ejecución' },
  'client.approvals.gateBlocked': { en: '{n} comment(s) are still in revision, so this cannot be approved yet.', es: 'Quedan {n} comentario(s) en revisión, así que todavía no se puede aprobar.' },
  'client.approvals.gateEmpty': { en: 'There is nothing to approve on this project yet.', es: 'Todavía no hay nada que aprobar en este proyecto.' },
  'client.approvals.gateReady': { en: 'Every comment is resolved. You can approve.', es: 'Todos los comentarios están resueltos. Puedes aprobar.' },
  'client.approvals.gateAlready': { en: 'You approved this design for execution.', es: 'Aprobaste este diseño para ejecución.' },
  'client.approvals.gateDone': { en: 'Approved for execution. The studio has been notified.', es: 'Aprobado para ejecución. El estudio fue notificado.' },
  'client.approvals.empty': { en: 'No comments yet', es: 'Todavía no hay comentarios' },
  'client.approvals.emptyDesc': {
    en: 'When the studio presents the scheme, every comment lands here.',
    es: 'Cuando el estudio presente el esquema, cada comentario quedará aquí.',
  },

  // C-04 messages
  'client.messages.title': { en: 'Messages', es: 'Mensajes' },
  'client.messages.desc': { en: 'The official channel with the studio.', es: 'El canal oficial con el estudio.' },
  'client.messages.threadLabel': { en: 'Conversation about {project}', es: 'Conversación sobre {project}' },
  'client.messages.tabsLabel': { en: 'Your projects', es: 'Tus proyectos' },
  'client.messages.you': { en: 'You', es: 'Tú' },
  'client.messages.composer': { en: 'Write a message', es: 'Escribe un mensaje' },
  'client.messages.send': { en: 'Send', es: 'Enviar' },
  'client.messages.sent': { en: 'Message sent.', es: 'Mensaje enviado.' },
  'client.messages.markRead': { en: 'Mark as read', es: 'Marcar como leído' },
  'client.messages.marked': { en: 'Conversation marked as read.', es: 'Conversación marcada como leída.' },
  'client.messages.unread': { en: 'New', es: 'Nuevo' },
  'client.messages.empty': { en: 'No messages yet', es: 'Todavía no hay mensajes' },
  'client.messages.emptyDesc': { en: 'Say hello: the studio answers here.', es: 'Escríbenos: el estudio responde por aquí.' },

  // C-05 payments
  'client.payments.title': { en: 'Payments', es: 'Pagos' },
  'client.payments.desc': { en: 'What has been billed, paid and is still open.', es: 'Lo facturado, lo pagado y lo que sigue abierto.' },
  'client.payments.caption': { en: 'Your payments', es: 'Tus pagos' },
  'client.payments.col.concept': { en: 'Concept', es: 'Concepto' },
  'client.payments.col.project': { en: 'Project', es: 'Proyecto' },
  'client.payments.col.due': { en: 'Due date', es: 'Vence' },
  'client.payments.col.amount': { en: 'Amount', es: 'Monto' },
  'client.payments.col.pending': { en: 'Outstanding', es: 'Por pagar' },
  'client.payments.col.status': { en: 'Status', es: 'Estado' },
  'client.payments.total.billed': { en: 'Billed', es: 'Facturado' },
  'client.payments.total.paid': { en: 'Paid', es: 'Pagado' },
  'client.payments.total.pending': { en: 'Outstanding', es: 'Por pagar' },
  'client.payments.overdue': { en: '{n} overdue', es: '{n} vencido(s)' },
  'client.payments.payOnline': { en: 'Pay online', es: 'Pagar en línea' },
  'client.payments.payOnlineWhat': { en: 'pay this invoice with a card (Stripe, coming later)', es: 'pagar esta cuenta con tarjeta (Stripe, más adelante)' },
  'client.payments.readOnly': { en: 'This page is read only: the studio issues every invoice.', es: 'Esta página es solo de lectura: el estudio emite cada cuenta de cobro.' },
  'client.payments.empty': { en: 'No payments yet', es: 'Todavía no hay pagos' },
  'client.payments.emptyDesc': { en: 'Invoices appear here as the studio issues them.', es: 'Las cuentas de cobro aparecen aquí a medida que el estudio las emite.' },

  // C-06 brief
  'client.brief.title': { en: 'Strategic brief', es: 'Brief estratégico' },
  'client.brief.desc': { en: 'Tell us how you live the space. This is where every project starts.', es: 'Cuéntanos cómo vives el espacio. Aquí empieza todo proyecto.' },
  'client.brief.intro': {
    en: 'Answer what you can; you may come back and finish later. The studio reads it before the session.',
    es: 'Responde lo que puedas; puedes volver y terminarlo después. El estudio lo lee antes de la sesión.',
  },
  'client.brief.save': { en: 'Save the brief', es: 'Guardar el brief' },
  'client.brief.saved': { en: 'Brief saved.', es: 'Brief guardado.' },
  'client.brief.answered': { en: '{done} of {total} answered', es: '{done} de {total} respondidas' },
  'client.brief.noEngagement': { en: 'The brief is not open yet', es: 'El brief aún no está abierto' },
  'client.brief.noEngagementDesc': {
    en: 'The studio opens your brief when the project is activated.',
    es: 'El estudio abre tu brief cuando el proyecto se activa.',
  },
};
