import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'work.nav.work': { en: 'Work', es: 'Trabajo' },
  'work.title': { en: 'Work', es: 'Trabajo' },
  'work.subtitle': { en: 'Every task of the studio in the views the team already knows: list, board, timeline and calendar. Changes are live for everyone.', es: 'Todas las tareas del estudio en las vistas que el equipo ya conoce: lista, tablero, cronograma y calendario. Los cambios se ven en vivo para todos.' },
  'work.project.subtitle': { en: '{client} · {n} tasks in {sections} sections · {open} open', es: '{client} · {n} tareas en {sections} secciones · {open} abiertas' },
  'work.project.notFound': { en: 'This project does not exist', es: 'Este proyecto no existe' },
  'work.openProject': { en: 'Open a project…', es: 'Abrir un proyecto…' },
  'work.allWork': { en: 'All work', es: 'Todo el trabajo' },
  'work.added': { en: 'Task added', es: 'Tarea agregada' },
  'work.moved': { en: 'Task moved', es: 'Tarea movida' },
  'work.cannotMove': { en: 'Tasks cannot be moved into "{group}"', es: 'No se pueden mover tareas a "{group}"' },
  'work.saved': { en: 'Saved', es: 'Guardado' },
  'work.viewSaved': { en: 'View "{name}" saved', es: 'Vista "{name}" guardada' },
  'work.viewDeleted': { en: 'View deleted', es: 'Vista eliminada' },
  'work.presence': { en: 'Who is here', es: 'Quién está aquí' },

  // W-03 new project from template (D-062)
  'work.nav.new': { en: 'New project', es: 'Nuevo proyecto' },
  'work.new.title': { en: 'New project from template', es: 'Nuevo proyecto desde plantilla' },
  'work.new.subtitle': { en: 'The studio’s own workflow, applied to a new project: the phases, the task tree, the owners and the deliverables, without duplicating anything by hand.', es: 'El flujo de trabajo del estudio aplicado a un proyecto nuevo: las fases, el árbol de tareas, los responsables y los entregables, sin duplicar nada a mano.' },
  'work.new.steps': { en: 'Steps', es: 'Pasos' },
  'work.new.step.template': { en: 'Template', es: 'Plantilla' },
  'work.new.step.project': { en: 'Project', es: 'Proyecto' },
  'work.new.step.phases': { en: 'Phases', es: 'Fases' },
  'work.new.step.zones': { en: 'Zones', es: 'Zonas' },
  'work.new.step.review': { en: 'Review', es: 'Revisión' },
  'work.new.template': { en: 'Project template', es: 'Plantilla de proyecto' },
  'work.new.templateHint': { en: 'One template today: the founder’s workflow for every project, in English and Spanish.', es: 'Hoy hay una sola plantilla: el flujo de trabajo de la fundadora para cada proyecto, en inglés y español.' },
  'work.new.projectHint': { en: 'The project row this creates; budget, location and dates are filled in later on the project itself.', es: 'El proyecto que se va a crear; presupuesto, ubicación y fechas se completan después en el proyecto mismo.' },
  'work.new.phasesHint': { en: 'All phases are included by default. Leave out the ones this project does not need.', es: 'Todas las fases vienen incluidas. Quita las que este proyecto no necesita.' },
  'work.new.zonesHint': { en: 'The tasks the studio repeats per space (references, 3D model, the nine-lens deep design) are created once per zone. Add a zone of your own if this project has one.', es: 'Las tareas que el estudio repite por espacio (referentes, modelado 3D, diseño a profundidad) se crean una vez por zona. Agrega una zona propia si este proyecto la tiene.' },
  'work.new.reviewHint': { en: 'What will be written when you create the project.', es: 'Lo que se va a escribir al crear el proyecto.' },
  'work.new.name': { en: 'Project name', es: 'Nombre del proyecto' },
  'work.new.client': { en: 'Client', es: 'Cliente' },
  'work.new.pickClient': { en: 'Choose a client…', es: 'Elige un cliente…' },
  'work.new.type': { en: 'Project type', es: 'Tipo de proyecto' },
  'work.new.type.residential': { en: 'Residential', es: 'Residencial' },
  'work.new.type.commercial': { en: 'Commercial', es: 'Comercial' },
  'work.new.type.hospitality': { en: 'Hospitality', es: 'Hospitalidad' },
  'work.new.type.wellness': { en: 'Wellness', es: 'Bienestar' },
  'work.new.type.lighting-product': { en: 'Lighting product', es: 'Producto de iluminación' },
  'work.new.lead': { en: 'Lead designer', es: 'Diseñador responsable' },
  'work.new.service': { en: 'Service', es: 'Servicio' },
  'work.new.addZone': { en: 'Add a zone', es: 'Agregar una zona' },
  'work.new.zonesCount': { en: '{zones} zones selected · {tasks} tasks will be created', es: '{zones} zonas seleccionadas · se crearán {tasks} tareas' },
  'work.new.noZones': { en: 'No zones: the per-space tasks are created once', es: 'Sin zonas: las tareas por espacio se crean una sola vez' },
  'work.new.phaseHint': { en: '{tasks} tasks · owner {owner}', es: '{tasks} tareas · responsable {owner}' },
  'work.new.count.phases': { en: 'Phases in the template', es: 'Fases en la plantilla' },
  'work.new.count.templateTasks': { en: 'Tasks in the template', es: 'Tareas en la plantilla' },
  'work.new.count.zoneScoped': { en: 'Repeated per zone', es: 'Repetidas por zona' },
  'work.new.count.sections': { en: 'Sections', es: 'Secciones' },
  'work.new.count.tasks': { en: 'Tasks', es: 'Tareas' },
  'work.new.count.zones': { en: 'Zones', es: 'Zonas' },
  'work.new.count.deliverables': { en: 'Deliverables', es: 'Entregables' },
  'work.new.count.owners': { en: 'Owners', es: 'Responsables' },
  'work.new.missing': { en: 'Missing', es: 'Falta' },
  'work.new.back': { en: 'Back', es: 'Atrás' },
  'work.new.next': { en: 'Next', es: 'Siguiente' },
  'work.new.create': { en: 'Create the project', es: 'Crear el proyecto' },
  'work.new.creating': { en: 'Creating…', es: 'Creando…' },
  'work.new.created': { en: 'Project created: {n} tasks in {sections} sections', es: 'Proyecto creado: {n} tareas en {sections} secciones' },
  'work.new.noPermission': { en: 'Only the founder and operations can create a project.', es: 'Solo la fundadora y operaciones pueden crear un proyecto.' },
  'work.new.summary': { en: 'Created from the template "{template}" with {zones} zones and {tasks} tasks. Budget, location and dates are still to be set.', es: 'Creado desde la plantilla "{template}" con {zones} zonas y {tasks} tareas. Faltan presupuesto, ubicación y fechas.' },
  'work.new.open': { en: 'New project from template', es: 'Nuevo proyecto desde plantilla' },
};
