import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'dev.nav.components': { en: 'Components', es: 'Componentes' },
  'dev.nav.specs': { en: 'Page specs', es: 'Especificaciones' },
  'dev.summary': { en: '{shown} of {total}', es: '{shown} de {total}' },
  'dev.tier.atom': { en: 'Atoms', es: 'Átomos' },
  'dev.tier.molecule': { en: 'Molecules', es: 'Moléculas' },
  'dev.tier.organism': { en: 'Organisms', es: 'Organismos' },
  'dev.tier.template': { en: 'Templates', es: 'Plantillas' },

  'dev.components.title': { en: 'Component library', es: 'Biblioteca de componentes' },
  'dev.components.subtitle': { en: '{count} components, each rendered from its meta with a live example. Pages never hand-roll UI: if it is not here, add it here first.', es: '{count} componentes, cada uno renderizado desde su meta con un ejemplo vivo. Las páginas nunca improvisan UI: si no está aquí, se agrega aquí primero.' },
  'dev.components.search': { en: 'Search components…', es: 'Buscar componentes…' },
  'dev.components.tiers': { en: 'Component tiers', es: 'Niveles de componentes' },
  'dev.components.all': { en: 'All', es: 'Todos' },
  'dev.components.none': { en: 'No component matches', es: 'Ningún componente coincide' },
  'dev.components.noExample': { en: 'No example', es: 'Sin ejemplo' },
  'dev.components.props': { en: 'Props', es: 'Props' },
  'dev.components.noProps': { en: 'No props.', es: 'Sin props.' },
  'dev.components.a11y': { en: 'Accessibility and inputs', es: 'Accesibilidad y entradas' },
  'dev.components.usages': { en: 'Used by', es: 'Usado por' },

  'dev.specs.title': { en: 'Page specs', es: 'Especificaciones de página' },
  'dev.specs.subtitle': { en: 'Every registered route with status, roles, actions and completeness. Same data as window.__aluzina.routes.', es: 'Cada ruta registrada con estado, roles, acciones y completitud. Los mismos datos que window.__aluzina.routes.' },
  'dev.specs.routes': { en: 'Routes', es: 'Rutas' },
  'dev.specs.built': { en: 'Built', es: 'Construidas' },
  'dev.specs.stubs': { en: 'Stubs', es: 'Borradores' },
  'dev.specs.actions': { en: 'Actions declared', es: 'Acciones declaradas' },
  'dev.specs.search': { en: 'Search code, name, path, role…', es: 'Buscar código, nombre, ruta, rol…' },
  'dev.specs.surface': { en: 'Surface', es: 'Superficie' },
  'dev.specs.allSurfaces': { en: 'All surfaces', es: 'Todas las superficies' },
  'dev.specs.col.code': { en: 'Code', es: 'Código' },
  'dev.specs.col.name': { en: 'Page', es: 'Página' },
  'dev.specs.col.path': { en: 'Path', es: 'Ruta' },
  'dev.specs.col.surface': { en: 'Surface', es: 'Superficie' },
  'dev.specs.col.status': { en: 'Status', es: 'Estado' },
  'dev.specs.col.roles': { en: 'Roles', es: 'Roles' },
  'dev.specs.col.actions': { en: 'Actions', es: 'Acciones' },
  'dev.specs.col.completeness': { en: 'Spec', es: 'Spec' },
  'dev.specs.shell': { en: 'Shell', es: 'Shell' },
  'dev.specs.permission': { en: 'Permission', es: 'Permiso' },
  'dev.specs.navGroup': { en: 'Nav group', es: 'Grupo de menú' },
  'dev.specs.dataTables': { en: 'Data tables', es: 'Tablas de datos' },
  'dev.specs.components': { en: 'Components', es: 'Componentes' },
  'dev.specs.missing': { en: 'Missing: {items}', es: 'Falta: {items}' },
  'dev.specs.complete': { en: 'Complete', es: 'Completa' },
  'dev.specs.layout': { en: 'Layout', es: 'Estructura' },
  'dev.specs.logic': { en: 'Logic', es: 'Lógica' },
};
