import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'dev.nav.components': { en: 'Components', es: 'Componentes' },
  'dev.nav.specs': { en: 'Page specs', es: 'Especificaciones' },
  'dev.nav.multiuser': { en: 'Multiuser', es: 'Multiusuario' },
  'dev.multiuser.title': { en: 'Multiuser and realtime', es: 'Multiusuario y tiempo real' },
  'dev.multiuser.subtitle': { en: 'Two tabs, two people: the mock provider fans every write out over a BroadcastChannel and presence heartbeats say who is where (D-023).', es: 'Dos pestañas, dos personas: el proveedor mock propaga cada escritura por un BroadcastChannel y los latidos de presencia dicen quién está dónde (D-023).' },
  'dev.multiuser.howTitle': { en: 'How to test it', es: 'Cómo probarlo' },
  'dev.multiuser.step1': { en: 'Open a second tab as another demo user with the buttons below (the ?as= query picks the person for that tab only).', es: 'Abre una segunda pestaña como otro usuario demo con los botones de abajo (la consulta ?as= elige la persona solo para esa pestaña).' },
  'dev.multiuser.step2': { en: 'Change a task in one tab (status, assignee, a comment): the other tab updates within a second and the presence bar shows both people.', es: 'Cambia una tarea en una pestaña (estado, asignado, un comentario): la otra se actualiza en menos de un segundo y la barra de presencia muestra a ambas personas.' },
  'dev.multiuser.step3': { en: 'Edit the same task in both tabs: the later write wins and the loser sees a toast naming who overwrote it (D-024).', es: 'Edita la misma tarea en ambas pestañas: gana la última escritura y quien pierde ve un aviso con el nombre de quien la sobrescribió (D-024).' },
  'dev.multiuser.openAs': { en: 'Open a tab as {role}', es: 'Abrir pestaña como {role}' },
  'dev.multiuser.reset': { en: 'Reset demo data', es: 'Restablecer datos demo' },
  'dev.multiuser.resetDone': { en: 'Demo data re-seeded in every tab', es: 'Datos demo restablecidos en todas las pestañas' },
  'dev.multiuser.dataChannel': { en: 'Data channel', es: 'Canal de datos' },
  'dev.multiuser.presenceChannel': { en: 'Presence channel', es: 'Canal de presencia' },
  'dev.multiuser.heartbeat': { en: 'Heartbeat / expiry', es: 'Latido / expiración' },
  'dev.multiuser.thisTab': { en: 'This tab', es: 'Esta pestaña' },
  'dev.multiuser.presenceTitle': { en: 'Who is here', es: 'Quién está aquí' },
  'dev.multiuser.presenceSub': { en: '{n} people across open tabs', es: '{n} personas en las pestañas abiertas' },
  'dev.multiuser.activityTitle': { en: 'Last 20 activity rows', es: 'Últimas 20 filas de actividad' },
  'dev.multiuser.activitySub': { en: 'Written by the provider on every update, one row per changed field.', es: 'Escritas por el proveedor en cada actualización, una fila por campo cambiado.' },
  'dev.multiuser.col.person': { en: 'Person', es: 'Persona' },
  'dev.multiuser.col.route': { en: 'Route', es: 'Ruta' },
  'dev.multiuser.col.tabs': { en: 'Tabs', es: 'Pestañas' },
  'dev.multiuser.col.seen': { en: 'Last seen', es: 'Visto' },
  'dev.multiuser.col.when': { en: 'When', es: 'Cuándo' },
  'dev.multiuser.col.actor': { en: 'Who', es: 'Quién' },
  'dev.multiuser.col.row': { en: 'Row', es: 'Fila' },
  'dev.multiuser.col.field': { en: 'Field', es: 'Campo' },
  'dev.multiuser.col.change': { en: 'Change', es: 'Cambio' },
  'dev.summary': { en: '{shown} of {total}', es: '{shown} de {total}' },
  'dev.tier.atom': { en: 'Atoms', es: 'Átomos' },
  'dev.tier.molecule': { en: 'Molecules', es: 'Moléculas' },
  'dev.tier.organism': { en: 'Organisms', es: 'Organismos' },
  'dev.tier.template': { en: 'Templates', es: 'Plantillas' },

  'dev.components.title': { en: 'Component library', es: 'Biblioteca de componentes' },
  'dev.components.subtitle': { en: '{count} components, each rendered from its meta with a live example. Pages never hand-roll UI: if it is not here, add it here first.', es: '{count} componentes, cada uno renderizado desde su meta con un ejemplo vivo. Las páginas nunca improvisan UI: si no está aquí, se agrega aquí primero.' },
  'dev.components.search': { en: 'Search components…', es: 'Buscar componentes…' },
  'dev.components.tiers': { en: 'Component tiers', es: 'Niveles de componentes' },
  'dev.components.all': { en: 'All', es: 'Todos' },
  'dev.components.none': { en: 'No component matches', es: 'Ningún componente coincide' },
  'dev.components.noExample': { en: 'No example', es: 'Sin ejemplo' },
  'dev.components.props': { en: 'Props', es: 'Props' },
  'dev.components.noProps': { en: 'No props.', es: 'Sin props.' },
  'dev.components.a11y': { en: 'Accessibility and inputs', es: 'Accesibilidad y entradas' },
  'dev.components.usages': { en: 'Used by', es: 'Usado por' },

  'dev.specs.title': { en: 'Page specs', es: 'Especificaciones de página' },
  'dev.specs.subtitle': { en: 'Every registered route with status, roles, actions and completeness. Same data as window.__aluzina.routes.', es: 'Cada ruta registrada con estado, roles, acciones y completitud. Los mismos datos que window.__aluzina.routes.' },
  'dev.specs.routes': { en: 'Routes', es: 'Rutas' },
  'dev.specs.built': { en: 'Built', es: 'Construidas' },
  'dev.specs.stubs': { en: 'Stubs', es: 'Borradores' },
  'dev.specs.actions': { en: 'Actions declared', es: 'Acciones declaradas' },
  'dev.specs.search': { en: 'Search code, name, path, role…', es: 'Buscar código, nombre, ruta, rol…' },
  'dev.specs.surface': { en: 'Surface', es: 'Superficie' },
  'dev.specs.allSurfaces': { en: 'All surfaces', es: 'Todas las superficies' },
  'dev.specs.col.code': { en: 'Code', es: 'Código' },
  'dev.specs.col.name': { en: 'Page', es: 'Página' },
  'dev.specs.col.path': { en: 'Path', es: 'Ruta' },
  'dev.specs.col.surface': { en: 'Surface', es: 'Superficie' },
  'dev.specs.col.status': { en: 'Status', es: 'Estado' },
  'dev.specs.col.roles': { en: 'Roles', es: 'Roles' },
  'dev.specs.col.actions': { en: 'Actions', es: 'Acciones' },
  'dev.specs.col.completeness': { en: 'Spec', es: 'Spec' },
  'dev.specs.shell': { en: 'Shell', es: 'Shell' },
  'dev.specs.permission': { en: 'Permission', es: 'Permiso' },
  'dev.specs.navGroup': { en: 'Nav group', es: 'Grupo de menú' },
  'dev.specs.dataTables': { en: 'Data tables', es: 'Tablas de datos' },
  'dev.specs.components': { en: 'Components', es: 'Componentes' },
  'dev.specs.missing': { en: 'Missing: {items}', es: 'Falta: {items}' },
  'dev.specs.complete': { en: 'Complete', es: 'Completa' },
  'dev.specs.layout': { en: 'Layout', es: 'Estructura' },
  'dev.specs.logic': { en: 'Logic', es: 'Lógica' },
};
