import type { StringTable } from '../../i18n/types';

/** QA / dev-tool pages: D-09 actions registry, D-14 tokens, D-11 testing hub (P-13: en + es). */
export const strings: StringTable = {
  'qa.nav.actions': { en: 'Actions', es: 'Acciones' },
  'qa.nav.tokens': { en: 'Tokens', es: 'Tokens' },
  'qa.nav.testing': { en: 'Testing hub', es: 'Centro de pruebas' },
  'qa.summary': { en: '{shown} of {total}', es: '{shown} de {total}' },
  'qa.copied': { en: 'Copied to the clipboard', es: 'Copiado al portapapeles' },
  'qa.copyFailed': { en: 'The clipboard is not available in this browser', es: 'El portapapeles no está disponible en este navegador' },
  'qa.none': { en: 'Nothing matches the filters', es: 'Nada coincide con los filtros' },
  'qa.noneDesc': { en: 'Clear the search or the filters to see everything again.', es: 'Borra la búsqueda o los filtros para volver a verlo todo.' },
  'qa.unknown': { en: 'Unknown', es: 'Desconocido' },

  // D-09 Actions registry
  'qa.actions.title': { en: 'Actions registry', es: 'Registro de acciones' },
  'qa.actions.subtitle': { en: 'Every action declared in a page spec, joined with the handlers registered right now. This list is the WebMCP tool surface and the voice vocabulary (P-05, P-06, D-036).', es: 'Cada acción declarada en una especificación de página, cruzada con los manejadores registrados ahora mismo. Esta lista es la superficie de herramientas WebMCP y el vocabulario de voz (P-05, P-06, D-036).' },
  'qa.actions.declared': { en: 'Declared', es: 'Declaradas' },
  'qa.actions.distinct': { en: 'Distinct ids', es: 'Ids distintos' },
  'qa.actions.liveNow': { en: 'Live now', es: 'Activas ahora' },
  'qa.actions.withPermission': { en: 'With permission', es: 'Con permiso' },
  'qa.actions.withParams': { en: 'With params', es: 'Con parámetros' },
  'qa.actions.search': { en: 'Search id, intent, label…', es: 'Buscar id, intención, etiqueta…' },
  'qa.actions.surface': { en: 'Surface', es: 'Superficie' },
  'qa.actions.allSurfaces': { en: 'All surfaces', es: 'Todas las superficies' },
  'qa.actions.module': { en: 'Module', es: 'Módulo' },
  'qa.actions.allModules': { en: 'All modules', es: 'Todos los módulos' },
  'qa.actions.permission': { en: 'Permission', es: 'Permiso' },
  'qa.actions.allPermissions': { en: 'Any permission', es: 'Cualquier permiso' },
  'qa.actions.noPermission': { en: 'No permission', es: 'Sin permiso' },
  'qa.actions.liveOnly': { en: 'Live only', es: 'Solo activas' },
  'qa.actions.export': { en: 'Export all as JSON', es: 'Exportar todo en JSON' },
  'qa.actions.exported': { en: 'Downloaded {file}', es: 'Descargado {file}' },
  'qa.actions.col.id': { en: 'Action id', es: 'Id de acción' },
  'qa.actions.col.page': { en: 'Page', es: 'Página' },
  'qa.actions.col.path': { en: 'Path', es: 'Ruta' },
  'qa.actions.col.label': { en: 'Label', es: 'Etiqueta' },
  'qa.actions.col.intent': { en: 'Intent phrase', es: 'Frase de intención' },
  'qa.actions.col.permission': { en: 'Permission', es: 'Permiso' },
  'qa.actions.col.params': { en: 'Params', es: 'Parámetros' },
  'qa.actions.col.live': { en: 'Live', es: 'Activa' },
  'qa.actions.live': { en: 'Live', es: 'Activa' },
  'qa.actions.notLive': { en: 'Not mounted', es: 'No montada' },
  'qa.actions.caption': { en: 'Declared actions', es: 'Acciones declaradas' },
  'qa.actions.drawer.definition': { en: 'Definition', es: 'Definición' },
  'qa.actions.drawer.params': { en: 'Parameters', es: 'Parámetros' },
  'qa.actions.drawer.noParams': { en: 'This action takes no parameters.', es: 'Esta acción no recibe parámetros.' },
  'qa.actions.drawer.run': { en: 'Run', es: 'Ejecutar' },
  'qa.actions.drawer.running': { en: 'Running…', es: 'Ejecutando…' },
  'qa.actions.drawer.result': { en: 'Result', es: 'Resultado' },
  'qa.actions.drawer.error': { en: 'Error', es: 'Error' },
  'qa.actions.drawer.copyTool': { en: 'Copy as WebMCP tool JSON', es: 'Copiar como JSON de herramienta WebMCP' },
  'qa.actions.drawer.notLiveHint': { en: 'No page has registered a handler for this id right now. Open the page that declares it, then come back.', es: 'Ninguna página tiene un manejador registrado para este id ahora mismo. Abre la página que lo declara y vuelve.' },
  'qa.actions.drawer.deniedHint': { en: 'You lack {permission}; switch role to run it.', es: 'Te falta {permission}; cambia de rol para ejecutarla.' },
  'qa.actions.drawer.openPage': { en: 'Open the page', es: 'Abrir la página' },
  'qa.actions.drawer.alsoOn': { en: 'Also declared on', es: 'También declarada en' },
  'qa.actions.notFound': { en: 'No declared action with the id {id}', es: 'No hay ninguna acción declarada con el id {id}' },
  'qa.actions.selfRun': { en: 'qa.runAction cannot run itself', es: 'qa.runAction no puede ejecutarse a sí misma' },
  'qa.actions.ran': { en: 'Ran {id}', es: 'Ejecutada {id}' },

  // D-14 Tokens
  'qa.tokens.title': { en: 'Design tokens', es: 'Tokens de diseño' },
  'qa.tokens.subtitle': { en: 'The design system as data, read from src/design/tokens.ts — the one source every CSS variable is generated from (P-07). Read-only here: tokens change in the source file.', es: 'El sistema de diseño como datos, leído de src/design/tokens.ts: la única fuente de la que se genera cada variable CSS (P-07). Aquí es solo lectura: los tokens se cambian en el archivo fuente.' },
  'qa.tokens.search': { en: 'Search token or variable…', es: 'Buscar token o variable…' },
  'qa.tokens.copy': { en: 'Copy variable', es: 'Copiar variable' },
  'qa.tokens.edit': { en: 'Edit token', es: 'Editar token' },
  'qa.tokens.editWhat': { en: 'write the value back into src/design/tokens.ts and regenerate tokens.css', es: 'escribir el valor de vuelta en src/design/tokens.ts y regenerar tokens.css' },
  'qa.tokens.colors': { en: 'Colours', es: 'Colores' },
  'qa.tokens.colorsSub': { en: 'Light and dark side by side. Every pair is generated into tokens.css as --color-*.', es: 'Claro y oscuro lado a lado. Cada par se genera en tokens.css como --color-*.' },
  'qa.tokens.light': { en: 'Light', es: 'Claro' },
  'qa.tokens.dark': { en: 'Dark', es: 'Oscuro' },
  'qa.tokens.contrast': { en: 'Contrast (text on surface)', es: 'Contraste (texto sobre superficie)' },
  'qa.tokens.contrastSub': { en: 'WCAG 2.1 contrast ratio for every text-on-surface pair, in both themes. Under 4.5:1 is flagged.', es: 'Relación de contraste WCAG 2.1 para cada par texto-sobre-superficie, en ambos temas. Por debajo de 4.5:1 se marca.' },
  'qa.tokens.col.pair': { en: 'Pair', es: 'Par' },
  'qa.tokens.col.theme': { en: 'Theme', es: 'Tema' },
  'qa.tokens.col.ratio': { en: 'Ratio', es: 'Relación' },
  'qa.tokens.col.verdict': { en: 'AA (4.5:1)', es: 'AA (4.5:1)' },
  'qa.tokens.pass': { en: 'Pass', es: 'Cumple' },
  'qa.tokens.fail': { en: 'Below 4.5', es: 'Bajo 4.5' },
  'qa.tokens.largeOnly': { en: 'Large text only', es: 'Solo texto grande' },
  'qa.tokens.type': { en: 'Typography', es: 'Tipografía' },
  'qa.tokens.typeSub': { en: 'Three families and the rem ladder the library uses. Sizes are computed at the previewed --scale, never hard-coded per page (P-01).', es: 'Tres familias y la escalera en rem que usa la biblioteca. Los tamaños se calculan con el --scale previsualizado, nunca fijos por página (P-01).' },
  'qa.tokens.sample': { en: 'Emotional lighting for interiors — Iluminación emocional', es: 'Emotional lighting for interiors — Iluminación emocional' },
  'qa.tokens.col.rem': { en: 'rem', es: 'rem' },
  'qa.tokens.col.px': { en: 'px at this scale', es: 'px en esta escala' },
  'qa.tokens.col.used': { en: 'Used for', es: 'Se usa para' },
  'qa.tokens.use.0.75': { en: 'Badges, chips, table meta', es: 'Insignias, chips, meta de tabla' },
  'qa.tokens.use.0.8125': { en: 'Captions, code, section labels', es: 'Leyendas, código, etiquetas de sección' },
  'qa.tokens.use.0.875': { en: 'Dense tables and sidebars', es: 'Tablas densas y barras laterales' },
  'qa.tokens.use.0.9375': { en: 'Secondary body, list rows', es: 'Cuerpo secundario, filas de lista' },
  'qa.tokens.use.1': { en: 'Body text (the 16 px floor at 1920)', es: 'Texto de cuerpo (el mínimo de 16 px a 1920)' },
  'qa.tokens.use.1.125': { en: 'Lead paragraphs, stat values', es: 'Párrafos de entrada, valores de indicadores' },
  'qa.tokens.use.1.25': { en: 'Card titles', es: 'Títulos de tarjeta' },
  'qa.tokens.use.1.5': { en: 'Section headings', es: 'Encabezados de sección' },
  'qa.tokens.use.2': { en: 'Page titles', es: 'Títulos de página' },
  'qa.tokens.use.2.5': { en: 'Hub hero', es: 'Portada del hub' },
  'qa.tokens.spacing': { en: 'Spacing', es: 'Espaciado' },
  'qa.tokens.spacingSub': { en: 'Eight steps, all in rem so they grow with --scale.', es: 'Ocho pasos, todos en rem para que crezcan con --scale.' },
  'qa.tokens.radii': { en: 'Radii', es: 'Radios' },
  'qa.tokens.radiiSub': { en: 'Four corner radii; pill is the badge and chip shape.', es: 'Cuatro radios de esquina; pill es la forma de insignias y chips.' },
  'qa.tokens.shadows': { en: 'Shadows', es: 'Sombras' },
  'qa.tokens.shadowsSub': { en: 'There are no shadow tokens yet: the six elevations below are hard-coded in component CSS. Requested for the next pass so elevation is data like everything else.', es: 'Todavía no hay tokens de sombra: las seis elevaciones de abajo están fijas en el CSS de los componentes. Solicitados para la próxima pasada para que la elevación sea dato como todo lo demás.' },
  'qa.tokens.col.where': { en: 'Where', es: 'Dónde' },
  'qa.tokens.col.value': { en: 'Value', es: 'Valor' },
  'qa.tokens.scale': { en: 'Responsive scale bands', es: 'Bandas de escala responsiva' },
  'qa.tokens.scaleSub': { en: 'One band per matrix width (P-01). --scale multiplies the 16 px root size; everything else is in rem, so type, spacing and targets grow together.', es: 'Una banda por ancho de la matriz (P-01). --scale multiplica el tamaño raíz de 16 px; todo lo demás está en rem, así que tipo, espaciado y objetivos crecen juntos.' },
  'qa.tokens.preview': { en: 'Preview band', es: 'Banda de vista previa' },
  'qa.tokens.previewCurrent': { en: 'Current viewport ({width} px)', es: 'Viewport actual ({width} px)' },
  'qa.tokens.col.band': { en: 'From width', es: 'Desde ancho' },
  'qa.tokens.col.scale': { en: 'Scale', es: 'Escala' },
  'qa.tokens.col.root': { en: 'Root size', es: 'Tamaño raíz' },
  'qa.tokens.col.target': { en: 'Target', es: 'Objetivo' },
  'qa.tokens.here': { en: 'You are here', es: 'Estás aquí' },
  'qa.tokens.measured': { en: 'Measured in this tab', es: 'Medido en esta pestaña' },
  'qa.tokens.rootMeasured': { en: 'Root font size right now', es: 'Tamaño de fuente raíz ahora' },
  'qa.tokens.targetMeasured': { en: 'Minimum target right now', es: 'Objetivo mínimo ahora' },
  'qa.tokens.targetTitle': { en: 'Target size and focus ring', es: 'Tamaño de objetivo y anillo de foco' },
  'qa.tokens.targetSub': { en: '--target is the 44 px minimum every control must meet (P-03); --focus-ring never drops below 3 px (P-01).', es: '--target es el mínimo de 44 px que debe cumplir cada control (P-03); --focus-ring nunca baja de 3 px (P-01).' },
  'qa.tokens.targetDemo': { en: 'Tab to me: 44 px tall, visible ring', es: 'Tabula hasta aquí: 44 px de alto, anillo visible' },
  'qa.tokens.previewedScale': { en: 'Previewing the {width} px band (scale {scale})', es: 'Vista previa de la banda de {width} px (escala {scale})' },

  // D-11 Testing hub
  'qa.testing.title': { en: 'Testing hub', es: 'Centro de pruebas' },
  'qa.testing.subtitle': { en: 'Every registered route against the responsive matrix (P-01) and the spec checklist (P-02). A tick means the width is recorded in spec.checkedAt, not that a robot measured it.', es: 'Cada ruta registrada frente a la matriz responsiva (P-01) y la lista de la especificación (P-02). Un tic significa que el ancho está registrado en spec.checkedAt, no que lo haya medido un robot.' },
  'qa.testing.routes': { en: 'Routes', es: 'Rutas' },
  'qa.testing.fully': { en: 'Fully checked', es: 'Verificadas del todo' },
  'qa.testing.fullyHint': { en: 'all 7 widths recorded', es: 'los 7 anchos registrados' },
  'qa.testing.avg': { en: 'Average completeness', es: 'Completitud media' },
  'qa.testing.cells': { en: 'Width cells checked', es: 'Celdas de ancho verificadas' },
  'qa.testing.search': { en: 'Search code, page, path…', es: 'Buscar código, página, ruta…' },
  'qa.testing.surface': { en: 'Surface', es: 'Superficie' },
  'qa.testing.allSurfaces': { en: 'All surfaces', es: 'Todas las superficies' },
  'qa.testing.incompleteOnly': { en: 'Incomplete only', es: 'Solo incompletas' },
  'qa.testing.caption': { en: 'Responsive and spec matrix', es: 'Matriz responsiva y de especificación' },
  'qa.testing.col.code': { en: 'Code', es: 'Código' },
  'qa.testing.col.page': { en: 'Page', es: 'Página' },
  'qa.testing.col.spec': { en: 'Spec', es: 'Espec.' },
  'qa.testing.col.lang': { en: 'EN / ES', es: 'EN / ES' },
  'qa.testing.col.placeholders': { en: 'Placeholders', es: 'Marcadores' },
  'qa.testing.col.shots': { en: 'Screenshots', es: 'Capturas' },
  'qa.testing.checkedAt': { en: 'checked at {width} px', es: 'verificado a {width} px' },
  'qa.testing.notCheckedAt': { en: 'not recorded at {width} px', es: 'no registrado a {width} px' },
  'qa.testing.placeholdersHint': { en: 'Counted by visiting the page; nothing to read from here yet.', es: 'Se cuentan al visitar la página; todavía no hay nada que leer desde aquí.' },
  'qa.testing.langHint': { en: 'English is complete by construction (the en key is required); Spanish coverage per page is not measurable at runtime yet.', es: 'El inglés está completo por construcción (la clave en es obligatoria); la cobertura en español por página aún no se puede medir en tiempo de ejecución.' },
  'qa.testing.shotsWhat': { en: 'read the screenshot manifest from docs/screenshots at deploy time and tick the pages that have captures', es: 'leer el manifiesto de capturas de docs/screenshots al desplegar y marcar las páginas que tienen capturas' },
  'qa.testing.shotsButton': { en: 'Load screenshot manifest', es: 'Cargar manifiesto de capturas' },
  'qa.testing.shotsNote': { en: 'Screenshot availability comes from docs/screenshots/<CODE>/, which the running app cannot read; the column stays “—” until the build writes a manifest.', es: 'La disponibilidad de capturas viene de docs/screenshots/<CODE>/, que la app en ejecución no puede leer; la columna queda en «—» hasta que el build escriba un manifiesto.' },
  'qa.testing.drawer.missing': { en: 'Missing spec checks', es: 'Comprobaciones de especificación que faltan' },
  'qa.testing.drawer.complete': { en: 'Every spec check passes.', es: 'Todas las comprobaciones de la especificación pasan.' },
  'qa.testing.drawer.widths': { en: 'Widths', es: 'Anchos' },
  'qa.testing.drawer.recorded': { en: 'Recorded', es: 'Registrados' },
  'qa.testing.drawer.missingWidths': { en: 'Not recorded', es: 'Sin registrar' },
  'qa.testing.drawer.open': { en: 'Open at {width}', es: 'Abrir a {width}' },
  'qa.testing.drawer.openHint': { en: 'Opens a window about {width} px wide as {role}; the browser may clamp the size.', es: 'Abre una ventana de unos {width} px de ancho como {role}; el navegador puede ajustar el tamaño.' },
  'qa.testing.drawer.paramRoute': { en: 'This route takes URL parameters, so it cannot be opened from here without an id.', es: 'Esta ruta recibe parámetros de URL, así que no se puede abrir desde aquí sin un id.' },
  'qa.testing.drawer.popupBlocked': { en: 'The browser blocked the popup; allow popups for this site.', es: 'El navegador bloqueó la ventana emergente; permite emergentes para este sitio.' },
  'qa.testing.drawer.simulator': { en: 'Open in the demo simulator', es: 'Abrir en el simulador de demo' },
  'qa.testing.drawer.simulatorWhat': { en: 'frame this route in the D-08 demo simulator, which is not registered yet', es: 'enmarcar esta ruta en el simulador de demo D-08, que todavía no está registrado' },
  'qa.testing.feedback': { en: 'Feedback and bugs (P-08)', es: 'Comentarios y errores (P-08)' },
  'qa.testing.feedbackBody': { en: 'Testers are meant to annotate the product itself, not a spreadsheet: an element-pinned comment, request or bug carrying author, role, page code, element path, viewport, theme and a screenshot. Agents then triage from the store — weighing who wrote it (Justin binding, the owner binding on business rules, staff a request, a customer a signal) and recording triage, note and decision reference before changing anything.', es: 'Quien prueba debe anotar sobre el producto mismo, no en una hoja de cálculo: un comentario, petición o error anclado a un elemento con autor, rol, código de página, ruta del elemento, viewport, tema y captura. Después los agentes hacen triage desde el almacén, pesando quién lo escribió (Justin vinculante, la dueña vinculante en reglas de negocio, el equipo una petición, un cliente una señal) y registrando triage, nota y referencia de decisión antes de cambiar nada.' },
  'qa.testing.feedbackBlocked': { en: 'The feedback entity does not exist yet, so the button below is a Placeholder (P-09) and this page cannot list anything.', es: 'La entidad feedback todavía no existe, así que el botón de abajo es un Placeholder (P-09) y esta página no puede listar nada.' },
  'qa.testing.fileBug': { en: 'File a bug', es: 'Reportar un error' },
  'qa.testing.fileBugWhat': { en: 'pin a bug to this element and write a feedback row with author, role, page code, viewport and theme', es: 'anclar un error a este elemento y escribir una fila de feedback con autor, rol, código de página, viewport y tema' },
  'qa.testing.notWired': { en: 'Not wired yet', es: 'Todavía sin conectar' },
  'qa.testing.rowNotFound': { en: 'No route with the code {code}', es: 'No hay ninguna ruta con el código {code}' },
};
