import type { StringTable } from '../../i18n/types';

/**
 * Brand portal strings (P-13). English primary, Spanish complete: the studio works in Spanish
 * (D-004) and Angélica's roster was written in Spanish (docs/knowledge/team.md).
 */
export const strings: StringTable = {
  // --- navigation -----------------------------------------------------------
  'brand.nav.home': { en: 'Dashboard', es: 'Panel' },
  'brand.nav.competitions': { en: 'Competitions', es: 'Concursos' },
  'brand.nav.presentations': { en: 'Presentations', es: 'Presentaciones' },
  'brand.nav.identity': { en: 'Identity', es: 'Identidad' },
  'brand.nav.images': { en: 'Client images', es: 'Imágenes cliente' },
  'brand.nav.revisions': { en: 'Revisions', es: 'Revisiones' },
  'brand.nav.assets': { en: 'Asset library', es: 'Biblioteca' },

  // --- shared ---------------------------------------------------------------
  'brand.unknown': { en: 'unknown', es: 'desconocido' },
  'brand.noProject': { en: 'no project', es: 'sin proyecto' },
  'brand.noDue': { en: 'no date', es: 'sin fecha' },
  'brand.shown': { en: '{shown} of {total}', es: '{shown} de {total}' },
  'brand.save': { en: 'Save', es: 'Guardar' },
  'brand.advance': { en: 'Advance', es: 'Avanzar' },
  'brand.advanceTo': { en: 'Move to {status}', es: 'Pasar a {status}' },
  'brand.col.status': { en: 'Status', es: 'Estado' },
  'brand.col.kind': { en: 'Kind', es: 'Tipo' },
  'brand.col.project': { en: 'Project', es: 'Proyecto' },
  'brand.col.due': { en: 'Due', es: 'Entrega' },
  'brand.col.owner': { en: 'Owner', es: 'Responsable' },
  'brand.col.requestedBy': { en: 'Requested by', es: 'Solicitado por' },
  'brand.filter.status': { en: 'Status', es: 'Estado' },
  'brand.filter.kind': { en: 'Kind', es: 'Tipo' },
  'brand.filter.project': { en: 'Project', es: 'Proyecto' },
  'brand.filter.allStatuses': { en: 'All statuses', es: 'Todos los estados' },
  'brand.filter.allKinds': { en: 'All kinds', es: 'Todos los tipos' },
  'brand.filter.allProjects': { en: 'All projects', es: 'Todos los proyectos' },
  'brand.kind.sales': { en: 'Sales', es: 'Ventas' },
  'brand.kind.concept': { en: 'Concept', es: 'Concepto' },
  'brand.kind.proposal': { en: 'Proposal', es: 'Propuesta' },
  'brand.kind.competition': { en: 'Competition', es: 'Concurso' },
  'brand.kind.image': { en: 'Images', es: 'Imágenes' },
  'brand.kind.layout': { en: 'Layout', es: 'Diagramación' },
  'brand.kind.pdf': { en: 'PDF', es: 'PDF' },
  'brand.kind.presentation': { en: 'Presentation', es: 'Presentación' },
  'brand.kind.social': { en: 'Social', es: 'Redes' },
  'brand.assetKind.logo': { en: 'Logos', es: 'Logotipos' },
  'brand.assetKind.typography': { en: 'Typography', es: 'Tipografía' },
  'brand.assetKind.palette': { en: 'Palette', es: 'Paleta' },
  'brand.assetKind.template': { en: 'Templates', es: 'Plantillas' },
  'brand.assetKind.photo': { en: 'Photography', es: 'Fotografía' },
  'brand.assetKind.icon': { en: 'Icons', es: 'Iconos' },
  'brand.assetKind.guideline': { en: 'Identity manual', es: 'Manual de identidad' },

  // --- G-01 dashboard -------------------------------------------------------
  'brand.home.title': { en: 'Brand dashboard', es: 'Panel de marca' },
  'brand.home.desc': {
    en: 'Competitions calendar, sales presentations, brand identity, client images, graphic revisions and the asset library.',
    es: 'Calendario de concursos, presentaciones de ventas, identidad de marca, imágenes para clientes, revisiones gráficas y biblioteca de activos.',
  },
  'brand.home.stat.competitions': { en: 'Competitions 2027', es: 'Concursos 2027' },
  'brand.home.stat.competitionsHint': { en: '{dated} with a date, {undated} unknown', es: '{dated} con fecha, {undated} desconocidas' },
  'brand.home.stat.presentations': { en: 'Open presentations', es: 'Presentaciones abiertas' },
  'brand.home.stat.presentationsHint': { en: '{n} in total', es: '{n} en total' },
  'brand.home.stat.revisions': { en: 'Revisions in the queue', es: 'Revisiones en cola' },
  'brand.home.stat.revisionsHint': { en: '{n} delivered, waiting for approval', es: '{n} entregadas, esperando aprobación' },
  'brand.home.stat.assets': { en: 'Current brand assets', es: 'Activos de marca vigentes' },
  'brand.home.stat.assetsHint': { en: '{n} superseded', es: '{n} obsoletos' },
  'brand.home.deadlines': { en: 'Next deadlines', es: 'Próximas entregas' },
  'brand.home.deadlinesSub': { en: 'Competitions, presentations and revisions that carry a date.', es: 'Concursos, presentaciones y revisiones que tienen fecha.' },
  'brand.home.noDeadlines': { en: 'Nothing dated yet', es: 'Nada con fecha todavía' },
  'brand.home.noDeadlinesDesc': {
    en: 'The 2027 competition submission dates have not been shared yet, so nothing can be scheduled from here.',
    es: 'Aún no se han compartido las fechas de entrega de los concursos 2027, así que todavía no hay nada que programar.',
  },
  'brand.home.deadline.competition': { en: 'Competition', es: 'Concurso' },
  'brand.home.deadline.presentation': { en: 'Presentation', es: 'Presentación' },
  'brand.home.deadline.revision': { en: 'Revision', es: 'Revisión' },
  'brand.home.alerts': { en: 'Alerts for this role', es: 'Alertas de este rol' },
  'brand.home.alertsSub': { en: 'Raised before things become urgent; operations manages them.', es: 'Se avisan antes de que sean urgentes; operaciones las gestiona.' },
  'brand.home.alertLead': { en: 'Due {date} · warns {days} days ahead', es: 'Vence {date} · avisa {days} días antes' },
  'brand.home.noAlerts': { en: 'No open alerts', es: 'Sin alertas abiertas' },
  'brand.home.open': { en: 'Open {section}', es: 'Abrir {section}' },
  'brand.home.section.competitions': { en: 'Competitions 2027', es: 'Concursos 2027' },
  'brand.home.section.presentations': { en: 'Sales presentations', es: 'Presentaciones de ventas' },
  'brand.home.section.identity': { en: 'Brand identity', es: 'Identidad de marca' },
  'brand.home.section.images': { en: 'Images for clients', es: 'Imágenes para clientes' },
  'brand.home.section.revisions': { en: 'Graphic revisions queue', es: 'Cola de revisiones gráficas' },
  'brand.home.section.assets': { en: 'Graphic assets library', es: 'Biblioteca de activos gráficos' },
  'brand.home.sectionDesc.competitions': { en: '20 slots by submission date, with their materials folders.', es: '20 cupos por fecha de entrega, con sus carpetas de materiales.' },
  'brand.home.sectionDesc.presentations': { en: 'Decks from requested to final.', es: 'Presentaciones de solicitada a final.' },
  'brand.home.sectionDesc.identity': { en: 'Logos, typography, palette, templates and the manual.', es: 'Logotipos, tipografía, paleta, plantillas y el manual.' },
  'brand.home.sectionDesc.images': { en: 'Image sets prepared for each client.', es: 'Conjuntos de imágenes preparados para cada cliente.' },
  'brand.home.sectionDesc.revisions': { en: 'What the studio has asked you to revise.', es: 'Lo que el estudio te ha pedido revisar.' },
  'brand.home.sectionDesc.assets': { en: 'How the graphic files are organized.', es: 'Cómo están organizados los archivos gráficos.' },

  // --- G-02 competitions ----------------------------------------------------
  'brand.competitions.title': { en: 'Competitions 2027', es: 'Concursos 2027' },
  'brand.competitions.subtitle': {
    en: '20 slots, ordered by submission date; slots without a date come last. Nothing here is guessed: what has not been shared shows as unknown.',
    es: '20 cupos, ordenados por fecha de entrega; los cupos sin fecha van al final. Nada aquí se inventa: lo que no se ha compartido aparece como desconocido.',
  },
  'brand.competitions.slotN': { en: 'Slot {n}', es: 'Cupo {n}' },
  'brand.competitions.stat.slots': { en: 'Slots', es: 'Cupos' },
  'brand.competitions.stat.slotsHint': { en: 'The programme is 20 competitions', es: 'El programa son 20 concursos' },
  'brand.competitions.stat.dated': { en: 'With a submission date', es: 'Con fecha de entrega' },
  'brand.competitions.stat.undated': { en: 'Date unknown', es: 'Fecha desconocida' },
  'brand.competitions.stat.undatedHint': { en: 'Fill them in as the calls arrive', es: 'Se completan a medida que llegan las convocatorias' },
  'brand.competitions.stat.submitted': { en: 'Submitted', es: 'Entregados' },
  'brand.competitions.searchPlaceholder': { en: 'Competition, organiser, project, folder', es: 'Concurso, organizador, proyecto, carpeta' },
  'brand.competitions.viewLabel': { en: 'Competitions view', es: 'Vista de concursos' },
  'brand.competitions.tab.table': { en: 'List', es: 'Lista' },
  'brand.competitions.tab.calendar': { en: 'Calendar', es: 'Calendario' },
  'brand.competitions.calendarLabel': { en: 'Competition submission dates', es: 'Fechas de entrega de concursos' },
  'brand.competitions.col.slot': { en: '#', es: '#' },
  'brand.competitions.col.name': { en: 'Competition', es: 'Concurso' },
  'brand.competitions.col.organiser': { en: 'Organiser', es: 'Organizador' },
  'brand.competitions.col.category': { en: 'Category', es: 'Categoría' },
  'brand.competitions.col.date': { en: 'Submission date', es: 'Fecha de entrega' },
  'brand.competitions.col.project': { en: 'Project entered', es: 'Proyecto inscrito' },
  'brand.competitions.col.folder': { en: 'Materials folder', es: 'Carpeta de materiales' },
  'brand.competitions.col.status': { en: 'Status', es: 'Estado' },
  'brand.competitions.col.result': { en: 'Result', es: 'Resultado' },
  'brand.competitions.empty': { en: 'No slot matches the filters', es: 'Ningún cupo coincide con los filtros' },
  'brand.competitions.emptyDesc': { en: 'Clear the filters to see the 20 slots of the 2027 programme.', es: 'Limpia los filtros para ver los 20 cupos del programa 2027.' },
  'brand.competitions.formHint': {
    en: 'Fill in what the call actually says. Anything left empty stays unknown.',
    es: 'Completa lo que diga la convocatoria. Lo que quede vacío se mantiene como desconocido.',
  },
  'brand.competitions.folderHint': { en: 'For example: Concursos 2027/05 - Name of the competition', es: 'Por ejemplo: Concursos 2027/05 - Nombre del concurso' },
  'brand.competitions.saved': { en: 'Competition saved', es: 'Concurso guardado' },
  'brand.competitions.advanced': { en: 'Slot {slot} is now {status}', es: 'El cupo {slot} pasa a {status}' },
  'brand.competitions.import': { en: 'Import the list', es: 'Importar la lista' },
  'brand.competitions.importWhat': { en: 'import the competition list', es: 'importar la lista de concursos' },
  'brand.competitions.openFolder': { en: 'Open materials folder', es: 'Abrir carpeta de materiales' },
  'brand.competitions.folderWhat': { en: 'open the materials folder', es: 'abrir la carpeta de materiales' },

  // --- G-03 presentations ---------------------------------------------------
  'brand.presentations.title': { en: 'Sales presentations', es: 'Presentaciones de ventas' },
  'brand.presentations.subtitle': {
    en: 'Every deck, from the request to the final file: sales, concept, proposal and competition.',
    es: 'Cada presentación, de la solicitud al archivo final: ventas, concepto, propuesta y concurso.',
  },
  'brand.presentations.stat.open': { en: 'Open', es: 'Abiertas' },
  'brand.presentations.stat.review': { en: 'In review', es: 'En revisión' },
  'brand.presentations.stat.final': { en: 'Final', es: 'Finales' },
  'brand.presentations.stat.overdue': { en: 'Overdue', es: 'Vencidas' },
  'brand.presentations.searchPlaceholder': { en: 'Title or project', es: 'Título o proyecto' },
  'brand.presentations.col.title': { en: 'Presentation', es: 'Presentación' },
  'brand.presentations.col.slides': { en: 'Slides', es: 'Láminas' },
  'brand.presentations.notStarted': { en: 'not started', es: 'sin empezar' },
  'brand.presentations.empty': { en: 'No presentation matches the filters', es: 'Ninguna presentación coincide con los filtros' },
  'brand.presentations.advanced': { en: '{title} is now {status}', es: '{title} pasa a {status}' },
  'brand.presentations.request': { en: 'Request a deck', es: 'Solicitar presentación' },
  'brand.presentations.requestWhat': { en: 'request a new deck', es: 'solicitar una presentación' },
  'brand.presentations.openDeck': { en: 'Open the file', es: 'Abrir el archivo' },
  'brand.presentations.openDeckWhat': { en: 'open the deck file', es: 'abrir el archivo' },

  // --- G-04 identity --------------------------------------------------------
  'brand.identity.title': { en: 'Brand identity and assets', es: 'Identidad de marca y activos' },
  'brand.identity.subtitle': {
    en: "Aluzina's identity in one place, so the same logo, type, palette and templates are applied everywhere.",
    es: 'La identidad de Aluzina en un solo lugar, para aplicar siempre el mismo logotipo, tipografía, paleta y plantillas.',
  },
  'brand.identity.stat.current': { en: 'Current', es: 'Vigentes' },
  'brand.identity.stat.draft': { en: 'Draft', es: 'Borrador' },
  'brand.identity.stat.superseded': { en: 'Superseded', es: 'Obsoletos' },
  'brand.identity.stat.supersededHint': { en: 'Kept visible so nobody reuses them', es: 'Se muestran para que nadie los reutilice' },
  'brand.identity.col.name': { en: 'Asset', es: 'Activo' },
  'brand.identity.col.format': { en: 'Format', es: 'Formato' },
  'brand.identity.col.version': { en: 'Version', es: 'Versión' },
  'brand.identity.col.path': { en: 'Path', es: 'Ruta' },
  'brand.identity.kindCount': { en: '{n} files', es: '{n} archivos' },
  'brand.identity.doNotUse': { en: 'do not use', es: 'no usar' },
  'brand.identity.supersede': { en: 'Mark superseded', es: 'Marcar obsoleto' },
  'brand.identity.restore': { en: 'Mark current', es: 'Marcar vigente' },
  'brand.identity.marked': { en: '{name}: {status}', es: '{name}: {status}' },
  'brand.identity.manual': { en: 'Identity manual', es: 'Manual de identidad' },
  'brand.identity.manualSub': { en: 'The rules everyone applies.', es: 'Las reglas que todos aplican.' },
  'brand.identity.manualOutdated': { en: 'The manual on file is superseded: a current version is missing.', es: 'El manual archivado está obsoleto: falta una versión vigente.' },
  'brand.identity.noManual': { en: 'No manual on file', es: 'Sin manual archivado' },
  'brand.identity.noManualDesc': { en: 'Upload the identity manual so the rest of the team can apply it.', es: 'Sube el manual de identidad para que el resto del equipo pueda aplicarlo.' },
  'brand.identity.openManual': { en: 'Open the manual', es: 'Abrir el manual' },
  'brand.identity.openManualWhat': { en: 'open the manual', es: 'abrir el manual' },
  'brand.identity.upload': { en: 'Upload a version', es: 'Subir una versión' },
  'brand.identity.uploadWhat': { en: 'upload a new version', es: 'subir una versión nueva' },
  'brand.identity.applying': { en: 'Applying the identity', es: 'Aplicar la identidad' },
  'brand.identity.applyingSub': { en: 'Checks that keep every piece consistent.', es: 'Verificaciones que mantienen la consistencia de cada pieza.' },
  'brand.identity.check': { en: 'Check a file', es: 'Revisar un archivo' },
  'brand.identity.checkWhat': { en: 'check a file', es: 'revisar un archivo' },
  'brand.identity.tokens': { en: 'Design tokens', es: 'Tokens de diseño' },
  'brand.identity.tokensWhat': { en: 'open the design tokens', es: 'abrir los tokens de diseño' },

  // --- G-05 images ----------------------------------------------------------
  'brand.images.title': { en: 'Images for clients', es: 'Imágenes para clientes' },
  'brand.images.subtitle': {
    en: 'The image sets prepared for each client, grouped by project, from the request to the approval.',
    es: 'Los conjuntos de imágenes preparados para cada cliente, agrupados por proyecto, de la solicitud a la aprobación.',
  },
  'brand.images.searchPlaceholder': { en: 'Image set or project', es: 'Conjunto de imágenes o proyecto' },
  'brand.images.col.title': { en: 'Image set', es: 'Conjunto de imágenes' },
  'brand.images.setCount': { en: '{n} sets', es: '{n} conjuntos' },
  'brand.images.empty': { en: 'No image set matches the filters', es: 'Ningún conjunto coincide con los filtros' },
  'brand.images.emptyDesc': { en: 'Image sets are the revisions of kind "images"; the other kinds live in the revisions queue.', es: 'Los conjuntos de imágenes son las revisiones de tipo «imágenes»; los demás tipos están en la cola de revisiones.' },
  'brand.images.advanced': { en: '{title} is now {status}', es: '{title} pasa a {status}' },
  'brand.images.new': { en: 'New image set', es: 'Nuevo conjunto' },
  'brand.images.newWhat': { en: 'prepare a new image set', es: 'preparar un conjunto nuevo' },
  'brand.images.share': { en: 'Share with the client', es: 'Compartir con el cliente' },
  'brand.images.shareWhat': { en: 'share with the client', es: 'compartir con el cliente' },
  'brand.images.preview': { en: 'Image previews', es: 'Vistas previas de las imágenes' },
  'brand.images.previewWhat': { en: 'show the thumbnails', es: 'mostrar las miniaturas' },

  // --- G-06 revisions -------------------------------------------------------
  'brand.revisions.title': { en: 'Graphic revisions queue', es: 'Cola de revisiones gráficas' },
  'brand.revisions.subtitle': {
    en: 'What the studio has asked you to revise, from requested to approved. Cards move with buttons, never by dragging only.',
    es: 'Lo que el estudio te ha pedido revisar, de solicitada a aprobada. Las tarjetas se mueven con botones, nunca solo arrastrando.',
  },
  'brand.revisions.boardLabel': { en: 'Revisions board', es: 'Tablero de revisiones' },
  'brand.revisions.searchPlaceholder': { en: 'Revision or project', es: 'Revisión o proyecto' },
  'brand.revisions.moved': { en: 'Moved to {status}', es: 'Movida a {status}' },
  'brand.revisions.request': { en: 'Request a revision', es: 'Solicitar revisión' },
  'brand.revisions.requestWhat': { en: 'add a revision request', es: 'agregar una solicitud' },

  // --- G-07 asset library ---------------------------------------------------
  'brand.assets.title': { en: 'Asset library organization', es: 'Organización de la biblioteca' },
  'brand.assets.subtitle': {
    en: 'The folders the graphic files live in, derived from the asset paths and the competition materials folders.',
    es: 'Las carpetas donde viven los archivos gráficos, derivadas de las rutas de los activos y de las carpetas de materiales de los concursos.',
  },
  'brand.assets.stat.folders': { en: 'Folders', es: 'Carpetas' },
  'brand.assets.stat.files': { en: 'Files', es: 'Archivos' },
  'brand.assets.stat.competition': { en: 'Competition folders', es: 'Carpetas de concursos' },
  'brand.assets.stat.competitionHint': { en: 'One per slot that has a folder', es: 'Una por cupo que tiene carpeta' },
  'brand.assets.stat.empty': { en: 'Still empty', es: 'Todavía vacías' },
  'brand.assets.stat.emptyHint': { en: 'Normal until the materials are produced', es: 'Es normal hasta que se produzcan los materiales' },
  'brand.assets.searchPlaceholder': { en: 'Folder path', es: 'Ruta de la carpeta' },
  'brand.assets.col.path': { en: 'Folder', es: 'Carpeta' },
  'brand.assets.col.source': { en: 'Source', es: 'Origen' },
  'brand.assets.col.items': { en: 'Files', es: 'Archivos' },
  'brand.assets.col.superseded': { en: 'Superseded', es: 'Obsoletos' },
  'brand.assets.source.brand': { en: 'Brand', es: 'Marca' },
  'brand.assets.source.competition': { en: 'Competition', es: 'Concurso' },
  'brand.assets.emptyFolder': { en: 'empty', es: 'vacía' },
  'brand.assets.empty': { en: 'No folder matches the search', es: 'Ninguna carpeta coincide con la búsqueda' },
  'brand.assets.newFolder': { en: 'New folder', es: 'Nueva carpeta' },
  'brand.assets.newFolderWhat': { en: 'create a folder', es: 'crear una carpeta' },
  'brand.assets.connect': { en: 'Connect storage', es: 'Conectar almacenamiento' },
  'brand.assets.connectWhat': { en: 'connect the studio storage', es: 'conectar el almacenamiento' },
  'brand.assets.notWired': { en: 'Not wired yet', es: 'Aún sin conectar' },
  'brand.assets.notWiredSub': { en: 'The hub has no file storage yet, so nothing here touches real files.', es: 'El hub todavía no tiene almacenamiento de archivos, así que nada de esto toca archivos reales.' },
  'brand.assets.upload': { en: 'Upload files', es: 'Subir archivos' },
  'brand.assets.uploadWhat': { en: 'upload files', es: 'subir archivos' },
  'brand.assets.rename': { en: 'Rename folder', es: 'Renombrar carpeta' },
  'brand.assets.renameWhat': { en: 'rename a folder', es: 'renombrar una carpeta' },
  'brand.assets.move': { en: 'Move files', es: 'Mover archivos' },
  'brand.assets.moveWhat': { en: 'move files', es: 'mover archivos' },

  // --- G-08 brand documents -------------------------------------------------
  'brand.nav.documents': { en: 'Documents', es: 'Documentos' },
  'brand.documents.title': { en: 'Brand documents', es: 'Documentos de marca' },
  'brand.documents.subtitle': {
    en: 'The portfolio and the brochure the studio sends to a client: read them here or download the current PDF.',
    es: 'El portafolio y el brochure que el estudio envía a un cliente: léelos aquí o descarga el PDF vigente.',
  },
  'brand.documents.doc.portfolio.title': { en: 'Portfolio', es: 'Portafolio' },
  'brand.documents.doc.portfolio.desc': {
    en: 'The studio portfolio: projects, spaces and the way Aluzina works with light.',
    es: 'El portafolio del estudio: proyectos, espacios y la forma en que Aluzina trabaja la luz.',
  },
  'brand.documents.doc.brochure.title': { en: 'Brochure', es: 'Brochure' },
  'brand.documents.doc.brochure.desc': {
    en: 'The short presentation of the studio and its services, for a first conversation with a client.',
    es: 'La presentación corta del estudio y sus servicios, para una primera conversación con un cliente.',
  },
  'brand.documents.pdf': { en: 'PDF document', es: 'Documento PDF' },
  'brand.documents.fileMeta': { en: 'PDF · {pages} pages · {size} MB', es: 'PDF · {pages} páginas · {size} MB' },
  'brand.documents.view': { en: 'View', es: 'Ver' },
  'brand.documents.download': { en: 'Download', es: 'Descargar' },
  'brand.documents.downloadAria': { en: 'Download {title} as a PDF', es: 'Descargar {title} en PDF' },
  'brand.documents.newTab': { en: 'Open in a new tab', es: 'Abrir en pestaña nueva' },
  'brand.documents.newTabAria': { en: 'Open {title} in a new tab', es: 'Abrir {title} en una pestaña nueva' },
  'brand.documents.share': { en: 'Share link', es: 'Copiar enlace' },
  'brand.documents.shareAria': { en: 'Copy the link to {title}', es: 'Copiar el enlace de {title}' },
  'brand.documents.shared': { en: 'Link to the {title} copied to the clipboard', es: 'Enlace del {title} copiado al portapapeles' },
  'brand.documents.shareFailed': { en: 'The clipboard is not available here. The link is {url}', es: 'El portapapeles no está disponible aquí. El enlace es {url}' },
  'brand.documents.viewer': { en: 'Viewer', es: 'Visor' },
  'brand.documents.viewerSub': { en: 'Read the document without leaving the portal.', es: 'Lee el documento sin salir del portal.' },
  'brand.documents.tabsLabel': { en: 'Document to view', es: 'Documento por ver' },
  'brand.documents.frameTitle': { en: '{title}, PDF viewer', es: '{title}, visor de PDF' },
  'brand.documents.noPdf': {
    en: 'Your browser cannot show PDFs here; download it instead.',
    es: 'Tu navegador no puede mostrar PDF aquí; descárgalo.',
  },
  'brand.documents.replace': { en: 'Replace document', es: 'Reemplazar documento' },
  'brand.documents.replaceWhat': {
    en: 'upload a new version of the portfolio or the brochure (the hub has no file storage yet)',
    es: 'subir una nueva versión del portafolio o del brochure (el hub aún no tiene almacenamiento de archivos)',
  },
  'brand.documents.storage': { en: 'Where these files live', es: 'Dónde viven estos archivos' },
  'brand.documents.storageSub': { en: 'Static files shipped with the app.', es: 'Archivos estáticos que viajan con la aplicación.' },
  'brand.documents.storageBody': {
    en: 'The portfolio and the brochure are served with the app from apps/hub/public/brand/. Until file storage exists, a new version is a commit: replace the PDF and the whole system — this page and the public page — shows it.',
    es: 'El portafolio y el brochure se sirven con la aplicación desde apps/hub/public/brand/. Mientras no exista almacenamiento de archivos, una versión nueva es un commit: reemplaza el PDF y todo el sistema —esta página y la página pública— lo muestra.',
  },
  'brand.documents.pagesInData': { en: '{count} pages as records', es: '{count} páginas como registros' },
  'brand.documents.palette': { en: 'Colours read from the file: {colors}', es: 'Colores leídos del archivo: {colors}' },
  'brand.documents.fonts': { en: 'Fonts: {fonts}', es: 'Tipografías: {fonts}' },
  'brand.documents.related': { en: 'Related', es: 'Relacionado' },
  'brand.documents.relatedProjects': { en: 'Projects its pages show ({count})', es: 'Proyectos que muestran sus páginas ({count})' },
  'brand.documents.relatedServices': { en: 'Services its pages argue for ({count})', es: 'Servicios que sustentan sus páginas ({count})' },
  'brand.documents.relatedNone': { en: 'No relations recorded for this document yet.', es: 'Este documento aún no tiene relaciones registradas.' },
  'brand.documents.relatedLoading': { en: 'Loading relations…', es: 'Cargando relaciones…' },
  'brand.documents.dataBody': {
    en: 'Each document is an assets row and each of its pages another one, related to the projects it shows and the services it argues for (Spaces > Portfolio holds one space and one note per project). The rows are seeded from docs/brand/<document>/index.json, so the repo stays the source of truth.',
    es: 'Cada documento es una fila de assets y cada una de sus páginas otra, relacionada con los proyectos que muestra y los servicios que sustenta (Espacios > Portfolio tiene un espacio y una nota por proyecto). Las filas se generan desde docs/brand/<documento>/index.json, así el repositorio sigue siendo la fuente de verdad.',
  },
  'brand.documents.company.title': { en: 'Company documents (Dropbox 2023)', es: 'Documentos de la empresa (Dropbox 2023)' },
  'brand.documents.company.subtitle': {
    en: 'The 12 files from the "00 INFORMACION RELEVANTE ALUZINA 2023" Dropbox folder: catalogues, presentations and price lists of Aluzina\'s own, plus three third-party references kept for comparison.',
    es: 'Los 12 archivos de la carpeta de Dropbox "00 INFORMACION RELEVANTE ALUZINA 2023": catálogos, presentaciones y listas de precios propios de Aluzina, más tres documentos de referencia de terceros.',
  },
  'brand.documents.company.openAria': { en: 'Open {title}', es: 'Abrir {title}' },
  'brand.documents.company.ownerOwn': { en: 'Aluzina', es: 'Aluzina' },
  'brand.documents.company.ownerThirdParty': { en: 'Third party', es: 'Terceros' },
  'brand.documents.company.visibilityPublic': { en: 'Public', es: 'Público' },
  'brand.documents.company.visibilityInternal': { en: 'Internal', es: 'Interno' },
  'brand.documents.company.noPreview': {
    en: 'No preview for this file (price list or third-party material): open it at the source instead.',
    es: 'Este archivo no tiene vista previa (lista de precios o material de terceros): ábrelo en el origen.',
  },
  'brand.documents.company.openSource': { en: 'Open at source', es: 'Abrir en el origen' },
  'brand.documents.company.close': { en: 'Close', es: 'Cerrar' },
  'brand.documents.company.pages': { en: '{count} pages', es: '{count} páginas' },
  'brand.documents.company.pagesOne': { en: '1 page', es: '1 página' },
  'brand.documents.company.viewerFallback': { en: 'This file cannot be shown here; open it at the source.', es: 'Este archivo no se puede mostrar aquí; ábrelo en el origen.' },
  'brand.documents.company.viewerDownload': { en: 'Download', es: 'Descargar' },
  'brand.documents.company.viewerPosition': { en: 'Page {index} of {total}', es: 'Página {index} de {total}' },
  'brand.documents.company.viewerPrev': { en: 'Previous page', es: 'Página anterior' },
  'brand.documents.company.viewerNext': { en: 'Next page', es: 'Página siguiente' },
  'brand.documents.company.viewerThumbnails': { en: 'Pages', es: 'Páginas' },
  'brand.home.documents': { en: 'Client documents', es: 'Documentos para clientes' },
  'brand.home.documentsSub': { en: 'The portfolio and the brochure, ready to view, download or share.', es: 'El portafolio y el brochure, listos para ver, descargar o compartir.' },
  'brand.home.viewDoc': { en: 'View', es: 'Ver' },
  'brand.home.viewDocAria': { en: 'View {title} in the document viewer', es: 'Ver {title} en el visor de documentos' },
  'brand.home.section.documents': { en: 'Brand documents', es: 'Documentos de marca' },
  'brand.home.sectionDesc.documents': { en: 'Portfolio and brochure: view, download, share.', es: 'Portafolio y brochure: ver, descargar, compartir.' },
};
