import { HOY_SECTIONS, HOY_TASKS } from './asana/hoy';
import { PROJECT_IDS, TASK_DEFAULTS } from './projects';
import type { SeedCtx } from './types';

/** After projects (0) and work (1): the sections and tasks belong to `prj-hoy`. */
export const order = 2;

/**
 * PROYECTO HOY as the founder actually keeps it (D-063): the four sections and all 212 tasks of the Asana
 * export, nested through `parentTaskId`, tagged `asana`, each carrying its `asana:<Task ID>` as `externalId`
 * and the deliverable its title maps to. Generated by `npm run import:asana` into `./asana/{hoy,portfolio}.ts`;
 * this module only turns that data into rows, so re-importing never means re-writing seed logic.
 *
 * The project's own placeholder tasks and sections were removed from `seed/projects.ts` and `seed/work.ts`
 * in the same pass: HOY has one task tree, not two. The export carries no dates, so the Timeline view of
 * this project is empty until the founder schedules it — that is what Asana holds today, not a defect.
 *
 * What is **not** asserted here: that PROYECTO HOY is HOY Wellness Center, or that ZONE 1..11 are HOY's
 * spaces rather than residue of the 2023 project the template grew out of. The question is kept visible in
 * the project summary and in `docs/knowledge/asana-conventions.md`; nothing is cleaned up on the founder's
 * behalf (the 2023 vendor names `federico` and `semco` survive in the titles, as they do in Asana).
 */
export function seed({ add }: SeedCtx): void {
  for (const s of HOY_SECTIONS) add('sections', s.id, { projectId: PROJECT_IDS.hoy, name: s.name, order: s.order });

  for (const t of HOY_TASKS) {
    add('tasks', t.id, {
      ...TASK_DEFAULTS,
      projectId: PROJECT_IDS.hoy,
      sectionId: t.sectionId,
      parentTaskId: t.parentTaskId,
      title: t.title,
      description: t.description,
      ownerRole: t.ownerRole,
      assigneeId: t.assigneeId,
      status: t.status,
      priority: 'normal',
      startDate: t.startDate,
      dueDate: t.dueDate,
      dependsOn: [],
      tags: ['asana'],
      completedAt: t.completedAt,
      order: t.order,
      deliverableId: t.deliverableId,
      externalId: t.externalId,
    });
  }
}
